### ISSUE TITLE
MS ToDo Compatibility

### ISSUE THREAD

**Issue by Nathan-Harlan** [microsoftgraph/msgraph-sdk-python#106]
Hello,

I am attempting to connect to MS ToDo by adapting the provided tutorial here: https://learn.microsoft.com/en-us/graph/tutorials/python?tabs=aad

A Problem I have been running into is the TodoRequestBuilderDeleteRequestConfiguration object seems to require query_parameters attribute even though it does not seem to allow it when first instantiated. The specific function I have is:

~~~python
    async def get_list_of_tasks(self):

        request_config = TodoRequestBuilder.TodoRequestBuilderGetRequestConfiguration()
        
        messages = await self.user_client.me.todo.lists_by_id('all').get(
                request_configuration=request_config)
        return messages
~~~

This is new territory for me so it's possible I am just misinterpreting how this is supposed to work.

**Comment by samwelkanda** [comment]
Hi @Nathan-Harlan. Thanks for trying out our library!

`RequestConfiguration` object is used to customize the request before sending e.g adding query parameters, custom headers etc. This means it's an optional parameter and you do not need to pass it in the `get()` call.

```py
    async def get_list_of_tasks(self):

        request_config = TodoRequestBuilder.TodoRequestBuilderGetRequestConfiguration()
        
        messages = await self.user_client.me.todo.lists_by_id('all').get()
        return messages
```

**Comment by samwelkanda** [comment]
Closing for now, feel free to re-open if your issue is not resolved.

**Comment by Nathan-Harlan** [comment]
Hi @samwelkanda,
Thanks for answering the question! It seems that I am still having issues connecting to ms todo. I can get tasks lists but it does not show the tasks in them.

**A more direct question I have: Is there a way to use this library for authentication, but then use regular http GET/POST and so on requests and receive the output as JSON data?**

I am hoping for something super basic like this using the API docs [here](https://learn.microsoft.com/en-us/graph/todo-concept-overview?view=graph-rest-1.0):

~~~python
response = self.user_client.me.request('GET', 'https://graph.microsoft.com/v1.0/me/todo/lists')
~~~

Alternatively, can I configure the message and authorization using this library and then use httpx.requests() method to send and receive it?

Again, many thanks for your time helping me out and the effort put into this library!

-NH

**Comment by Nathan-Harlan** [comment]
Hi @samwelkanda,

I am opnening this back up as I think the compatibility is still in question. I might be wayyy wrong so no worries if this is better off closed, but here is the issue I am having after solving the basic setup issues. Thanks for any advice you can give on solving this!

## Problem description 
With the current library, the client.me.todo methods can only access "list" information. No matter what the actual MS ToDo app shows in those lists, the "tasks" attribute is always "None". Here is some example output from the script below. Note, the "tasks: None" section in the output from each list.

~~~console
Name:  Tasks  tasks:  None  id:  AAMk...
Name:  sharing test  tasks:  None  id:  AAMk...
Name:  Tags  tasks:  None  id:  AAMk...
Name:  test list  tasks:  None  id:  AAMk...
Name:  testapi  tasks:  None  id:  AAMk...
Name:  Flagged Emails  tasks:  None  id:  AAMk...
~~~

## Solution options:
* One solution for this would be a clean way to get and send raw http GET/POST etc. requests using this library to authenticate.
* The other would be a possible fix to the code below if I am missing something or if this library needs additions

### code to recreate the problem
I have created a stand alone test for the problem I am seeing. It is just a cfg file for my api info and this python script:
~~~python
import asyncio
from azure.identity import DeviceCodeCredential
from kiota_authentication_azure.azure_identity_authentication_provider import AzureIdentityAuthenticationProvider
from msgraph import GraphRequestAdapter, GraphServiceClient
from msgraph.generated.me.todo.lists.lists_request_builder import ListsRequestBuilder
from kiota_abstractions.native_response_handler import NativeResponseHandler
import httpx
import configparser

# Load settings
config = configparser.ConfigParser()
config.read(['config.cfg', 'config.dev.cfg'])
azure_settings = config['azure']
settings = azure_settings
client_id = settings['clientId']
tenant_id = settings['tenantId']
graph_scopes = settings['graphUserScopes'].split(' ')

# Authentication
device_code_credential = DeviceCodeCredential(client_id, tenant_id = tenant_id)
auth_provider = AzureIdentityAuthenticationProvider(
    device_code_credential,
    scopes=graph_scopes)

# instances
request_adapter = GraphRequestAdapter(auth_provider)
client = GraphServiceClient(request_adapter)


async def main():
    t_lists = await get_lists()

    # show all the lists:
    [print('Name: ', a.display_name, ' tasks: ', a.tasks, ' id: ', a.id) for a in t_lists.value]
    print('/n')

    # attempt to get a task from first list via lists_by_id method:
    first_list_tasks = await get_lists_by_id(t_lists.value[0].id)
    print('tasks:', first_list_tasks.tasks)


async def get_lists():
    t_lists = await client.me.todo.lists.get()
    return t_lists


async def get_lists_by_id(list_id):
    t_lists = await client.me.todo.lists_by_id(list_id).get()
    return t_lists


asyncio.run(main())
~~~

The config format as a file named : "config.cfg" I have removed my client and tenant ids.

~~~ config
[azure]
clientId = REMOVED
tenantId = REMOVED
graphUserScopes = User.Read Mail.Read Mail.Send Tasks.ReadWrite
~~~

**Comment by Nathan-Harlan** [comment]
Hi @samwelkanda,

I created a new issue with a better description. Hope this helps to clear up the problem. #111 

Thanks a lot!
