### ISSUE TITLE
Get message content error

### ISSUE THREAD

**Issue by dpslavov** [microsoftgraph/msgraph-sdk-python#118]
# The error
Following sample code generates exception:
```
...
response = await GraphServiceClient(GraphRequestAdapter(auth_provider)).me.messages_by_id(id).content.get()
...
```
```
...
File "/home/vscode/getmail/getmail.py", line 101, in getmail
    response = await GraphServiceClient(GraphRequestAdapter(auth_provider)).me.messages_by_id(id).content.get()
  File "/home/vscode/.local/lib/python3.9/site-packages/msgraph/generated/me/messages/item/value/content_request_builder.py", line 53, in get
    return await self.request_adapter.send_primitive_async(request_info, "bytes", error_mapping)
  File "/home/vscode/.local/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py", line 227, in send_primitive_async
    raise Exception("Found unexpected type to deserialize")
Exception: Found unexpected type to deserialize
```

Package                              Version
------------------------------------ ---------
aiohttp                              3.8.4
aiosignal                            1.3.1
anyio                                3.6.2
async-timeout                        4.0.2
attrs                                22.2.0
azure-core                           1.26.3
azure-identity                       1.12.0
cachetools                           5.3.0
certifi                              2022.12.7
cffi                                 1.15.1
charset-normalizer                   3.0.1
cryptography                         39.0.1
frozenlist                           1.3.3
google-api-core                      2.11.0
google-api-python-client             2.74.0
google-auth                          2.16.0
google-auth-httplib2                 0.1.0
google-auth-oauthlib                 0.8.0
googleapis-common-protos             1.58.0
h11                                  0.14.0
h2                                   4.1.0
hpack                                4.0.0
httpcore                             0.16.3
httplib2                             0.21.0
httpx                                0.23.3
hyperframe                           6.0.1
idna                                 3.4
microsoft-kiota-abstractions         0.4.0
microsoft-kiota-authentication-azure 0.2.0
microsoft-kiota-http                 0.4.0
microsoft-kiota-serialization-json   0.2.1
microsoft-kiota-serialization-text   0.2.0
msal                                 1.21.0
msal-extensions                      1.0.0
msgraph-core                         1.0.0a4
msgraph-sdk                          1.0.0a9
multidict                            6.0.4
oauthlib                             3.2.2
pip                                  22.3.1
portalocker                          2.7.0
protobuf                             4.21.12
pyasn1                               0.4.8
pyasn1-modules                       0.2.8
pycparser                            2.21
PyJWT                                2.6.0
pyparsing                            3.0.9
python-dateutil                      2.8.2
requests                             2.28.2
requests-oauthlib                    1.3.1
rfc3986                              1.5.0
rsa                                  4.9
setuptools                           67.0.0
six                                  1.16.0
sniffio                              1.3.0
typing_extensions                    4.4.0
uritemplate                          4.1.1
urllib3                              1.26.14
wheel                                0.38.4
yarl                                 1.8.2

# The workaround
Use native HTTPX response and parse it:
```
request_configuration = MessagesRequestBuilder.MessagesRequestBuilderGetRequestConfiguration(
    options=[ResponseHandlerOption(NativeResponseHandler())]
)
response = await GraphServiceClient(GraphRequestAdapter(auth_provider)).me.messages_by_id(id).content.get(request_configuration=request_configuration)
```

**Comment by samwelkanda** [comment]
Hey @dpslavov, 

Thank you for reporting this issue. 

The bug was resolved a while ago and the call should give you the bytes content of the message. Closing this for now, feel free to re-open if you have further questions. 

Thanks!
