### ISSUE TITLE
Send message in a Teams channel using msgraph-sdk-python

### ISSUE THREAD

**Issue by nic0CD** [microsoftgraph/msgraph-sdk-python#120]
Hello,

I have been trying to find a way to send a message in a Teams channel using msgraph-sdk-python but I do not seem to find it. Is there a method for this matter? And if there is one, where can I find the post function ?

I noticed that I can do this with **Graph Explorer** using the {team ID} and the {channel ID} in the Beta version of Microsoft Teams.

Thank you for your time

**Comment by samwelkanda** [comment]
Hi @nic0CD 

Thanks for trying out our SDK!

Here's a code sample to send a message in a teams channel using `v1.0.0a12` of the SDK:

```py
from msgraph.generated.models.chat_message import ChatMessage
from msgraph.generated.models.item_body import ItemBody

async def send_message_channel():
    
    try:
        msg_body = ChatMessage()
        chat_body = ItemBody()
        chat_body.content = 'Hi there!'
        msg_body.body = chat_body
        message = await client.teams.by_team_id(
            'TEAM_ID').channels.by_channel_id(
                'CHANNEL_ID').messages.post(msg_body)
        if message:
            print(message.id, message.body, message.channel_identity, message.chat_id)
    except Exception as e:
        print(e.error.message)
asyncio.run(send_message_channel())
```

**Comment by samwelkanda** [comment]
Closing for now, feel free to re-open if you have further questions.
