### ISSUE TITLE
Incorrectly configured request headers in me_request_builder.py

### ISSUE THREAD

**Issue by iargue** [microsoftgraph/msgraph-sdk-python#134]
Version:
> msgraph-sdk                          1.0.0a9

When attempting to run the Microsoft Graph SDK for python, an error is thrown during execution.

Source Tutorial: https://learn.microsoft.com/en-us/graph/tutorials/python?tabs=aad&tutorial-step=4

In this step, running `user = await self.user_client.me.get(request_configuration=request_config)` will fail. wrapping this in an try/except clause provides the following error.

> Error: The MIME type 'a, p, p, l, i, c, a, t, i, o, n, /, j, s, o, n' requires a '/' character between type and subtype, such as 'text/plain'.

**Comment by iargue** [comment]
Cause:

Header is being configured as a string

https://github.com/microsoftgraph/msgraph-sdk-python/blame/74694859b0f92b9d9336939669b1e29669ae1706/msgraph/generated/me/me_request_builder.py#L1081
`request_info.headers["Accept"] = "application/json"`

And
https://github.com/microsoftgraph/msgraph-sdk-python/blame/74694859b0f92b9d9336939669b1e29669ae1706/msgraph/generated/me/me_request_builder.py#L1102
`request_info.headers["Accept"] = "application/json"`

This was corrected and currently is providing the header as an list.

https://github.com/microsoftgraph/msgraph-sdk-python/blame/main/msgraph/generated/me/me_request_builder.py#L1081
`request_info.headers["Accept"] = ["application/json"]`
https://github.com/microsoftgraph/msgraph-sdk-python/blame/main/msgraph/generated/me/me_request_builder.py#L1102
`request_info.headers["Accept"] = ["application/json"]`

Pip does not have this version currently, it's highly recommended to push this out to Pip as the project is currently broken with this implementation.

The issue is widespread across the project, affecting other graph entries, such as Security Incidents.

**Comment by iargue** [comment]
If anyone is wanting to use the SDK while the pip version is broken, you can get the version directly from Github. This will resolve all MIME type issues, but may or may not introduce other issues.

`pip install --upgrade 'msgraph-sdk @ git+https://github.com/microsoftgraph/msgraph-sdk-python.git'`

**Comment by tristan-martin-orangecyberdefense** [comment]
This issue is arising because of dependency on microsoft-kiota-serialization-json
The last version of this package is 0.3.0 and this brock the sdk.

If you force this package on version 0.2.2 you will fix this issue.

Just put microsoft-kiota-serialization-json==0.2.2 in your requirement file.

**Comment by datenzauberai** [comment]
> This issue is arising because of dependency on microsoft-kiota-serialization-json
> The last version of this package is 0.3.0 and this brock the sdk.
> If you force this package on version 0.2.2 you will fix this issue.

0.2.2 did not fix the issue for me.

```
(.venv) >pip show microsoft-kiota-serialization-json
Name: microsoft-kiota-serialization-json
Version: 0.2.2

(.venv) >python.exe test.py
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ... to authenticate.
Error: The MIME type 'a, p, p, l, i, c, a, t, i, o, n, /, j, s, o, n' requires a '/' character between type and subtype, such as 'text/plain'.
```

**Comment by atiaar** [comment]
Hello, same for me. I had to pull the package msgraph-sdk from github directly as explained by @iargue 

> If anyone is wanting to use the SDK while the pip version is broken, you can get the version directly from Github. This will resolve all MIME type issues, but may or may not introduce other issues.
> 
> `pip install --upgrade 'msgraph-sdk @ git+https://github.com/microsoftgraph/msgraph-sdk-python.git'`

**Comment by aristosvo** [comment]
I have some troubles executing this command using Azure DevOps agents:

```
Collecting msgraph-sdk@ git+https://github.com/microsoftgraph/msgraph-sdk-python.git
  Cloning https://github.com/microsoftgraph/msgraph-sdk-python.git to /tmp/pip-install-ntunvlyu/msgraph-sdk_9fcb04736acc4f958f7370cb0cb07107
  Running command git clone --filter=blob:none --quiet https://github.com/microsoftgraph/msgraph-sdk-python.git /tmp/pip-install-ntunvlyu/msgraph-sdk_9fcb04736acc4f958f7370cb0cb07107
  Resolved https://github.com/microsoftgraph/msgraph-sdk-python.git to commit 3d35d3207f036e2f53ec2f62f96d2f7b8367a5f8
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  WARNING: Generating metadata for package msgraph-sdk produced metadata for project name unknown. Fix your #egg=msgraph-sdk fragments.
Discarding git+https://github.com/microsoftgraph/msgraph-sdk-python.git: Requested unknown from git+https://github.com/microsoftgraph/msgraph-sdk-python.git has inconsistent name: filename has 'msgraph-sdk', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement msgraph-sdk (unavailable) (from versions: 1.0.0a0, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a7, 1.0.0a8, 1.0.0a9)
ERROR: No matching distribution found for msgraph-sdk (unavailable)
```

**Edit**: `pip install --upgrade pip` did the trick 🥳

**Comment by samwelkanda** [comment]
Hi @iargue 

Thank you for creating this issue. Indeed the error was caused by recent unpublished changes to support multi-value headers. The SDK and all dependencies on PyPI have been updated accordingly.

Please update to the latest version to get these changes and many more.

Best Regards
