### ISSUE TITLE
is this the recommended way to interact with azure AD groups/users using Python at the moment?

### ISSUE THREAD

**Issue by gilmoregrills** [microsoftgraph/msgraph-sdk-python#142]
I was previously trying to use the azure-graphrbac library, but it seems like that's been deprecated and I can no longer assign the right kind of admin permissions to my service client to use it. This library however seems to be in preview and using the examples here & what little documentation I can find it's been hard to actually accomplish anything.

Is there something I'm missing? Or should I just try a different language/approach?

Thanks!

**Comment by DrKabum** [comment]
I can relate to what you're saying, it took me an incredible amount of time to do just basic stuff. And this might be all for nothing after they implement breaking changes too, but I couldn't find any other good lib for Python.

**Comment by gilmoregrills** [comment]
for future ref we ended up just working with the ms graph api directly, using python/requests, and it was actually super easy to interact with - I'd probably recommend that approach for now for anyone else trying to use this sdk in the present 😅
