### ISSUE TITLE
Incorrect url for items_by_id

### ISSUE THREAD

**Issue by iargue** [microsoftgraph/msgraph-sdk-python#163]
Using msgraph-sdk-1.0.0a11

When using drives_by_id and then using items_by_id, the URL template is invalid.

`query = self.user_client.drives_by_id(id=drive.id).items_by_id(id=item.id)`
`print(query.url_template)`

The URL template for the request is:

`{+baseurl}/drives/{drive%2Did}/special/{driveItem%2Did}{?%24select,%24expand}`

The path should be /drive/{drive-id}/items/{item-id}. /special/ is for special folders and  should not be used by items_by_id

Trying to execute the code provides

`Error: The special folder identifier isn't valid`

This is caused by the line here: https://github.com/microsoftgraph/msgraph-sdk-python/blob/3f83a221bc4986d9440f7d81e0612572e8829d4d/msgraph/generated/drives/item/special/item/drive_item_item_request_builder.py#L33

**Comment by iargue** [comment]
Correction, this is caused because the items_by_id function is importing the same request 4 times and the drive_item_item_request_builder from special.item is the last one to be imported.

https://github.com/microsoftgraph/msgraph-sdk-python/blob/3f83a221bc4986d9440f7d81e0612572e8829d4d/msgraph/generated/drives/item/drive_item_request_builder.py#L137-L140

**Comment by samwelkanda** [comment]
Hi @iargue 

Thank you for reporting the above issue. We have released a new [version](https://pypi.org/project/msgraph-sdk/1.0.0a12/) that addresses this issue among others. Indexers have been moved lower in the API which eliminates multiple imports of the same name as the paths will now be unique.

Also note that these changes mean the syntax for the above call has changed from 

`client.drives_by_id(drive.id).items_by_id(item.id).get()`

 to 

`client.drives.by_drive_id(drive.id).items.by_drive_item_id(item.id).get()`

Feel free to re-open if you have more questions.
