### ISSUE TITLE
Get User by Id

### ISSUE THREAD

**Issue by codygreen** [microsoftgraph/msgraph-sdk-python#166]
I'm following the [Build Python apps with Microsoft Graph and app-only authentication](https://learn.microsoft.com/en-us/graph/tutorials/python-app-only?tabs=aad) tutorial and I'm having difficulty figuring out how to return user information based on the user id with app-only authentication.

The examples in the README.md seem to leverage delegated authentication. 

Looking at the UsersRequestBuilderGetQueryParameters method I can add a filter to search for email address, but returning user information by ID requires the ID at the root of the request, not a filter - [docs](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http):
```/users/{id}```

Can anyone help me identify an example of how to set the UserRequestBuilder to include the user's id?

Thank you,

Cody

**Comment by codygreen** [comment]
Figured it out:

```python
async def get_user_by_id(self, user_id):
        query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
            select = ['id', 'givenName', 'surname', 'userPrincipalName', 'mail']
        )

        request_config = UsersRequestBuilder.UsersRequestBuilderGetRequestConfiguration(
            query_parameters=query_params
        )

        try:
            user = await self.app_client.users_by_id(user_id).get(request_configuration=request_config)
            if user is not None:
                payload = {
                    "id": user.__dict__['_id'],
                    "given_name": user.__dict__['_given_name'],
                    "mail": user.__dict__['_mail'],
                    "surname": user.__dict__['_surname'],
                    "user_principal_name": user.__dict__['_user_principal_name']
                }
            return payload
        except Exception as e:
            print(e.error.message)
            return None
```

**Comment by samwelkanda** [comment]
Hey @codygreen 

Thanks for using the our SDK!

While the above works, you can simplify your code as the call to get a user will return a `User` object with all properties populated. You can access these properties using dot notation as opposed to having to use the `__dict__` attribute.

```py
async def get_user_by_id(user_id):
        try:
            user = await client.users.by_user_id(user_id).get()
            if user is not None:
                payload = {
                    "id": user.id,
                    "given_name": user.given_name,
                    "mail": user.mail,
                    "surname": user.surname,
                    "user_principal_name": user.user_principal_name
                }
                print(payload)
        except Exception as e:
            print(e.error.message)
            return None
``

**Comment by samwelkanda** [comment]
Closing this for now, feel free to re-open if you have further questions.
