### ISSUE TITLE
filterByCurrentUser never works

### ISSUE THREAD

**Issue by rfc6919** [microsoftgraph/msgraph-sdk-python#172]
I'm trying to retrieve the list of access packages a user is allowed to request. The correct request URL is `/identityGovernance/entitlementManagement/accessPackages/filterByCurrentUser(on='allowedRequestor')` which I'm calling through the SDK with `access_packages = await client.identity_governance.entitlement_management.access_packages.filter_by_current_user_with_on('allowedRequestor').get()` but the actual URL generated and submitted is `/identityGovernance/entitlementManagement/accessPackages/filterByCurrentUser(on='')` which unsurprisingly returns an error.

The file `msgraph/generated/identity_governance/entitlement_management/access_packages/filter_by_current_user_with_on/filter_by_current_user_with_on_request_builder.py` contains the line

`url_tpl_params[""] = on`

and as a result the `filterByCurrentUser(on='{on}')` part of the URL template is not correctly filled in when the request is prepared. Changing this to

`url_tpl_params["on"] = on`

allows the request to succeed and return the expected list of access packages.

Grepping through the library it looks like every instance of `filter_by_current_user_with_on_request_builder.py` has this error.

**Comment by rfc6919** [comment]
practical workaround right now is unpleasant, but at least I don't have to patch the SDK...

```    request_builder = client.identity_governance.entitlement_management.access_packages.filter_by_current_user_with_on('allowedRequestor')
    request_builder = client.identity_governance.entitlement_management.access_packages.filter_by_current_user_with_on('allowedRequestor')
    # XXX work around https://github.com/microsoftgraph/msgraph-sdk-python/issues/172
    # XXX once that's fixed, we no longer need to force the correct parameter into the request template here
    request_builder.path_parameters["on"] = 'allowedRequestor'
    # XXX end workaround
    access_packages = await request_builder.get()

**Comment by shemogumbe** [comment]
Hello @rfc6919 Thanks for using the SDK and for raising this.

Is this still an issue on the latest SDK version?

Running:
```python
async def get_access_package_by_current_user():

    try:
        access_packages = await user_client.identity_governance.entitlement_management.access_packages.filter_by_current_user_with_on(
            'allowedRequestor').get()
        print(f"Access Packages: {access_packages.value}")
    except APIError as api_error:
        print(f"api error {api_error}")


asyncio.run(get_access_package_by_current_user())
```
Gives me:
```
Access Packages: []
```
Whic implies request went through, just that the data is empty

**Comment by rfc6919** [comment]
Sorry, I have no idea. I gave up on the SDK a year ago and we now use a homegrown msgraph wrapper.
