### ISSUE TITLE
We should align with other languages and make initialization easier

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-sdk-python#180]
As discussed, we'd like to abstract these 3 lines of code:
```py
auth_provider = AzureIdentityAuthenticationProvider(credential, scopes=scopes)

# Initialize a request adapter. Handles the HTTP concerns
request_adapter = GraphRequestAdapter(auth_provider)

# Get a service client
client = GraphServiceClient(request_adapter)
```

And only request from the developer to specify the context, the scope and its required values.

**Comment by isvargasmsft** [comment]
CC: @samwelkanda @shemogumbe @baywet

**Comment by baywet** [comment]
if possible an overload constructor defined in a derived class is probably the best option here. The generated client would become the BaseGraphClient and this manually crafted class that derives from it would become GraphServiceClient, and accept credential and scopes directly.
That overload constructor should not mask the default one with the request adapter as people in need of more advanced configuration should still be able to pass a request adapter.
