### ISSUE TITLE
error in example from readme: The provided value for scope `User.Read` is not valid. Client credential flows must have a scope value with `/.default`

### ISSUE THREAD

**Issue by copdips** [microsoftgraph/msgraph-sdk-python#181]
Hello,

Running the [example ](https://github.com/microsoftgraph/msgraph-sdk-python#3-make-requests-against-the-service)given in the readme throw following error:

> azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS1002012: The provided value for scope User.Read is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).

I'm using `from azure.identity import ClientSecretCredential` to generate the crendential object, and use the scope given by the example `scopes = ['User.Read']`, the error message is clear for me, Azure AD only accepts `/.default` scope for `ClientSecretCredential` auth flow. I would like to know how to specify specific scope instead of `/.default`

**Comment by samwelkanda** [comment]
Hi @copdips , thanks for reporting this issue. 

Indeed the sample code provided is incorrect. Specific scopes are only available for [delegated access](https://learn.microsoft.com/en-us/graph/auth-v2-user)(as a user) and not for application access. To be able to use specific scopes, please use one of the [credential classes for authenticating users](https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#authenticate-users)

You can also check out our [auth samples](https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/samples/authentication_samples.md#delegated-access-samples-requires-signed-in-user) for more concrete examples.
