### ISSUE TITLE
Unable to run Advanced Hunting Query

### ISSUE THREAD

**Issue by iargue** [microsoftgraph/msgraph-sdk-python#183]
I am using version 1.0.0a12

I am trying to utilize the API to run an advanced hunting query and run into two issues.

1. The SecurityRunHuntingQueryRequestBuilder uses an invalid URL for running a hunting query
https://github.com/microsoftgraph/msgraph-sdk-python/blob/247e3230ca57b1d5e2dfbb593c00a9a38474f544/msgraph/generated/security/security_run_hunting_query/security_run_hunting_query_request_builder.py#L33

This should be /security/runHuntingQuery per the API documentation

2. SecurityRunHuntingQueryRequestBuilder.post lists an optional field that is not optional.
https://github.com/microsoftgraph/msgraph-sdk-python/blob/247e3230ca57b1d5e2dfbb593c00a9a38474f544/msgraph/generated/security/security_run_hunting_query/security_run_hunting_query_request_builder.py#L39

However, within the post function, the body is not optional. and shouldn't be marked as optional

https://github.com/microsoftgraph/msgraph-sdk-python/blob/247e3230ca57b1d5e2dfbb593c00a9a38474f544/msgraph/generated/security/security_run_hunting_query/security_run_hunting_query_request_builder.py#L47-L48

In addition, the optional type RunHuntingQueryPostRequestBody does not allow for any parameters to be set.

https://github.com/microsoftgraph/msgraph-sdk-python/blob/247e3230ca57b1d5e2dfbb593c00a9a38474f544/msgraph/generated/security/security_run_hunting_query/run_hunting_query_post_request_body.py#L6

I have absolutely no idea how I'm supposed to pass the query field to run an advanced hunting query. This doesn't seem to be functional in any way.

**Comment by andrueastman** [comment]
@iargue Any chance you can confirm if this is still an issue in the latest version of the SDK?
