### ISSUE TITLE
msgraph-sdk 1.0.0a12 failed to install to Azure Automation Account

### ISSUE THREAD

**Issue by stvpwrs** [microsoftgraph/msgraph-sdk-python#185]
Hello,

When trying to install msgraph-sdk 1.0.0a12 to an Azure Automation Account I get the following install error:

```
Error
Orchestrator.Activities.PythonPackageExtractException: Error while extractinig Python package: pip install failed for python package msgraph-sdk. at Orchestrator.Activities.SetModuleActivity.ExecuteInternal(CodeActivityContext context, Byte[] moduleContent, String moduleName, ModuleLanguage moduleLanguage, Guid moduleVersionId, String modulePath) at Orchestrator.Activities.SetModuleActivity.Execute(CodeActivityContext context) at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)
```

This is the only Microsoft package that I've been unable to install to an Azure Automation Account.

**Comment by bibonut** [comment]
+1 with msgraph-sdk 1.0.0 on runtime ver 3.8

**Comment by shemogumbe** [comment]
Hello @stvpwrs thanks for using the SDK and for raising this.

Are you installing with pip, what is the setup of your runbook, it's a bit difficult to create an environment that maps to your azure automation account environment to reproduce this, mind sharing the setup.

Are you using a virtual environment in the setup? Any logs from your runbook?  The target installation environment?
