### ISSUE TITLE
Unable to install packages due to an OSError

### ISSUE THREAD

**Issue by ysio774** [microsoftgraph/msgraph-sdk-python#188]
Using microsoftgraph, I am planning about excel input/output of data frame. Coding uses jupyterLab.

As a start, I did the following:

`!pip install msgraph-sdk`

Then, the following message appears, in short "ERROR: Could not install packages due to an OSError" has occurred

`Collecting msgraph-sdk
  Using cached msgraph_sdk-1.0.0a12-py3-none-any.whl (19.8 MB)
Requirement already satisfied: azure-identity>=1.12.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-sdk) (1.12.0)
Requirement already satisfied: microsoft-kiota-abstractions>=0.5.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-sdk) (0.5.0)
Requirement already satisfied: microsoft-kiota-authentication-azure>=0.2.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-sdk) (0.2.0)
Requirement already satisfied: microsoft-kiota-serialization-json>=0.3.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-sdk) (0.3.2)
Requirement already satisfied: microsoft-kiota-serialization-text>=0.2.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-sdk) (0.2.0)
Requirement already satisfied: msgraph-core>=1.0.0a2 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-sdk) (1.0.0a4)
Requirement already satisfied: azure-core<2.0.0,>=1.11.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from azure-identity>=1.12.0->msgraph-sdk) (1.26.4)
Requirement already satisfied: cryptography>=2.5 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from azure-identity>=1.12.0->msgraph-sdk) (38.0.1)
Requirement already satisfied: msal<2.0.0,>=1.12.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from azure-identity>=1.12.0->msgraph-sdk) (1.22.0)
Requirement already satisfied: msal-extensions<2.0.0,>=0.3.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from azure-identity>=1.12.0->msgraph-sdk) (1.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from azure-identity>=1.12.0->msgraph-sdk) (1.16.0)
Requirement already satisfied: uritemplate>=4.1.1 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from microsoft-kiota-abstractions>=0.5.0->msgraph-sdk) (4.1.1)
Requirement already satisfied: aiohttp>=3.8.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (3.8.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from microsoft-kiota-serialization-json>=0.3.0->msgraph-sdk) (2.8.2)
Requirement already satisfied: microsoft-kiota-http>=0.1.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-core>=1.0.0a2->msgraph-sdk) (0.4.1)
Requirement already satisfied: httpx[http2]>=0.23.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msgraph-core>=1.0.0a2->msgraph-sdk) (0.24.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from aiohttp>=3.8.0->microsoft-kiota-authentication-azure>=0.2.0->msgraph-sdk) (1.3.1)
Requirement already satisfied: requests>=2.18.4 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from azure-core<2.0.0,>=1.11.0->azure-identity>=1.12.0->msgraph-sdk) (2.28.1)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from azure-core<2.0.0,>=1.11.0->azure-identity>=1.12.0->msgraph-sdk) (4.4.0)
Requirement already satisfied: cffi>=1.12 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from cryptography>=2.5->azure-identity>=1.12.0->msgraph-sdk) (1.15.1)
Requirement already satisfied: certifi in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (2022.12.7)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (0.17.0)
Requirement already satisfied: idna in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (3.4)
Requirement already satisfied: sniffio in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (1.2.0)
Requirement already satisfied: h2<5,>=3 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (4.1.0)
Requirement already satisfied: PyJWT[crypto]<3,>=1.0.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msal<2.0.0,>=1.12.0->azure-identity>=1.12.0->msgraph-sdk) (2.6.0)
Requirement already satisfied: portalocker<3,>=1.6 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from msal-extensions<2.0.0,>=0.3.0->azure-identity>=1.12.0->msgraph-sdk) (2.7.0)
Requirement already satisfied: pycparser in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from cffi>=1.12->cryptography>=2.5->azure-identity>=1.12.0->msgraph-sdk) (2.21)
Requirement already satisfied: hyperframe<7,>=6.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (4.0.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx[http2]>=0.23.0->msgraph-core>=1.0.0a2->msgraph-sdk) (3.5.0)
Requirement already satisfied: pywin32>=226 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from portalocker<3,>=1.6->msal-extensions<2.0.0,>=0.3.0->azure-identity>=1.12.0->msgraph-sdk) (305.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ysio7\anaconda3\envs\scrape\lib\site-packages (from requests>=2.18.4->azure-core<2.0.0,>=1.11.0->azure-identity>=1.12.0->msgraph-sdk) (1.26.13)
Installing collected packages: msgraph-sdk
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\ysio7\\anaconda3\\envs\\scrape\\Lib\\site-packages\\msgraph\\generated\\communications\\call_records\\call_records_get_direct_routing_calls_with_from_date_time_with_to_date_time\\call_records_get_direct_routing_calls_with_from_date_time_with_to_date_time_request_builder.py'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths` 

In response to the comment "This error might have occurred since this system does not have Windows Long Path support enabled.", I set "Enable Win32 Long Path" to "Enabled" using the Local Group Policy Editor.
Then again, I ran "!pip install msgraph-sdk" again, but it still didn't work and I still get the exact same error message.

Any advice would be highly appreciated.

**Comment by zachmdsi** [comment]
Ideally, you don't want to have to edit things in the Registry.

Try this first. Sometimes doing things in the Anaconda Prompt can avoid certain issues:

- Open Anaconda Prompt
- `cd project_directory`
- Active your environment using `conda activate scrape`
- `pip install msgraph-sdk`

If this doesn't work and you must enable support for long paths, there is a chance your local group policy editor did not apply to the entire system. Follow these steps with caution:

  - Press Windows key + R, type regedit, and press Enter.
  - In the Registry Editor, navigate to: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
  - In the right pane, look for a value named `LongPathsEnabled`. If it doesn’t exist, create it by right-clicking the right pane, select `New > DWORD (32-bit) Value`, and then name it `LongPathsEnabled`.
  - Double click on `LongPathsEnabled`, and set the Value data to 1.
  - Close the Registry Editor and restart your computer.

**Comment by isvargasmsft** [comment]
CC: @shemogumbe @samwelkanda

**Comment by isvargasmsft** [comment]
Thank you very much for this issue, @ysio774. 
Please enable longh paths in your environment:
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later

Today, the snake case nature of python file naming and nested resources in Microsoft Graph causes us to have long file names, and the only solution involves the user having to enable long file paths in their operating system. This 260 character limitation was actually dropped starting with some later versions of windows 10, and it is completely safe to enable.
