### ISSUE TITLE
How to retrieve Azure B2C Custom Attributes using the SDK?

### ISSUE THREAD

**Issue by matt-grain** [microsoftgraph/msgraph-sdk-python#191]
Hi, I have defined some custom user attributes in my Azure B2C User Flow and I try to retrieve them using the SDK but no luck so far.
I tried:

```python
	query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
		select=[
			"extension_MyCustomAttribute",
			"extension_{myclientIDwithout-}_MyCustomAttribute",
			"MyCustomAttribute",
			"displayName",
			"companyName",
		]
	)
	request_config = UsersRequestBuilder.UsersRequestBuilderGetRequestConfiguration(
		query_parameters=query_params
	)

	user = await self.client.users.by_user_id(str(user_id)).get(request_configuration=request_config)
	if user:
		print(dir(user))
		print(user.extensions)
		print(user.my_custom_attribute)
```

Any idea?

Thanks !

**Comment by samwelkanda** [comment]
Hey @matt-grain 

Thanks for using our SDK. 

What error are you getting exactly? If you are getting `None` values, I'd suggest you skip the select and fetch all properties of the user like so: 
`user = await self.client.users.by_user_id(str(user_id)).get()`

That way you can be able to see all the available properties of the user ubject using `dir()`.

**Comment by matt-grain** [comment]
Hi Samwel!

In fact this is exactly what I’ve done first but the custom attributes were not mapped as variables as the User object.
That’s why I tried using select (as it is written in the documentation, AAD/AB2C custom attributes are only retrieved using the $select option)

But not better, the custom variables in the query are not mapped:
“AttributeError: ‘User’ object has no attribute ‘…’”

Are custom attributes automatically mapped?

Thanks!
________________________________

**Comment by samwelkanda** [comment]
Hey @matt-grain 

The SDK will only deserialize the default attributes defined in the `User` object model. All other properties are thrown into an `additional_data` property bag, which I suspect is the case for you.

Try `print(user.additional_data)` and check if they are contained there.

**Comment by matt-grain** [comment]
Ah! `additiona_data` is the last attribute I did not try :D 

So when I print it I get:

`{'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users("extension_MyCustomAttribute,extension_{myclientIDwithout-}_MyCustomAttribute,MyCustomAttribute,displayName,companyName)/$entity'}`


but not the values

**Comment by samwelkanda** [comment]
Interesting. how about you get the native response like so:

```py
from kiota_abstractions.native_response_handler import NativeResponseHandler
from kiota_http.middleware.options import ResponseHandlerOption

request_config = UsersRequestBuilder.UsersRequestBuilderGetRequestConfiguration(
		options=[ResponseHandlerOption(NativeResponseHandler())], )
	)

	resp = await self.client.users.by_user_id(str(user_id)).get(request_configuration=request_config)
       print(resp.json())
```

Are the values contained in the json?

**Comment by matt-grain** [comment]
no... only the build-in attributes

`
{'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users/$entity', 'businessPhones': [], 'displayName': 'Juanma', 'givenName': 'Juanma', 'jobTitle': 'Dev', 'mail': None, 'mobilePhone': None, 'officeLocation': None, 'preferredLanguage': None, 'surname': 'matri', 'userPrincipalName': ...6f@....onmicrosoft.com', 'id': '...6f'}
`

**Comment by samwelkanda** [comment]
Did you include the query params in your call?

```py
query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
		select=[
			"extension_MyCustomAttribute",
			"extension_{myclientIDwithout-}_MyCustomAttribute",
			"MyCustomAttribute", 
			"displayName",
			"companyName",
		]
	)
request_config = UsersRequestBuilder.UsersRequestBuilderGetRequestConfiguration(
		options=[ResponseHandlerOption(NativeResponseHandler())], ),
                query_parameters=query_params
	)

	resp = await self.client.users.by_user_id(str(user_id)).get(request_configuration=request_config)
```

If you did, can you try fetching one extension property at a time?

```py
query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
		select=[
			"extension_{myclientIDwithout-}_MyCustomAttribute",
			"displayName",
			"companyName",
		]
	)
```

**Comment by matt-grain** [comment]
Yes I tried with the query.
But not one at a time and this is the result:

`
{'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users(extension_{myclientIDwithout-}_MyCustomAttribute,displayName,companyName)/$entity', 'displayName': 'mighty matt', 'companyName': 'company'}
`

**Comment by matt-grain** [comment]
if the format `extension_{myclientIDwithout-}_MyCustomAttribute` the good one in the select ?

**Comment by samwelkanda** [comment]
Yes, it should work if it's the correct name. 

Since you have the app id, you can verify that it's the right one by calling `await self.client.applications.by_application_id('app_id').extension_properties.get()` and checking if it's in the list

**Comment by matt-grain** [comment]
What is the graph permission to add to use this API?
I got:  Insufficient privileges to complete the operation

![image](https://user-images.githubusercontent.com/111311078/236352823-4cd9814e-17cc-4a6a-ab7b-c1677cd25df7.png)

**Comment by samwelkanda** [comment]
Try granting `Directory.Read.All`

**Comment by matt-grain** [comment]
ok it took some time to be applied it seems.
Now my error while checking the application ID is 

`
Resource 'xxxxxxx-xxxx-xxxx-xxxx-09cdd23e7e0b' does not exist or one of its queried reference-property objects are not present
`

But this is really the Application ID:

![image](https://user-images.githubusercontent.com/111311078/236353680-eed5910e-e89b-428f-ab5d-0172c9baebcd.png)

should I remove the - from the app-id? (I tried... not better)

**Comment by samwelkanda** [comment]
Are you using the id for the `extensions-app`? You can query all the listed applications using `self.client.applications.get()` and look for the app name ending with `extensions-app. Do not modify.`. That's the app id you should use.

**Comment by matt-grain** [comment]
So I added:
```python
            apps = await self.client.applications.get()
            for app in apps.value:
                print(app.app_id)
```

and I got:
`
xxx
xxx
xxx
xxxxxxxf-09cdd23e7e0b
xxx
`

soi the app-id is ok but the get by_application_id is not :)

**Comment by matt-grain** [comment]
ah,,,, ok the one with the **`b2c-extensions-app. Do not modify. Used by AADB2C for storing user data.** is another one...

**Comment by samwelkanda** [comment]
Great, so now we can retry the previous calls with the correct app-id.

**Comment by matt-grain** [comment]
ok but does it mean I need to modify the application "b2c-extensions-app. Do not modify. Used by AADB2C for storing user data":
- adding a secret for the auth
- adding permissions?

I thought do not modify was not a joke :D

**Comment by samwelkanda** [comment]
You don't need to modify the app. 

You just need it's app id that you can then use to get the list of extension properties `client.applications.by_application_id('app_id').extension_properties.get()` and also it's the app_id you'll use in `extension_{myAppIDwithout-}_MyCustomAttribute` when fetching the custom attributes.

**Comment by matt-grain** [comment]
ahah! Works now!!! additional_data is well filled!
Thanks a lot for the debugging session!

**Comment by ghost** [comment]
Hey guys :)
regarding issue #262, i'm find correlation between my issue and this one, but the fact is when it try to add 
`request_configuration=request_config` in this request:
```python3
request_config = (
                UsersRequestBuilder.UsersRequestBuilderGetRequestConfiguration(
                    headers={"Content-type": "application/json"},
                    options=[ResponseHandlerOption(NativeResponseHandler())],
                ),
            )
            
resp = await self.client.users.by_user_id(str(email)).get(
                request_configuration=request_config
            )
```

I get this error: `error is:  'tuple' object has no attribute 'headers'`

if i do the request without `request_configuration=request_config`
i get only `User(additional_data={'@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users/$entity'})`

without any data in.

If you have any idea :)

Have a good day

EDIT: problem solve, black python formatter add brackets on `request_config = (
                UsersRequestBuilder.UsersRequestBuilderGetRequestConfiguration(
                    headers={"Content-type": "application/json"},
                    options=[ResponseHandlerOption(NativeResponseHandler())],
                ),
            )`

**Comment by EFG-TheDevopsGuy** [comment]
Can you guys provide an example of patch request please ?
Thanks
