### ISSUE TITLE
Deserialization Bug for Calendar class

### ISSUE THREAD

**Issue by djuelg** [microsoftgraph/msgraph-sdk-python#206]
Hi, I probably found a deserialization bug for the calendar class.

Using version `msgraph-sdk = "^1.0.0a12"` of the library, when calling `self.client.me.calendars.get()` I'm getting the following error:

```
Invalid key: ['skypeForConsumer'] for enum <enum 'OnlineMeetingProviderType'>
```

I suppose the key should be only 'skypeForConsumer' without the parentheses and the bug resides somewhere around `calendar_collection_response.py:39` and `calendar.py:245`

If it helps this is the json I got from the Graph API:
```
{
    "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users(\'h***%40****.de\')/calendars",
    "value": [
        {
            "id": "AQMkADAwATYwMAItYRgAAA0TN3Bzm...8qOTpUInNFkOagTVroAAAAEVko4AAAA",
            "name": "Kalender",
            "color": "auto",
            "hexColor": "",
            "isDefaultCalendar": true,
            "changeKey": "Lyo5OlQic0WQ...VNWugAABFajHw==",
            "canShare": true,
            "canViewPrivateItems": true,
            "canEdit": true,
            "allowedOnlineMeetingProviders": [
                "skypeForConsumer"
            ],
            "defaultOnlineMeetingProvider": "skypeForConsumer",
            "isTallyingResponses": true,
            "isRemovable": false,
            "owner": {
                "name": "********",
                "address": "h*****@*****.de"
            }
        }
    ]
}
```

**Comment by samwelkanda** [comment]
Hi @djuelg 

Thanks for reporting this issue. The bug has been fixed, please update the serialization library with `pip install microsoft-kiota-serialization-json==0.3.4` to get the fix. Thanks.

**Comment by samwelkanda** [comment]
Closing for now. Feel free to re-open if your issue persists.
