### ISSUE TITLE
Add tab to a channel

### ISSUE THREAD

**Issue by mprnci** [microsoftgraph/msgraph-sdk-python#212]
Hello,

First of all thank you so much for the issue with deleting a teams channel, everything works fine now!

I am currently trying to add a tab to a teams channel.
At the begining, I was simply doing:

```
        async def create_tab_async():
            try:
                myTab = TeamsTab()
                await client.teams.by_team_id(team_id).channels.by_channel_id(chanId).tabs.post(body=myTab)
            except Exception as e:
                print(e)

        asyncio.run(create_tab_async())
```

But this was giving the following error:

`Error: The navigation bind for the teamsApp was missing in request.`

So I thought of setting the teams_app of myTab (which I don't really know how to do but tried) by adding the following lines:

```
myTab .teams_app = TeamsApp()
myTab .teams_app.odata_type = "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.wiki"
```

But this gives the following error:

`Error: Invalid OData type specified: "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.wiki".`

How to properly add a tab of Wiki type to a Teams channel?

Thank you very much!

**Comment by samwelkanda** [comment]
Hi @mprnci 

You can set the navigation bind in the additional data dict of the tab you are creating like so:

```py
tb = TeamsTab()
tb.display_name = "My Wiki"
tb.additional_data = {"teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.wiki"}

await client.teams.by_team_id(team_id).channels.by_channel_id(chanId).tabs.post(body=tb)
```

**Comment by samwelkanda** [comment]
We understand some of these features might not be obvious to users at the moment. We are working to generate snippets that cover most of the endpoints/operations.

**Comment by mprnci** [comment]
Thank you so much, it works like a charm!

Perfect that would me awesome 🤩
