### ISSUE TITLE
Deleting an application (app registration) throws RuntimeError

### ISSUE THREAD

**Issue by dmartin-r7** [microsoftgraph/msgraph-sdk-python#216]
I have the following rudimentary code where I create an application, and then delete it if it creates successfully:

```
async def create_application():
    try:
        app = Application()

        app._display_name = "test_delete"

        result = await client.applications.post(body=app)
        return result

    except Exception as e:
        print(e)

async def delete_application(app_id):
    try:
        result = await client.applications.by_application_id(application_id=app_id).delete()
        return result

    except Exception as e:
        raise e

created_application = asyncio.run(create_application())

app_id = created_application.id
if app_id is not None:
    asyncio.run(delete_application(app_id))
```

When i run this it will create and delete but it throws `RuntimeError: Event loop was closed` on the deletion how can I avoid this?

**Comment by samwelkanda** [comment]
Hi @dmartin-r7 

The event loop is closed after the call to `create_application`. To avoid this you can use a wrapper function `main()` where you can execute requests within the event loop before closing.

```py
async def create_application():
    try:
        app = Application()

        app._display_name = "test_delete"

        result = await client.applications.post(body=app)
        return result

    except Exception as e:
        print(e)

async def delete_application(app_id):
    try:
        result = await client.applications.by_application_id(application_id=app_id).delete()
        return result

    except Exception as e:
        raise e

async def main():
    created_application = await create_application()
    app_id = created_application.id
    if app_id is not None:
        await delete_application(app_id)

asyncio.run(main())
```

**Comment by derekpurdy** [comment]
Sorry to drop in on this issue, but i am having an issue just creating an application and I cannot find a working example, but came across this recent issue. @dmartin-r7 if possible would you be able to provide your Application class?

**Comment by samwelkanda** [comment]
@derekpurdy , all graph models are autogenerated and can be found [here](https://github.com/microsoftgraph/msgraph-sdk-python/tree/main/msgraph/generated/models)

To import the application model you need to import 

`from msgraph.generated.models.application import Application`
