### ISSUE TITLE
Get code snippet inside a message

### ISSUE THREAD

**Issue by lucaslascano** [microsoftgraph/msgraph-sdk-python#223]
Hi. I'm trying to download all the messages inside a team's channel with the Python msgraph sdk API. I can get the body of the messages but, when I try to get the code snippets that are attached to the message, I only get a codeSnippetURL but not the actual content of the code snippet.

Here is how I'm accessing the attachments inside a message:

```python
messages = await self.app_client.teams.by_team_id("abc").channels.by_channel_id("123").messages.get()
for message in messages.value:
    for attachment in message.attachments:
        print(attachment.content)
```

What I get is something like this:
```python
'{"name":"","language":"Python","lines":59,"wrap":false,"codeSnippetUrl":"https://graph.microsoft.com/v1.0/teams/abc/channels/123/messages/xyz/hostedContents/aWQ9MC1ldXPdIUItZjc4ODVlMzFkMjY1N2M0YTk1ZTMzYzVmMTllNjhmZTIsdHlwZT0wLHVybD0=/$value"}'
```

How can I access the text inside the code snippet?

I can make a request to the codeSnippetUrl, but I was wondering if there is a built-in way to do it with the API.

Thanks in advance

**Comment by fey101** [comment]
Hi @lucaslascano , am not sure what you mean by using the API but if you meant the sdk then I think you should be able to query the path specified by the codeSnippetUrl with the snippet below as the path is available on the sdk [here](https://github.com/microsoftgraph/msgraph-sdk-python/tree/main/msgraph/generated/teams/item/channels/item/messages/item/hosted_contents/item/value):

```Python
code_snippet = self.app_client.teams.by_team_id("abc").channels.by_channel_id("123").messages.by_message_id("xyx").hostedContents.by_chat_message_hosted_content_id("aWQ9MC1ldXPdIUItZjc4ODVlMzFkMjY1N2M0YTk1ZTMzYzVmMTllNjhmZTIsdHlwZT0wLHVybD0=").value
```

Let us know how we can help further.
