### ISSUE TITLE
Attempting to create a AD Applicaiton with owners

### ISSUE THREAD

**Issue by derekpurdy** [microsoftgraph/msgraph-sdk-python#227]
Hello, I'm having difficulty in creating a AD Application with Owners assocaited with it. I am getting "msgraph.generated.models.o_data_errors.o_data_error.ODataError"

```
async def create_ad_application(requested_application_name, owner_list=None, application_id=None):
    try:
        app = Application()
        app._display_name = requested_application_name
        app._owners = owner_list
        app_result = await graph_client.applications.post(body=app)
        return app_result
    except Exception as e:
        print(e)
```

I tried both setting owner_list as a list of object IDs in python, and also creating a list of ad_objects within python using the following function below.

```
async def collect_ad_object_info(owner_list):
    post_config = GetByIdsPostRequestBody()
    post_config.ids = owner_list
    post_config.types=["user"]
    user_ad_lookup = await graph_client.directory_objects.get_by_ids.post(body=post_config)
    return user_ad_lookup.value
```

Any help would be appreciated, also I noticed grabbing an existing Application (using graph_client.applications.get) with owners visible in the Portal, the "owners" field is "None" in the result from the get call.

Thanks

Derek

**Comment by derekpurdy** [comment]
So it appears I was possibly doing that incorrectly, on the other hand it looks like some new documentation has been posted regarding this.

https://learn.microsoft.com/en-us/graph/tutorial-applications-basics?tabs=python#assign-an-owner-to-an-app

Unforunately I can't seem to get it to work either.

code from the microsoft site below.
```
// THE PYTHON SDK IS IN PREVIEW. NON-PRODUCTION USE ONLY
client =  GraphServiceClient(request_adapter)

request_body = ReferenceCreate()
request_body.@odata_id = 'https://graph.microsoft.com/v1.0/directoryObjects/8afc02cb-4d62-4dba-b536-9f6d73e9be26'

await client.applications.by_application_id('application-id').owners.ref.post(request_body = request_body)
```

I've tried request_body.@odata_id, request_body._odata_id and request_body.odata_id and none appear to be valid.

request_body.@odata_id gives an invalid syntax error.
```
request_body.@odata_id = 'https://graph.microsoft.com/v1.0/directoryObjects/' + application_owner_oid
                 ^
SyntaxError: invalid syntax
```

request_body.odata_id and request_body._odata_id give a msgraph.generated.models.o_data_errors.o_data_error.ODataError

**Comment by derekpurdy** [comment]
I appear to have got it working.

```
from msgraph.generated.models.application import Application
from msgraph.generated.models.service_principal import ServicePrincipal
from msgraph.generated.models.reference_create import ReferenceCreate
```

```
async def create_application(application_name):
    try:
        request_body = Application()
        request_body.display_name = application_name
        result = await graph_client.applications.post(body=request_body)
        return result
    except Exception as e:
        print(f'Error: {e.error.message}')
```

* Would be nice to handle an existing owner better then just passing the exception, but I cannot figure that bit out just yet (Any feedback appreciated)
```
async def update_application_owner(application_id, owner_id):
    try:
        request_body = ReferenceCreate()
        request_body.odata_id = 'https://graph.microsoft.com/v1.0/directoryObjects/' + owner_id
        result = await graph_client.applications.by_application_id(application_id).owners.ref.post(body=request_body)
        return result
    except Exception as e:
        pass
```


if anyone needs the service principal bit as well...

```
async def create_service_principal(application_id, application_name):
    try:
        request_body = ServicePrincipal()
        request_body.app_id = application_id
        request_body.display_name = application_name
        result = await graph_client.service_principals.post(body=request_body)
        return result
    except Exception as e:
        print(f'Error: {e.error.message}')
```

**Comment by shemogumbe** [comment]
@derekpurdy  Is this still an issue using the updated documentation and the GA version of the SDK?

**Comment by derekpurdy** [comment]
@shemogumbe sorry, I can no longer comment on the issue above, as I am no longer with the company working on this project. Thanks for your assistance.
