### ISSUE TITLE
No support for deltaToken and skipToken

### ISSUE THREAD

**Issue by Nemeczek** [microsoftgraph/msgraph-sdk-python#242]
Hey,

I have hard time understanding if this SDK is capable of making calls using Delta endpoints. 
While I can use this endpoint to make initial request to the API:
`await client.groups.delta.get()`

I can't see how can I make subsequent calls to Delta endpoint. There is no option to attach deltaToken. The same goes for skipToken which is crucial because the initial delta call is almost always paged. 

I can't even inject this query parameters by myself because the API expects only known query parameters:
``` python
   @dataclass
    class DeltaRequestBuilderGetQueryParameters():
        """
        Invoke function delta
        """
        def get_query_parameter(self,original_name: Optional[str] = None) -> str:
            """
            Maps the query parameters names to their encoded names for the URI template parsing.
            Args:
                originalName: The original query parameter name in the class.
            Returns: str
            """
            if original_name is None:
                raise Exception("original_name cannot be undefined")
            if original_name == "count":
                return "%24count"
            if original_name == "filter":
                return "%24filter"
            if original_name == "orderby":
                return "%24orderby"
            if original_name == "search":
                return "%24search"
            if original_name == "select":
                return "%24select"
            if original_name == "skip":
                return "%24skip"
            if original_name == "top":
                return "%24top"
            return original_name
```

To make matters even more confusing[ this kind of documentation](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/includes/snippets/python/delta-query-users-nextlink-request2-python-snippets.md) is signaling something that is not yet supported by this SDK. 

So is it possible to make calls, that include deltaToken or skipToken, using this SDK? Or will it be added in future. Because beyond that this SDK is looking amazing.

**Comment by peter-redkite** [comment]
Thanks for adding this issue. I had the same, was using the applications/service principals which utilize skipToken.
Also found the documentation unclear, which meant realizing that this wasn't supported at all to be confusing. 

Agree that otherwise this is a good module. Not usable by me without this being solved.

**Comment by ghassett** [comment]
Hello, I am still seeing this same issue in `msgraph-sdk==1.0.0` today.

I don't see how delta requests can be used (at all) until this is fixed.

The [documentation](https://learn.microsoft.com/en-us/graph/delta-query-users?tabs=python) states that we should add a `skiptoken` to the `DeltaRequestBuilder.DeltaRequestBuilderGetQueryParameters` that we instantiate, but this parameter is not permitted in the `dataclass`

### Documentation for SDK Preview
```
graph_client = GraphServiceClient(credentials, scopes)

query_params = DeltaRequestBuilder.DeltaRequestBuilderGetQueryParameters(
		skiptoken = "oEBwdSP6uehIAxQOWq_3Ksh_TLol6KIm3stvdc6hGhZRi1hQ7Spe__dpvm3U4zReE4CYXC2zOtaKdi7KHlUtC2CbRiBIUwOxPKLa",
)
...
```
### Error thrown:
```
TypeError: __init__() got an unexpected keyword argument 'skiptoken'
```

**Comment by HWFord16** [comment]
Adding to this issue as we ran into this yesterday trying to use `deltatoken` keyword within ` DeltaRequestBuilder.DeltaRequestBuilderGetQueryParameters()` as shown in the example documentation [here.](https://learn.microsoft.com/en-us/graph/delta-query-events?tabs=http)

![Screenshot 2024-03-12 at 5 45 34 PM](https://github.com/microsoftgraph/msgraph-sdk-python/assets/73403234/70328b93-c0a2-4617-932d-6b1feb5b54af)

**Comment by Christiaan-Mathu** [comment]
Hi @baywet, this is quite similar problem that was resolved in #364 can we get an ETA on this and if there is workaround that we can use in the meanwhile 🙏

**Comment by baywet** [comment]
Hi everyone,
Apologies for the loooong delay in triage here. I'm not directly assigned to Python.
delta links (with delta tokens) and paging links (with skip tokens, returned through delta and collection endpoints) MUST be treated as opaque and MUST NOT be parsed but considered entirely.

This is why our generation process DOES NOT emit query parameters for deltaToken and skipToken, so consumers are not tempted to parse the link and store only the token, but instead use the entire URI.

To use those links, use the with url method instead, like so (excuse my python)

```python
page1 = client.groups.delta.get()

page2 = client.groups.delta.with_url(page1.odata_next_link).get()
```

We have an issue to [implement automatic pagination with the next links for you so you don't have to implement the iteration](https://github.com/microsoftgraph/msgraph-sdk-python-core/issues/126) please upvote it if you feel like it'd be beneficial to you.

**Comment by Christiaan-Mathu** [comment]
> Hi everyone, Apologies for the loooong delay in triage here. I'm not directly assigned to Python. delta links (with delta tokens) and paging links (with skip tokens, returned through delta and collection endpoints) MUST be treated as opaque and MUST NOT be parsed but considered entirely.
> 
> This is why our generation process DOES NOT emit query parameters for deltaToken and skipToken, so consumers are not tempted to parse the link and store only the token, but instead use the entire URI.
> 
> To use those links, use the with url method instead, like so (excuse my python)
> 
> ```python
> page1 = client.groups.delta.get()
> 
> page2 = client.groups.delta.with_url(page1.odata_next_link).get()
> ```
> 
> We have an issue to [implement automatic pagination with the next links for you so you don't have to implement the iteration](https://github.com/microsoftgraph/msgraph-sdk-python-core/issues/126) please upvote it if you feel like it'd be beneficial to you.

Thank you @baywet 👏
