### ISSUE TITLE
Include imports for Models and request configuration classes for snippets that Require models/Request Configuration Classes

### ISSUE THREAD

**Issue by shemogumbe** [microsoftgraph/msgraph-sdk-python#271]
- [ ] For snippets that make use of  models, include towards beginning of the snippet file, the import to the model class
- [ ] For models that require Request configuration classes, Include an import to the request configuration class to solve error `Unknown class when executing the snippet.
- [ ] Change Raptor import mechanism to rely on imports in the snippets, this way there is no need for the Raptor work around.

**Comment by andrueastman** [comment]
Raptor work is tracked via https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/2986

Imports work already completed.
