### ISSUE TITLE
Include  client initialization in every snippet

### ISSUE THREAD

**Issue by shemogumbe** [microsoftgraph/msgraph-sdk-python#272]
In a bid to create a more copy and paste scenario for clients, Include graph clint initialization code.

We initially did not include this to save space, however, client initialization code has been optimized to be just one to three lines of code. Include these in  each snippet file to make snippets copy and paste

**Comment by andrueastman** [comment]
Closing this one for now as it does not align with the snippets specification. 
Tracking via https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1937
