### ISSUE TITLE
Update chatMessage with application permissions not working

### ISSUE THREAD

**Issue by johnavalos274** [microsoftgraph/msgraph-sdk-python#273]
I am using API version 1.0 with msgraph-sdk-python

I am trying to update the Violation Policy of a Teams chat message in chats with application permissions and I keep getting a 412 error code.

the code I am using is straight out of the Microsoft learn site: https://learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&tabs=python

The following code is the code "as is" from the above site with an exception for the last line which I had to change since I am querying a message from CHATS and not from a CHANNEL. 

![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/82e1d63f-30bc-4a18-81dd-986626e88a03)

When running this code "as is" I get an error the following error:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/a5220b46-bd19-424d-ba59-46b19095af3e)

After fixing the code as shown below I get another error:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/b7e0d416-3688-4bc7-8c34-0dd28297ec45)
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/b3259336-f016-4447-b040-0a5bd613920e)

I edit the code to then assign "(['Credit Card Number', ])" to "policy_violationpolicy_tip.matched_condition_descriptions" as shown below:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/b5459c7e-8d6e-481d-aa8f-399f688eb919)

I have to repeat the above process for fields "verdictdetails" and "dlpaction" or else I get the same two errors("object has no attribute" and "none type object is not callable). The finalized code with all the edits is shown below:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/5e5a0eca-3f41-488e-97f6-0f8715bb8474)

When running the code directly above is when I get the 412 error code as shown below:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/35aa6366-d0d2-4c0e-8ee5-f7915007efea)

Below are all the imports I have in this file:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/ce437739-ff20-4649-b68a-b378662f8e58)

The credentials I'm using for authorization work when I call getAllMessages from CHATS using the below code to do so:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/113067738/fb11e3f3-6b6f-40b3-9a58-aa53d7885aec)

I'm not sure why I continue to get an error code for the Update chatMessage function. 
I don't think it is a problem with authorization or bad credentials. 
I'm sure it has to do with the formatting of the values that I'm passing or the format of the fields themselves that I'm attempting to update.

**Comment by rkodev** [comment]
Hi @johnavalos274 , thanks for trying out the Graph Python SDK. Could you attempt to update the application policy using  [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and share the outcome
