### ISSUE TITLE
When uploading a DriveItem, an error occurs with the message: '[item] Read called with an open stream or textreader. Please close any open streams or text'readers before calling Read.'

### ISSUE THREAD

**Issue by hide212131** [microsoftgraph/msgraph-sdk-python#276]
I am trying to upload content to SharePoint.
I can handle authentication, obtain Drive information, and download content successfully.
However, I cannot upload content. I encountered the following error:

```python
client = GraphServiceClient(credentials=credential, scopes=scopes)
drive_req = client.drives.by_drive_id(DRIVE_ID)
...
request_body = DriveItem()
request_body.name = 'a.txt'
request_body.file = File()
request_body.content = b'abcde'
result = await drive_req.items.by_drive_item_id('root').children.post(body=request_body)
```

> msgraph.generated.models.o_data_errors.o_data_error.ODataError: {"message": null, "response_status_code": 400,
> ...
> "message": "[item] Read called with an open stream or textreader. Please close any open streams or text readers before calling Read."

I attempted to pass a stream and made the necessary modifications as follows. The error no longer occurs; however, the uploaded file has a size of 0 bytes.

```python
request_body.content = io.BytesIO(b'abcde')
```

Could the issue be due to incorrect usage of the API?

**Comment by vdimov-gcmlp** [comment]
Did you resolve this issue?

**Comment by shinkawk** [comment]
Hi @hide212131 @vdimov-gcmlp 

After tinkering for a several days, I found the following code as a workaround:

```
# Create an empty file called a.txt via Post API
request_body = DriveItem()
request_body.name = 'a.txt'
request_body.file = File()
result = await drive_req.items.by_drive_item_id('root').children.post(body=request_body)

# Put actual data using Put API
file_id = result.id
content = b'abcde' # Load your actual data here
await drive_req.items.by_drive_item_id(file_id).content.put(body=content)
```

So instead of trying to put bytes data using POST, you can upload data with PUT after creating an empty DriveItem.

Hope this helps!

**Comment by vdimov-gcmlp** [comment]
@shinkawk, thank you for the example. I was able to successfully upload a file another way using the example below, but that has downsides (it allows to overwrite existing files, creating a version of the previous file, without providing additional request params.

```python
await client.drives.by_drive_id(drive_id).items.by_drive_item_id(parent_id).children.by_drive_item_id1("file_name.txt").content.put(b'abcde')
```

Given MSGraph documentation, both ways should work for files <4MB. Anything larger would necessitate creating an upload session which is also not documented. If anyone has a sample of creating a session to upload larger files that will be greatly appreciated.

**Comment by paulschmeida** [comment]
The method above works for files up to 250mb, just tested it.

**Comment by andrueastman** [comment]
Closing this for now. Correct usage of the API is to use a PUT request to the `/content` endpoint

https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http
