### ISSUE TITLE
Appplication owners is always None

### ISSUE THREAD

**Issue by wradstok** [microsoftgraph/msgraph-sdk-python#284]
When fetching the owners of an app registration, the result is always `None`. Is this because some sort of delegated permission is required to access the field?

```
import asyncio
from azure.identity import DefaultAzureCredential
from msgraph import GraphServiceClient

# Create a credential object. Used to authenticate requests
credential = DefaultAzureCredential()
scopes = ["https://graph.microsoft.com/.default"]

# Create an API client with the credentials and scopes.
client = GraphServiceClient(credentials=credential, scopes=scopes)


async def get_app_owners():
    app = await client.applications.by_application_id(
        "<<app_registration_object_id_here>>"
    ).get()
    print(app.owners)

asyncio.run(get_app_owners())

```

**Comment by samwelkanda** [comment]
Hi @wradstok 

There is a separate endpoint o get application owners. See [documentation](https://learn.microsoft.com/en-us/graph/api/application-list-owners?view=graph-rest-1.0&tabs=python).

The resulting call should be:

`result = await graph_client.applications.by_application_id('application-id').owners.get()`

**Comment by wradstok** [comment]
Thanks, did not expected that as the owners field was present but None.
