### ISSUE TITLE
Cannot call microsoft_graph_call_records_get_pstn_calls_with_from_date_time_with_to_date_time

### ISSUE THREAD

**Issue by kotoy** [microsoftgraph/msgraph-sdk-python#285]
When I call result = await client.communications.call_records.microsoft_graph_call_records_get_pstn_calls_with_from_date_time_with_to_date_time(from_date_time, to_date_time).get()
  
I get the following error:

msgraph.generated.models.o_data_errors.o_data_error.ODataError: {"message": null, "response_status_code": 400, "response_headers": "Headers({'transfer-encoding': 'chunked', 'content-type': 'application/json', 'content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'strict-transport-security': 'max-age=31536000', 'request-id': 'b4923bb3-bfdf-437d-a5a5-e775ddc61eb9', 'client-request-id': 'c2cedb47-8612-4259-8408-736a3cb0b0ee', 'x-ms-ags-diagnostic': '{\"ServerInfo\":{\"DataCenter\":\"West Europe\",\"Slice\":\"E\",\"Ring\":\"5\",\"ScaleUnit\":\"010\",\"RoleInstance\":\"AM4PEPF00027789\"}}', 'date': 'Thu, 03 Aug 2023 14:17:09 GMT'})", "additional_data": {}, "error": {"additional_data": {}, "code": "BadRequest", "details": null, "inner_error": {"additional_data": {"date": "14:17:10"}, "client_request_id": "c2cedb47-8612-4259-8408-736a3cb0b0ee", "date": null, "odata_type": null, "request_id": "b4923bb3-bfdf-437d-a5a5-e775ddc61eb9"}, "message": "Expression expected at position 13 in 'fromDateTime=,toDateTime='.", "target": null}}

It seems that fromDateTime and ToDateTime doesn't get passed coorectly.

**Comment by sam-marteau** [comment]
Disclaimer: i am a freaking amateure
This did the trick to me:
open microsoft_graph_call_records_get_direct_routing_calls_with_from_date_time_with_to_date_time_request_builder.py
note line 30
params were not used to concatinate the url string, so the request URL was not built correctly. used strftime as well to format date correctly

[microsoft_graph_call_records_get_direct_routing_calls_with_from_date_time_with_to_date_time_request_builder.txt](https://github.com/microsoftgraph/msgraph-sdk-python/files/12537606/microsoft_graph_call_records_get_direct_routing_calls_with_from_date_time_with_to_date_time_request_builder.txt)
