### ISSUE TITLE
Cannot instantiate GraphServiceClient with microsoft-kiota-abstractions==0.7.0

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-python#289]
The following code throws a `TypeError` after upgrading microsoft-kiota-abstractions to 0.7.0.

```python
from azure.identity.aio import ClientSecretCredential
from msgraph import GraphServiceClient

client_credential = ClientSecretCredential(tenant_id, client_id, client_secret)
app_client = GraphServiceClient(client_credential) # type: ignore
```

## Error

```
  File "/home/jasonjoh/repos/msgraph-training-python/app-auth/graphapponlytutorial/graph.py", line 22, in __init__
    self.app_client = GraphServiceClient(credentials=self.client_credential) # type: ignore
  File "/home/jasonjoh/.local/lib/python3.10/site-packages/msgraph/graph_service_client.py", line 48, in __init__
    request_adapter = GraphRequestAdapter(auth_provider)
TypeError: Can't instantiate abstract class GraphRequestAdapter with abstract method convert_to_native_async
```

**Comment by isvargasmsft** [comment]
CC: @shemogumbe @samwelkanda would you please review? The Extron team is having the exact same issue.

**Comment by dernstOfExtron** [comment]
I have duplicated the error as well.  I tried using python3.8 and python3.9 with the same error as shown above. It also fails using certificates/keys again with the same error.

**Comment by zb-creativeone** [comment]
Looks like there was a [commit ](https://github.com/microsoft/kiota-abstractions-python/commit/991909eb790644de8b6f1b9958ad1bca084ed3f9) that added the `convert_to_native_async` abstract method to the Kiota abstractions request adapter in the latest release.  The problem being that the Kiota `HttpxRequestAdapter` class that the `BaseGraphRequestAdapter` class (and in turn the `GraphRequestAdapter`) inherits from does not implement this abstract class in it's latest release.  The code is there in the latest [commit](https://github.com/microsoft/kiota-http-python/blob/87b21c3ec004effdc6e9a8711c637083daf058a1/kiota_http/httpx_request_adapter.py#L351), but will require deploying to Pypi.  As a workaround in the meantime, you can copy the implementation (lines 351-358) to your local `\Lib\site-packages\kiota_http\httpx_request_adapter.py` file.  Hope that helps!

**Comment by AlanBridgeman** [comment]
Sorry if I'm wrong to reply to this issue here but I spent a bunch of time trying to resolve this issue and thought I might share. 

It started with having the same issue as noted above and applying the [recommended commit](https://github.com/microsoft/kiota-http-python/blob/87b21c3ec004effdc6e9a8711c637083daf058a1/kiota_http/httpx_request_adapter.py#L351) but once that was done I started getting a similar issue related to the `JsonSerializationWriter` class:

```
TypeError: Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization
```

From what I can tell, which do take with the appropriate amount of skepticism because my knowledge of these libraries is not the greatest, it's related to this [commit](https://github.com/microsoft/kiota-abstractions-python/commit/ec0147d564214d75bd9c2a5dd65b79459c690c06#diff-a87371b2f28f039a731a8d1a854aa43ff4d3c70905cd45dc46009f951e25307e) which was also included in the 0.7.0 release and specifically the changes in the `serialization_writer.py` file:
- `get_on_before_object_serialization` to `on_before_object_serialization`, 
- `get_on_after_object_serialization` to `on_before_object_serialization`, 
- `set_on_after_object_serialization` to `on_start_object_serialization`, 
- `set_on_start_object_serialization` to `on_start_object_serialization`

which are then reflected in the `\lib\site-packages\kiota_serialization_json\json_serialization_writer.py` in this [commit](https://github.com/microsoft/kiota-serialization-json-python/commit/b009d50f23004cff36024d115758bccff7801f5f#diff-8bf69659b0ea2c0a8090d9f472cf9e7b49c5f9ecf6e11bc3455446f9b866b1e5) if I'm not wrong.

So, in an attempt to get this all working inside a docker container (which is part of my use case) I came up with the following (note, I shortened some of paths for brevity)
```
RUN echo "    async def convert_to_native_async(self, request_info: RequestInformation) -> httpx.Request:" >> .../site-packages/kiota_http/httpx_request_adapter.py \
    && echo "        if request_info is None:" >> .../site-packages/kiota_http/httpx_request_adapter.py \
    && echo "            raise ValueError('request information must be provided')" >> .../site-packages/kiota_http/httpx_request_adapter.py \
    && echo "        " >> .../site-packages/kiota_http/httpx_request_adapter.py \
    && echo "        await self._authentication_provider.authenticate_request(request_info)" >> .../site-packages/kiota_http/httpx_request_adapter.py \
    && echo "        " >> .../site-packages/kiota_http/httpx_request_adapter.py \
    && echo "        request = self.get_request_from_request_information(request_info)" >> .../site-packages/kiota_http/httpx_request_adapter.py \
    && echo "        return request" >> .../site-packages/kiota_http/httpx_request_adapter.py

COPY json_serialization_writer.py .../site-packages/kiota_serialization_json/
```

Where the `json_serialization_writer.py` file is the updated one downloaded from Github.

With those changes it did seem to be back to working (for me at least). Though until the `microsoft-kiota-http` and `microsoft-kiota-serialization-json` libraries are updated with the needed commits it seems like it would probably be easier for people to target (or rollback to) an earlier version of the `microsoft-kiota-abstractions` library (especially because editing libraries internal files outside of the package manager always seems to end badly in my experience).

Anyway, hopefully this might help people if their having the same issues etc...

**Comment by zb-creativeone** [comment]
@AlanBridgeman - I ran into this afterwards as well and just ended up rolling back `microsoft-kiota-abstractions` to the previous release `0.6.0`.  Great catch!  I'll submit a new issue on the Kiota side if there's no movement on this tomorrow.

    pip uninstall microsoft-kiota-abstractions
    pip install microsoft-kiota-abstractions==0.6.0

**Comment by dernstOfExtron** [comment]
Rolling back to 0.6.0 now fails with the error: AttributeError: 'GraphRequestAdapter' object has no attribute 'get_token'

  user = await self._client.users.by_user_id(self._account_calendar).get(  # type:ignore
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/user_item_request_builder.py", line 154, in get
    return await self.request_adapter.send_async(request_info, User, error_mapping)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py", line 113, in send_async
    response = await self.get_http_response_message(request_info)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py", line 324, in get_http_response_message
    await self._authentication_provider.authenticate_request(request_info)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/authentication/base_bearer_token_authentication_provider.py", line 27, in authenticate_request
    token = await self.access_token_provider.get_authorization_token(request.url)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_authentication_azure/azure_identity_access_token_provider.py", line 49, in get_authorization_token
    if inspect.iscoroutinefunction(self._credentials.get_token):
AttributeError: 'GraphRequestAdapter' object has no attribute 'get_token'

**Comment by zb-creativeone** [comment]
@dernstOfExtron  - they deployed a new release of the `microsoft-kiota-http` package version 0.5.0, which I'm guessing updates that library to match the abstractions update from Friday.  I'm about to walk into a meeting, but you might try updating the abstractions and http package to the latest and see if that fixes the issue.

**Comment by dernstOfExtron** [comment]
Made it a bit further, but it now fails with: TypeError: Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization
----------------------------------------------------------------------------------------------------------------------

File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 81, in post
    request_info = self.to_post_request_information(
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 132, in to_post_request_information
    request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 158, in set_content_from_parsable
    writer = self._get_serialization_writer(request_adapter, content_type, values)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 244, in _get_serialization_writer
    return request_adapter.get_serialization_writer_factory(
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/serialization/serialization_writer_factory_registry.py", line 39, in get_serialization_writer
    return factory.get_serialization_writer(vendor_specific_content_type)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_serialization_json/json_serialization_writer_factory.py", line 30, in get_serialization_writer
    return JsonSerializationWriter()
TypeError: Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization
ERROR:root:CalendarMicrosoftGraph.py:138 my_run_until_complete() Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization
Traceback (most recent call last):
  File "/home/dernst/Perforce/dernst_xcalendar/linux_sw/common/xcalendar/branch_dev/src/xcalendar/scheduler/CalendarMicrosoftGraph.py", line 134, in my_run_until_complete
    retval = self._loop.run_until_complete(future)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/dernst/Perforce/dernst_xcalendar/linux_sw/common/xcalendar/branch_dev/src/xcalendar/scheduler/CalendarMicrosoftGraph.py", line 332, in create_event
    raise e
  File "/home/dernst/Perforce/dernst_xcalendar/linux_sw/common/xcalendar/branch_dev/src/xcalendar/scheduler/CalendarMicrosoftGraph.py", line 317, in create_event
    requestResult = await self._client.users.by_user_id(self._account_calendar).[events.post](http://events.post/)(  # type:ignore
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 81, in post
    request_info = self.to_post_request_information(
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 132, in to_post_request_information
    request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 158, in set_content_from_parsable
    writer = self._get_serialization_writer(request_adapter, content_type, values)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 244, in _get_serialization_writer
    return request_adapter.get_serialization_writer_factory(
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/serialization/serialization_writer_factory_registry.py", line 39, in get_serialization_writer
    return factory.get_serialization_writer(vendor_specific_content_type)
  File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_serialization_json/json_serialization_writer_factory.py", line 30, in get_serialization_writer
    return JsonSerializationWriter()
TypeError: Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization

**Comment by Morgomor** [comment]
> ## Made it a bit further, but it now fails with: TypeError: Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization
> File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 81, in post request_info = self.to_post_request_information( File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 132, in to_post_request_information request_info.set_content_from_parsable(self.request_adapter, "application/json", body) File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 158, in set_content_from_parsable writer = self._get_serialization_writer(request_adapter, content_type, values) File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 244, in _get_serialization_writer return request_adapter.get_serialization_writer_factory( File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/serialization/serialization_writer_factory_registry.py", line 39, in get_serialization_writer return factory.get_serialization_writer(vendor_specific_content_type) File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_serialization_json/json_serialization_writer_factory.py", line 30, in get_serialization_writer return JsonSerializationWriter() TypeError: Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization ERROR:root:CalendarMicrosoftGraph.py:138 my_run_until_complete() Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization Traceback (most recent call last): File "/home/dernst/Perforce/dernst_xcalendar/linux_sw/common/xcalendar/branch_dev/src/xcalendar/scheduler/CalendarMicrosoftGraph.py", line 134, in my_run_until_complete retval = self._loop.run_until_complete(future) File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/home/dernst/Perforce/dernst_xcalendar/linux_sw/common/xcalendar/branch_dev/src/xcalendar/scheduler/CalendarMicrosoftGraph.py", line 332, in create_event raise e File "/home/dernst/Perforce/dernst_xcalendar/linux_sw/common/xcalendar/branch_dev/src/xcalendar/scheduler/CalendarMicrosoftGraph.py", line 317, in create_event requestResult = await self._client.users.by_user_id(self._account_calendar).[events.post](http://events.post/)( # type:ignore File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 81, in post request_info = self.to_post_request_information( File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/msgraph/generated/users/item/events/events_request_builder.py", line 132, in to_post_request_information request_info.set_content_from_parsable(self.request_adapter, "application/json", body) File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 158, in set_content_from_parsable writer = self._get_serialization_writer(request_adapter, content_type, values) File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/request_information.py", line 244, in _get_serialization_writer return request_adapter.get_serialization_writer_factory( File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_abstractions/serialization/serialization_writer_factory_registry.py", line 39, in get_serialization_writer return factory.get_serialization_writer(vendor_specific_content_type) File "/home/dernst/anaconda3/envs/xcalendar_msgraph_test2/lib/python3.9/site-packages/kiota_serialization_json/json_serialization_writer_factory.py", line 30, in get_serialization_writer return JsonSerializationWriter() TypeError: Can't instantiate abstract class JsonSerializationWriter with abstract methods on_after_object_serialization, on_before_object_serialization, on_start_object_serialization

I run into the same issue as well now, version 0.4.0 of microsoft-kiota-serialization-json

**Comment by dernstOfExtron** [comment]
After upgrading to 0.4.0 my app now is working.  

I had to make one change to my app but I think the issue is with msgraph-sdk and events and not microsoft-kiota.*

**Comment by zb-creativeone** [comment]
Good to hear.  I just tested a fresh install in a virtual environment and the latest versions are working so I believe this issue can be closed.

Fresh install pkgs working ✔:

    microsoft-kiota-abstractions==0.7.0
    microsoft-kiota-authentication-azure==0.2.0
    microsoft-kiota-http==0.5.0
    microsoft-kiota-serialization-json==0.4.0
    microsoft-kiota-serialization-text==0.2.1

Note - the http and serialization-json packages have both been updated to match the abstractions update.

**Comment by Morgomor** [comment]
Thanks a lot! pinned these versions of kiota (didnt uninstall msgraph-sdk), and now it works.
