### ISSUE TITLE
Error when following the tutorial

### ISSUE THREAD

**Issue by Marwan-Ru** [microsoftgraph/msgraph-sdk-python#313]
When following the [tutorial](https://learn.microsoft.com/en-us/graph/tutorials/python?tabs=aad&tutorial-step=6) on the microsoft website I get the following error when testing out the email sending:
```
Error:
RequestBodyRead The property 'name' does not exist on type 'microsoft.graph.recipient'. Make sure to only use property names that are defined by the type or mark the type as open type.
```

I verified that I copied exactly what the tutorial provides. The rest of the tutorial is functional for me.

Python 3.11.4. and version 1.0.0a14 of msgraph.

My best guess would be that some changes have been made that havent been put in the Tutorial yet.

**Comment by samwelkanda** [comment]
Hi @Woople74 

I have run the tutorial against the latest version `v1.0.0a16` and it works fine. The underlying seems to have been addressed in the interval.

Please test it out again and re-open the issue if it persists.

Thanks.
