### ISSUE TITLE
pip error: dependency conflicts with uritemplate 4.1.1

### ISSUE THREAD

**Issue by zongo811** [microsoftgraph/msgraph-sdk-python#315]
*Environment**

- Python Version: 3.10.9
- msgraph-core version: 1.0.0a14 
- OS: debian buster

**Describe the bug**
While using "python3 -m pip install msgraph-sdk" the error below occurred. 

**Stack trace **
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-api-python-client 2.2.0 requires uritemplate<4dev,>=3.0.0, but you have uritemplate 4.1.1 which is incompatible.
```
**To Reproduce**
Not so easy. I'm using frappe framework, and can't use pip to show me the dependencies.
I just wanted to let you know that this problem exists, maybe you can switch to another version of google-api-python-client that doesn't clash with uritemplate 4.1.1

**Comment by samwelkanda** [comment]
Hi @zongo811 

Thanks for reporting this issue. 

We have since swiched to using std-uritemplate instead. Updating to `microsoft-kiota-abstractions==0.8.5` should resolve the conflict.
Thanks

**Comment by samwelkanda** [comment]
Closing for now. Feel free to re-open if the issue persists.

**Comment by zongo811** [comment]
Hi @samwelkanda ,
I can now install your package and everything seems to be fine.
Thank you!
