### ISSUE TITLE
TypeError: DeviceCodeCredential

### ISSUE THREAD

**Issue by JyothsnaPendyala** [microsoftgraph/msgraph-sdk-python#318]
credential = DeviceCodeCredential(client_id,tenant_id)

TypeError: DeviceCodeCredential.__init__() takes from 1 to 2 positional arguments but 3 were given

I am facing the above problem even though only two arguments were passed.

**Comment by samwelkanda** [comment]
Hi @JyothsnaPendyala 

This was caused by a bug introduced during an update to the auth library to support conditional access.
Please install the latest sdk version `1.0.0a15` or update to `microsoft-kiota-authentication-azure==0.3.0` to resolve the issue.

Thanks.

**Comment by viperscape** [comment]
Hi

I have updated to the alpha but this issue persists for me.

Updated packages with pip: `Successfully installed PyJWT-2.8.0 aiohttp-3.8.5 aiosignal-1.3.1 anyio-4.0.0 async-timeout-4.0.3 attrs-23.1.0 azure-core-1.29.4 azure-identity-1.14.0 certifi-2023.7.22 cffi-1.15.1 charset-normalizer-3.2.0 cryptography-41.0.3 deprecated-1.2.14 frozenlist-1.4.0 h11-0.14.0 h2-4.1.0 hpack-4.0.0 httpcore-0.18.0 httpx-0.25.0 hyperframe-6.0.1 idna-3.4 importlib-metadata-6.8.0 microsoft-kiota-abstractions-0.8.5 microsoft-kiota-authentication-azure-0.3.0 microsoft-kiota-http-0.6.0 microsoft-kiota-serialization-json-0.4.0 microsoft-kiota-serialization-text-0.2.1 msal-1.24.0 msal-extensions-1.0.0 msgraph-core-1.0.0a4 msgraph-sdk-1.0.0a15 multidict-6.0.4 opentelemetry-api-1.20.0 opentelemetry-sdk-1.20.0 opentelemetry-semantic-conventions-0.41b0 portalocker-2.8.2 pycparser-2.21 python-dateutil-2.8.2 pywin32-306 requests-2.31.0 six-1.16.0 sniffio-1.3.0 std-uritemplate-0.0.40 typing-extensions-4.8.0 urllib3-2.0.4 wrapt-1.15.0 yarl-1.9.2 zipp-3.17.0`

Confirmed that site-packages `_version.py` for msgraph shows: `VERSION: str = '1.0.0a15'`

**Comment by samwelkanda** [comment]
@viperscape 

This error arises from the `azure-identity` dependency which we use for authentication. From the documentation [here](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.devicecodecredential?view=azure-python)
this is the constructor:
```py
DeviceCodeCredential(client_id: str = '04b07795-8ddb-461a-bbee-02f9e1bf7b46', *, timeout: int | None = None, prompt_callback: Callable[[str, str, datetime], None] | None = None, **kwargs: Any)
```

From the above, the constructor only expects 1 positional parameter, `client_id`.
If you need to provide more arguments then I suggest you use kwargs like so:
```py
credential = DeviceCodeCredential(
    client_id='CLIENT_ID',
    tenant_id='TENANT_ID',
    client_secret='CLIENT_SECRET'
)
```
