### ISSUE TITLE
Failed to parse `guest_or_external_user_types`

### ISSUE THREAD

**Issue by jjaychen1e** [microsoftgraph/msgraph-sdk-python#327]
https://github.com/microsoftgraph/msgraph-sdk-python/blob/33354eacd8bb4e20d67cce3b46562d42b7024c98/msgraph/generated/models/conditional_access_guests_or_external_users.py#L17

https://github.com/microsoftgraph/msgraph-sdk-python/blob/33354eacd8bb4e20d67cce3b46562d42b7024c98/msgraph/generated/models/conditional_access_guests_or_external_users.py#L44

https://github.com/microsoftgraph/msgraph-sdk-python/blob/33354eacd8bb4e20d67cce3b46562d42b7024c98/msgraph/generated/models/conditional_access_guest_or_external_user_types.py#L3-L11

An example value of `guest_or_external_user_types` is `internalGuest,b2bCollaborationGuest,b2bCollaborationMember,b2bDirectConnectUser,otherExternalUser,serviceProvider`, which is a multi-value string separated with comma. But in the code, it's parsed as a single value enum.

**Comment by shemogumbe** [comment]
Hello @jjaychen1e working on this now, initial investigations gives me an idea that we could make changes in the serialization library to allow `ConditionalAccessGuestOrExternalUserTypes` and other  enum to be correctly serialized and deserialized as a multi-value string separated by commas.

To help reproduce and test this, do you mind sharing some code snippet that produced this bug and the stack trace.

To try and reproduce this, I have created a conditional access policy  and edited it to work for guests_or_external_users:

**Creating a policy**
```json
{
    "displayName": "Block access from untrusted locations for Guests",
    "state": "enabled",
    "conditions": {
        "users": {
            "includeGroups": [],  
            "includeUsers": [],  
            "excludeUsers": [],
            "includeGuests": true  
        },
        "locations": {
            "includeLocations": ["All"],
            "excludeLocations": []  
        },
        "platforms": {
            "includePlatforms": ["all"]
        },
        "applications": {
            "includeApplications": ["e8ab3e88-84aa-4399-a4e6-0ce4b356327c"],  
            "excludeApplications": []
        }
    },
    "grantControls": {
        "operator": "OR",
        "builtInControls": ["block"]
    }
}

```

**The policy below has guest_or_users allowed with all memberkinds:**

![conditional_access_user_types](https://github.com/user-attachments/assets/1011ecad-2eac-433e-be49-3f15f71cf387)


Querying it to the user types level throws no bug:

```python
policy_id = "c63e8ff2-aa9c-407a-a21f-f4f2d8a81ec7"


# GE - https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies
async def get_conditional_access_policies():
    policy = await user_client.identity.conditional_access.policies.by_conditional_access_policy_id(
        policy_id).get()

    print(
        f"Policy conditions: {policy.conditions.users.include_guests_or_external_users.guest_or_external_user_types}"
    )


asyncio.run(get_conditional_access_policies())

```


This points to an issue on the serialization library,  kindly confirm if this is similar to your error, optionally, is your error when you run a ge
t on a conditional access policy with guests_or_external_users set to true? Also are you using default security groups or using conditional access policies you have created yourself? if your own policeis, mind sharing the preview of the policy?
