### ISSUE TITLE
How use filters?

### ISSUE THREAD

**Issue by danielniccoli** [microsoftgraph/msgraph-sdk-python#337]
I want to send this query to the Graph API using this SDK:  
`https://graph.microsoft.com/v1.0/users?$select=id,displayName,createdDateTime&$filter=userType eq 'Member' and createdDateTime ge 2023-02-20T10:30:00Z and createdDateTime le 2023-02-20T11:00:00Z`

How do I use filters? This is what I tried:

```py
# https://graph.microsoft.com/v1.0/users?$select=displayName,createdDateTime&$filter=userType eq 'Member' and createdDateTime ge 2023-02-20T10:30:00Z and createdDateTime   le 2023-02-20T11:00:00Z

query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
    select=["id", "displayName", "createdDateTime"],
    filter=[
        "userType eq 'Member' and createdDateTime ge 2023-02-20T10:30:00Z and createdDateTime le 2023-02-20T11:00:00Z",
    ],
)
result: UserCollectionResponse = await GRAPH_CLIENT.users.get(query_params)

```

Throws

```
Exception has occurred: AttributeError
'UsersRequestBuilderGetQueryParameters' object has no attribute 'headers'
```

I would appreciate some help on this.

This issue would probably not have been necessary, if there would be a documentation... (https://github.com/microsoftgraph/msgraph-sdk-python/issues/282)

**Comment by samwelkanda** [comment]
Hi @danielniccoli 
A request accepts a RequestConfiguration object which is composed of query_parameters, headers and custom options.

Here's a working sample of what your request should translate to.

```py
from msgraph.generated.users.users_request_builder import UsersRequestBuilder
async def get_users():
    query_params = UsersRequestBuilder.UsersRequestBuilderGetQueryParameters(
    select=["id", "displayName", "createdDateTime"],
    filter = "userType eq 'Member' and createdDateTime ge 2023-02-20T10:30:00Z and createdDateTime le 2023-02-20T11:00:00Z",
    )
    request_config = UsersRequestBuilder.UsersRequestBuilderGetRequestConfiguration(
        query_parameters=query_params
    )
    users = await client.users.get(request_configuration=request_config)
    for user in users.value:
        print(user.id, user.display_name, user.mail)
asyncio.run(get_users())
```

For more information checkout out our documentation here: https://learn.microsoft.com/en-us/graph/filter-query-parameter?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=python

**Comment by samwelkanda** [comment]
Just to add, using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) you can paste the http url you'd like to access, click run and in the code snippets tab below, select Python and you can get an equivalent sdk code snippet automatically generated for you.

![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/40166690/c88008f6-41e2-43c1-86a6-38a76ba4fcc1)

![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/40166690/14846bd8-51c2-471e-99fd-9abebe738628)

**Comment by samwelkanda** [comment]
Closing this for now. Feel free to re-open as needed.
