### ISSUE TITLE
ValidatePropertiesPostRequestBody not accepting entity_type="Group"

### ISSUE THREAD

**Issue by danielniccoli** [microsoftgraph/msgraph-sdk-python#372]
I'm trying to validate properties before sending a create request to the Graph API. This throws an error that I would say is a bug in the SDK.

```py
request_body = ValidatePropertiesPostRequestBody(
    entity_type="Group",
    display_name=grouprequest.display_name,
    mail_nickname=grouprequest.mail_nickname,
    on_behalf_of_user_id=grouprequest.owner,
)
ret = await GRAPH_CLIENT.directory_objects.validate_properties.post(
    body=request_body
)
```

Throws

> ODataError: APIError 400: None MainError(additional_data={}, code='Request_BadRequest', details=None, inner_error=InnerError(additional_data={'date': datetime.timedelta(seconds=45788)}, client_request_id='92a3ba0d-bc66-4e22-98cf-62350dfbb381', date=None, odata_type=None, request_id='7004a753-e9c3-4072-85bd-23837a092c5a'), **message='Invalid entity type provided. Supported entities include: Group.'**, target=None)

**Comment by samwelkanda** [comment]
@danielniccoli 

This was a bug in serialization that was fixed in subsequent versions.

Please update to the latest stable version (v1.0.0) to resolve.

Thanks
