### ISSUE TITLE
Update servicePrincipal operation not working

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-sdk-python#374]
Though the update operation to change the “app_role_assignment_required” of “service principal” to “True” is executed without error. But I found the “app_role_assignment_required” isn’t updated to “True” after checked. 

Code:
```py
def get_msgraph_client(self, tenant_id):
        from msgraph import GraphServiceClient
        return GraphServiceClient(self.azure_auth.azure_credential_track2)

self._client = self.get_msgraph_client(self.tenant)

request_body = ServicePrincipal(
                    app_role_assignment_required = self.app_role_assignment_required
                )

asyncio.get_event_loop().run_until_complete(self.update_service_principal(old_response, request_body))

async def update_service_principal(self, old_response, request_body):
        return await self._client.service_principals.by_service_principal_id(old_response['object_id']).patch(body = request_body)

```

Docs: https://learn.microsoft.com/en-us/graph/api/serviceprincipal-update?view=graph-rest-1.0&tabs=python#request

**Comment by isvargasmsft** [comment]
CC: @shemogumbe @samwelkanda

**Comment by isvargasmsft** [comment]
Similar to https://github.com/microsoftgraph/msgraph-sdk-python/issues/377

**Comment by neil-yechenwei** [comment]
@isvargasmsft , May I ask if this issue is fixed?

**Comment by samwelkanda** [comment]
Fixed in subsequent sdk versions. Please update to the latest version
