### ISSUE TITLE
Update application password operation not executing

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-sdk-python#379]
Though the update operation is executed without error but I found the password isn’t added/updated.

Code:
```py
def get_msgraph_client(self, tenant_id):
        from msgraph import GraphServiceClient
        return GraphServiceClient(self.azure_auth.azure_credential_track2)

self._client = self.get_msgraph_client(self.tenant)

async def update_password_in_application(self, old_passwords):
        request_body = Application(
                password_credentials = old_passwords
            )
        return await self._client.applications.by_application_id(self.app_object_id).patch(body = request_body)

```

Docs: https://learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=python#example

**Comment by isvargasmsft** [comment]
Similar to https://github.com/microsoftgraph/msgraph-sdk-python/issues/374 and https://github.com/microsoftgraph/msgraph-sdk-python/issues/377

**Comment by isvargasmsft** [comment]
@shemogumbe @samwelkanda

**Comment by neil-yechenwei** [comment]
@isvargasmsft , May I ask if this issue is fixed?

**Comment by samwelkanda** [comment]
Fixed in subsequent sdk versions. Please update to the latest version
