### ISSUE TITLE
How can we make this library better?

### ISSUE THREAD

**Issue by stvpwrs** [microsoftgraph/msgraph-sdk-python#382]
Hello,

I have been trying to work with this library over the past 2 weeks and I would like to try and help make some more samples, but I frankly can't figure out enough of the library to even do some of that. 

Is there a way to get some time with developers on the team or work more with PnP community to get more collaboration going for this library?

I'm eager to start contributing here because this is going to be an important library for my company.

**Comment by danielniccoli** [comment]
@stvpwrs Unfortunately, Microsoft decided to go the computer generated route for this SDK. The "documentation" (Microsoft's word for whatever there is) is also of bad quality (#282). Afaik there is nothing to contribute to for this repo.

**Comment by WardenHub** [comment]
I'm trying to use the sendmail graph api, it's just terribly documented what needs to be in the header and how to do the msal. 

Kicker? if you dont use the sdk you get some rando error 500 'internal server error', when you ask support for what's missing they tell you to use the SDK.. round and round we go.

**Comment by stvpwrs** [comment]
@danielniccoli with the SDK going GA this month, I plan to try an raise awareness of this issue. I'm hoping there are some changes in the near future.

**Comment by rkodev** [comment]
Hi @stvpwrs, Thanks for trying out the Graph Python SDK.  As mentioned above, this SDK is generated using [Kiota - Kiota is a command line tool for generating an API client ](https://github.com/microsoft/kiota). If you would wish would still wish to make contributions to the Graph Python SDK, I would suggest you begin by getting acquainted with Kiota.

As for more information about the SDK, you can view the [contribution ](https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/CONTRIBUTING.md)guideline
