### ISSUE TITLE
Unable to retrieve Planner Tasks via method provided by documentation

### ISSUE THREAD

**Issue by Murder-Chicken** [microsoftgraph/msgraph-sdk-python#383]
As per the documentation provided on the [MS Graph SDK Resource page](https://learn.microsoft.com/en-us/graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=python), users are instructed to use the following method to retrieve  a list of [plannerTask](https://learn.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-1.0) objects associated with a [plannerPlan](https://learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-1.0) object.

`result = await graph_client.planner.plans.by_plan_id('plannerPlan-id').tasks.get()`

However, upon issuing the request, I recieve the following error:
`AttributeError: 'PlansRequestBuilder' object has no attribute 'by_plan_id'`

I have the following delegated permissions assigned to be able to perform the request as well: Tasks.Read, Tasks.Read.Shared, Tasks.ReadWrite, Tasks.ReadWrite.Shared, User.Read.

Is the feature still a work in progress for the Python SDK or is there something I am missing?

I'd appreciate any help on the matter.

**Comment by masyanru** [comment]
have you tried `by_planner_plan_id`, 'cause there is a lot of mistyping in docs - https://github.com/microsoftgraph/msgraph-sdk-python/blob/9300f9911874471a6bbebfdde9ae974affebd7fa/msgraph/generated/planner/plans/plans_request_builder.py#L32

**Comment by Murder-Chicken** [comment]
Yup, that did it! Definitely should just check the code myself next time...

Regardless, thanks for the pointer!
