### ISSUE TITLE
Failed to set displayName of the application password

### ISSUE THREAD

**Issue by neil-yechenwei** [microsoftgraph/msgraph-sdk-python#398]
@isvargasmsft , I tried to set displayName of the application password to "abc" but MS Graph API can't set it correctly without error at creation and it always returns null/none for this property. Could you take a look this issue? Thanks.

Code:
```
self._client = self.get_msgraph_client(self.tenant)

request_body = AddPasswordPostRequestBody(
                password_credential = PasswordCredential(
                    start_date_time = start_date,
                    end_date_time = end_date,
                    display_name = display_name
                ),
            )
pd = asyncio.get_event_loop().run_until_complete(self.add_password(request_body))

async def add_password(self, request_body):
        return await self._client.applications.by_application_id(self.app_object_id).add_password.post(body = request_body)
```

API Response:
```
PasswordCredential(display_name=None)
```

**Comment by isvargasmsft** [comment]
Docs:
https://learn.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=python#request

@samwelkanda, would you take a quick look, please?

**Comment by samwelkanda** [comment]
Hi @neil-yechenwei 

This was a bug in how we set properties to our backing store. Updating to the latest sdk version `msgraph-sdk 1.0.0rc1` should resolve.

Thanks
