### ISSUE TITLE
OneDrive path based addressing

### ISSUE THREAD

**Issue by wryun** [microsoftgraph/msgraph-sdk-python#40]
DriveItems support file paths as part of the URL:

e.g.
```
/me/drive/root:/{item-path}:/createUploadSession
```

Could I confirm that the msgraph-sdk has no support for this at the moment? I've had a bit of a poke around, and it seems like there's no urlTemplate like this and no mechanism to set something like item-path.

**Comment by Ndiritu** [comment]
@wryun to minimize SDK size, this version of the SDK provides access to resources via the root path of the resource in cases where there are multiple URLs to perform the same operation e.g. an upload session can be created via [multiple endpoints](https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#http-request) but the SDK supports accessing the root of the resource i.e. `/drives/{driveId}/items/{itemId}/createUploadSession`

You should be able to create the upload session via:
```python
await client.drives_by_id('driveId').items_by_id('root:/{item-path}:').create_upload_session().post()
```

**Comment by Ndiritu** [comment]
@shemogumbe  @baywet @isvargasmsft should we add a disclaimer on the READMEs that not all API paths will be supported by the request builders & what fallback options we will provide if any? We had a similar issue in [PHP](https://github.com/microsoftgraph/msgraph-sdk-php/issues/939).

**Comment by baywet** [comment]
Thanks for flagging this. The workarounds for those sort of situations are:
- issue two requests, one to get the id, and then another one on the canonical path with the id.
- instantiate a request builder, pass an already built URLs

none are great from a user experience perspective.

**Comment by Ndiritu** [comment]
Do we currently support workaround 2?

**Comment by baywet** [comment]
We should for that scenario specifically.
The way it's done in dotnet and Go is we have overload constructors that either accept the path parameters (fluent API passing things along) or the raw URL for this purpose.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/767c30e984b3fec03e6e5ca11b4c68c6db935249/admin/admin_request_builder.go#L43
https://github.com/microsoftgraph/msgraph-sdk-go/blob/767c30e984b3fec03e6e5ca11b4c68c6db935249/admin/admin_request_builder.go#L56

**Comment by isvargasmsft** [comment]
> @shemogumbe @baywet @isvargasmsft should we add a disclaimer on the READMEs that not all API paths will be supported by the request builders & what fallback options we will provide if any? We had a similar issue in [PHP](https://github.com/microsoftgraph/msgraph-sdk-php/issues/939).

@samwelkanda for visibility.

**Comment by samwelkanda** [comment]
Going with the convention of accessing resources from their root, the above can be done by issuing the request:

```py
async def create_upload_session():   
 resp = await client.drives.by_drive_id('driveId').items.by_drive_item_id('root:/{item-path}:').create_upload_session().post()
asyncio.run(create_upload_session())
```

**Comment by samwelkanda** [comment]
Closing as not a blocking issue.
