### ISSUE TITLE
Invalid type expected in ParseNodeFactoryRegistry().get_root_parse_node()

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-sdk-python#401]
The signature `ParseNodeFactoryRegistry().get_root_parse_node(str, BytesIO)` doesn't match what's expected on runtime. The second arg must be `bytes` or the code will fail with a runtime exception.

**Comment by andrueastman** [comment]
@waldekmastykarz Any chance you can confirm if this is still an issue in the latest version of the SDK?

**Comment by waldekmastykarz** [comment]
Seems to be fixed! Thank you!

**Comment by waldekmastykarz** [comment]
When I reloaded VSCode today, the issue is still showing up:

<img width="1313" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-python/assets/11164679/1ae340c8-3942-4c13-90d5-02075ce3db4d">
