### ISSUE TITLE
Failed get Application by `app_id`

### ISSUE THREAD

**Issue by xuzhang3** [microsoftgraph/msgraph-sdk-python#408]
Test code:
```python
._client.applications_with_app_id(app_id=app_id).get()
```

Error mesage:
`
APIError\n        Code: 400\n        message: None\n        error: MainError(additional_data={}, code='Request_BadRequest', details=None, inner_error=InnerError(additional_data={'date': datetime.timedelta(seconds=31956)}, client_request_id='xxxxxxx', date=None, odata_type=None, request_id='xxxxxx'), message=\"Invalid value specified for object reference property 'appId'. Please ensure that this value has an appropriate syntax and length.\", target=None)\n
`

Doc: https://learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=python#example-2-retrieve-an-application-by-its-appid-and-only-specific-properties

**Comment by tgip-work** [comment]
same error

**Comment by xuzhang3** [comment]
@tgip-work I use the list API to get the application with `$filter=appId eq 'xxxxxx'`

https://learn.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=python#example-3-use-filter-and-top-to-get-one-application-with-a-display-name-that-starts-with-a-including-a-count-of-returned-objects

**Comment by samwelkanda** [comment]
Hi @xuzhang3 

Thank you for reporting this issue. This was caused by a mismatch between the path parameter name and the parameter name in the urltemplate. Please update to the latest stable version `v1.0.0` to resolve.

Thanks.
