### ISSUE TITLE
Easily fall back to raw requests

### ISSUE THREAD

**Issue by wryun** [microsoftgraph/msgraph-sdk-python#41]
Because of https://github.com/microsoftgraph/msgraph-sdk-python/issues/40, I think I need to make raw requests. Unfortunately, it's not obvious how to easily fall back to this, as the SDK has a dependency on the 'new' version of msgraph-core which no longer support the old API.

https://github.com/microsoftgraph/msgraph-sdk-python-core/tree/kiota/long-term-branch#6-make-a-requests-to-the-graph

indicates I need to create my own Parsable, which seems more complicated than it should be...

**Comment by samwelkanda** [comment]
Hi @wryun .

Thanks for your interest in trying out our new SDK. Indeed this new SDK is meant to work with the generated models natively. However, we now provide a mechanism to access the native response from the HTTP library if you wish. The process involves passing a `NativeResponseHandler` instance from the abstractions library as a request option in the request configuration. Here's a sample snippet.

```py
# GET ALL MESSAGES FOR A SPECIFIC USER, RETURNING RAW RESPONSE
from kiota_abstractions.native_response_handler import NativeResponseHandler
from kiota_http.middleware.options import ResponseHandlerOption
from msgraph.generated.users.item.messages.messages_request_builder import MessagesRequestBuilder

async def get_user_messages():
        request_config = MessagesRequestBuilder.MessagesRequestBuilderGetRequestConfiguration(
            options=[ResponseHandlerOption(NativeResponseHandler())],
        )
        messages = await client.users_by_id('USER_ID').messages.get(request_configuration=request_config)
        print(messages.json())
asyncio.run(get_user_messages())
```

Please do let us know if your issue persists.

**Comment by dheckl** [comment]
Hi @samwelkanda,

I have tested this with version 1.0.0a9 from pip and it does not work for me. httpx.Request does not know "options". Running your snippet throws following error message:

AttributeError: 'Request' object has no attribute 'options'

**Comment by samwelkanda** [comment]
@dheckl Thanks for trying out our SDK and discovering the issue!

The bug has now been fixed. Kindly update to the latest `msgraph-core` package version `1.0.0a4` to get the changes.

**Comment by wryun** [comment]
@samwelkanda I raised this because I couldn't make a particular request. I'm not working on this any more, but it seems like your response and example code are about raw responses.

**Comment by bigautomata** [comment]
Hi @samwelkanda, many thanks for the fixes. Per https://github.com/microsoftgraph/msgraph-sdk-python/issues/41#issuecomment-1412948103, what is the latest version of msgraph-sdk to use specific, please? That it includes the fixes for this issue.

I've  installed msgraph-sdk-1.0.0.a9 version. Right?

python -m pip install --user msgraph-sdk "what version specific"

I am having this similar problem issue. I would like to try out this fixes.

**Comment by bigautomata** [comment]
> Hi @wryun .
> 
> Thanks for your interest in trying out our new SDK. Indeed this new SDK is meant to work with the generated models natively. However, we now provide a mechanism to access the native response from the HTTP library if you wish. The process involves passing a `NativeResponseHandler` instance from the abstractions library as a request option in the request configuration. Here's a sample snippet.
> 
> ```python
> # GET ALL MESSAGES FOR A SPECIFIC USER, RETURNING RAW RESPONSE
> from kiota_abstractions.native_response_handler import NativeResponseHandler
> from kiota_http.middleware.options import ResponseHandlerOption
> from msgraph.generated.users.item.messages.messages_request_builder import MessagesRequestBuilder
> 
> async def get_user_messages():
>         request_config = MessagesRequestBuilder.MessagesRequestBuilderGetRequestConfiguration(
>             options=[ResponseHandlerOption(NativeResponseHandler())],
>         )
>         messages = await client.users_by_id('USER_ID').messages.get(request_configuration=request_config)
>         print(messages.json())
> asyncio.run(get_user_messages())
> ```
> 
> Please do let us know if your issue persists.

Hi @samwelkanda,

I appreciate for providing the example here. Would help to provide the sample example for the following, please. How to construct the request builder for user? I am struggling to construct it.

For auth provider, I use AzureIdentityAuthenticationProvider by passing it a ClientSecretCredential object.

async def get_user():
    try:
        user = await client.users_by_id('userID').get()
        print(user.user_principal_name, user.display_name, user.id)
    except Exception as e:
        print(f'Error: {e.error.message}')

asyncio.run(get_user())
