### ISSUE TITLE
How to store and use saved token?

### ISSUE THREAD

**Issue by EmreDemircan** [microsoftgraph/msgraph-sdk-python#411]
I want the user to be able to download and upload files to their own OneDrive account through my desktop application. If I use **DeviceCodeCredential**, I can achieve this, but the user has to log in **every time** the program is opened. 

If I use the **SerializableTokenCache** in the **MSAL** library, I can save the generated token to a local text file and read it from there on the next launch, allowing me to successfully authenticate without the need for the user to log in again. However, in this case, I couldn't figure out how to convert this access token into the **client object** in the **'msgraph-sdk-python'** library. In other words, I have an access token, but I couldn't convert it to a **GraphServiceClient(credentials=?, scopes=scopes)** object.

**Comment by samwelkanda** [comment]
Hi @EmreDemircan 

Assuming you already have an AccessToken, here's a snippet of how you can add the token to every request

```py
import asyncio
import httpx
from kiota_abstractions.authentication import AnonymousAuthenticationProvider
from msgraph import GraphRequestAdapter
from msgraph import GraphServiceClient
from msgraph_core import GraphClientFactory

# Create custom  httpx client
# Add the Authorization header with the token to the client headers. This will be used to authenticate every request
headers = {'Authorization': f'Bearer {token}'}
http_client = GraphClientFactory.create_with_default_middleware(client=httpx.AsyncClient(headers=headers))

# Create a request adapter instance passing an anonymous auth provider and the custom client
auth_provider = AnonymousAuthenticationProvider()
request_adapter = GraphRequestAdapter(auth_provider, http_client)

# Create a graph client.
client = GraphServiceClient(request_adapter=request_adapter)

 
# GET ALL USERS IN A TENANT
# HTTP GET /users

async def get_users():
    users = await client.users.get()
    print(users)
    if users and users.value:
        for user in users.value:
            print(user.id, user.display_name, user.mail)
asyncio.run(get_users())
```

I hope that helps.

**Comment by vsoraas** [comment]
I'll piggyback on this as it is weakly related, but let me know if it rather belongs in a separate issue.

Can you convert a MSAL credential to one of the credential-classes Graph uses?
