### ISSUE TITLE
Accessing user's OneDrive using application authentication

### ISSUE THREAD

**Issue by champlin2** [microsoftgraph/msgraph-sdk-python#44]
We have an application that needs to check if a file with a given name exists in OneDrive for a particular user and if so delete it.  I've tried to get the list of drives [self.app_client.drives().get()] using the application authentication flow but getting back an OAuthData error (I can get the list of users using the same GraphServiceClient).  I was wondering a) why the application is not able to get the list of drives and b) once I get the list of drives and see what the path is for the given user can the application impersonate that user so we can check their personal OneDrive for the file and delete it if necessary?  This will have to be done without an interactive login as the application is a daemon process that runs in the background.

If possible a complete code sample would be very helpful.  Appreciate it.

**Comment by champlin2** [comment]
Figured out the problem was with permissions

**Comment by aminhusni** [comment]
> Figured out the problem was with permissions

 I really wish the solution could've been elaborated further :(
