### ISSUE TITLE
msgraph-sdk 1.0.0 fails with Exception of ‘dict’ object has no attribute ‘get_all’  when using request_configuration

### ISSUE THREAD

**Issue by dernstOfExtron** [microsoftgraph/msgraph-sdk-python#444]
When using using request_configuration to make changes to headers, msgraph-sdk 1.0.0 generates an Exception.

The attached example works when using msgraph-sdk16a and earlier, but fails with an Exception of ‘dict’ object has no attribute ‘get_all’ when using msgraph-sdk1.0.0.

Additional output indicated that the Exception may have originated in the kiota_abstractions/headers_collection.py.

 
[SimpleExampleV3.zip](https://github.com/microsoftgraph/msgraph-sdk-python/files/13254880/SimpleExampleV3.zip)

**Comment by samwelkanda** [comment]
Hi @dernstOfExtron 

Thanks for your continued use of the SDK.

This was the last known breaking change to our package prior to GA. We have moved from using a `dict` object for request headers to using a dedicated `HeadersCollection` class.  The new format of adding custom headers to a request looks like so:

```py
request_config = MessagesRequestBuilder.MessagesRequestBuilderGetRequestConfiguration(
    )
    request_config.headers.add("prefer", "outlook.body-content-type=text")
``` 
Also check our updated samples on the same: https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/docs/general_samples.md#5-passing-custom-request-headers

**Comment by RobertPaulson90** [comment]
Hi @samwelkanda I spent way too long trying to fix this than I'm willing to admit. Please update your automatically generated code on the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) because it generates code that fails like the OP describes.

**Comment by RobertPaulson90** [comment]
Actually I have no way to figure this out. How do I get working code show me the service principals that are member of a group?

If I do it without ConsistencyLevel they are hidden. If I try to add it, the code just fails

```python
request_configuration = MembersRequestBuilder.MembersRequestBuilderGetRequestConfiguration()
request_configuration.headers.add('ConsistencyLevel', 'eventual')

result = await self.graph_client.groups.by_group_id(group_id).members.get(request_configuration=request_configuration)
for member in result:
    print(member)
```

How do I add count=True to `MembersRequestBuilder.MembersRequestBuilderGetQueryParameters` ?
