### ISSUE TITLE
Getting DriveItems under a folder

### ISSUE THREAD

**Issue by champlin2** [microsoftgraph/msgraph-sdk-python#46]
I am able to get the DriveItems in the root of a user's OneDrive using the following:

`children = await self.app_client.drives_by_id(drive.id).root().children().get()`

And then I loop through the returned DriveItems and want to then get the items inside one of the folders but can't seem to get it to execute a GET to /drives/{drive-id}/items/{item-id}/children (which is in the url_template in the children_request_builder).  I've tried the following with no luck:

`children = await self.app_client.drives_by_id(drive.id).items_by_id(driveItem.id).children().get()`

Would love some sample code if anyone has it along with which generated imports to pull in.

**Comment by champlin2** [comment]
I tried changing the second call to 

`children = await self.app_client.drives_by_id(drive.id).bundles_by_id(driveItem.id).children().get()`

since it returns a DriveItemItemRequestBuilder which I could then call the children() property on but it seems the Kiota generated code has multiple assignments for drive_item_item_request_builder at the top of msgraph.generated.drives.item.drive_item_request_builder.py the last one which points to msgraph.generated.drives.item.special.item.drive_item_item_request_builder which doesn't have a children() property so the call doesn't work.  Not sure why there are multiple assignments to different locations of the drive_item_item_request_builder in this file.  I believe the 'special' one is the only one that is used since it is defined last.

**Comment by champlin2** [comment]
@samwelkanda I verified that if I comment out this line

`drive_item_item_request_builder = lazy_import('msgraph.generated.drives.item.special.item.drive_item_item_request_builder')`

in msgraph.generated.drives.item.drive_item_request_builder.py leaving the last definition of drive_item_request_builder to be

`drive_item_item_request_builder = lazy_import('msgraph.generated.drives.item.items.item.drive_item_item_request_builder')`

it seems to work fine and find the DriveItems under the top level DriveItem folder. 

Can you verify that there should only be the one lazy_import for drive_item_request_builder in the file and it should be for the one under items (so bundles, following and special should not be in there)?  And if that is the case any idea on timeframe for a new version that I can upgrade to with pip that would have the fix?

**Comment by champlin2** [comment]
@samwelkanda any update on this?

**Comment by jignesh-crest** [comment]
Hey, @samwelkanda are you working on this issue? 
If you don't have the bandwidth let me know I'll work on it and raise a PR.

**Comment by samwelkanda** [comment]
Hi @jignesh-crest, thanks for your continued interest in our SDK.

Yes we are. We have already identified the cause, which is a variable naming conflict, based on the last segment of the import path. We're implementing a fix to make the variable names unique, and expect the changes in by early next week.

**Comment by champlin2** [comment]
@samwelkanda any ETA on a fix?

**Comment by champlin2** [comment]
@samwelkanda @baywet What release of msgraph-sdk will this be fixed in and when will that be available?
