### ISSUE TITLE
Failed get application with `$filter`

### ISSUE THREAD

**Issue by xuzhang3** [microsoftgraph/msgraph-sdk-python#466]
Failed get application with `$filter`
API: `https://graph.microsoft.com/v1.0/applications?$filter=identifierUris/any(s:s eq 'xxxxxxxx')`
```log
'dict' object has no attribute 'get_all'

  File "/xxx/lib/python3.10/site-packages/msgraph/generated/applications/applications_request_builder.py", line 105, in to_get_request_information
    request_info.headers.add_all(request_configuration.headers)
  File "/xxx/lib/python3.10/site-packages/kiota_abstractions/headers_collection.py", line 83, in add_all
    for key, values in headers.get_all().items():
```

**Comment by isvargasmsft** [comment]
CC: @samwelkanda @shemogumbe

**Comment by xPancakery** [comment]
Any updates on this? I am also getting this issue when using the azure.azcollection ansible module

**Comment by A360-Paul** [comment]
This looks related to [issue 451](https://github.com/microsoftgraph/msgraph-sdk-python/issues/451)

My comment might apply.
Basically your setting a dict where its expecting the "HeaderColleciton" class.
Use the request_configuration.headers.try_add('HEADERKEY','HEADERVALUE') instead

**Comment by xuzhang3** [comment]
Thanks @A360-Paul pointing me.  The error  was I misadd the headers which was supported by the preview SDK.  The headers was deleted in  the `v1.0.0`

```python
request_configuration = ApplicationsRequestBuilder.ApplicationsRequestBuilderGetRequestConfiguration(
                query_parameters=ApplicationsRequestBuilder.ApplicationsRequestBuilderGetQueryParameters(
                    filter=(' and '.join(sub_filters)),
                ),
            headers={'ConsistencyLevel': "eventual"}, # not supported in v1.0.0
            )
            return await self._client.applications.get(request_configuration=request_configuration)
```

**Comment by A360-Paul** [comment]
Awesome - Happy to be of assistance.
The headers might still be needed though. We should be setting them using the new 'HeaderCollection' class and not a dict. Overwriting the 'HeaderCollection' object with a dict leads to the error. The documentation needs updating.

The following should still work and keep your headers as you wanted:
```
    request_configuration = ApplicationsRequestBuilder.ApplicationsRequestBuilderGetRequestConfiguration(
        query_parameters=ApplicationsRequestBuilder.ApplicationsRequestBuilderGetQueryParameters(
            filter=(' and '.join(sub_filters)),
        )
    )
    request_configuration.headers.try_add('ConsistencyLevel','eventual') #sets the same header as before but using object
return await self._client.applications.get(request_configuration=request_configuration)
```
