### ISSUE TITLE
Can't import `IdentitySet`, `Identity` and `Permission` 

### ISSUE THREAD

**Issue by nikolic-milan** [microsoftgraph/msgraph-sdk-python#470]
Greetings,

I am trying to implement the fallowing https://devblogs.microsoft.com/microsoft365dev/controlling-app-access-on-specific-sharepoint-site-collections/ . So I'm basically writing a script that will grand an app access to a specific SharePoint page. To di this I am using the fallowing example provided by Microsoft at https://learn.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&tabs=python 
```graph_client = GraphServiceClient(credentials, scopes)

request_body = Permission(
	roles = [
		"write",
	],
	granted_to_identities = [
		IdentitySet(
			application = Identity(
				id = "89ea5c94-7736-4e25-95ad-3fa95f62b66e",
				display_name = "Contoso Time Manager App",
			),
		),
	],
)

result = await graph_client.sites.by_site_id('site-id').permissions.post(request_body)
```

The Issues is that I can't find from which module to import `IdentitySet`, `Identity` and `Permission`. Can anyone help with this?
I tried `msgraph.models`, `msgraph.generated.models`, `msgraph`, `msgraph_core`. I can't seem to find any documentation anywhere listing all modules.

Thanks in advance!

**Comment by andrueastman** [comment]
Thanks for raising this @nikolic-milan 

The python snippets now have import statements in them. https://learn.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&tabs=python

Any chance you can confirm if this is helpful in your scenario?
