### ISSUE TITLE
[Feature request] Remove user from group

### ISSUE THREAD

**Issue by teemuij** [microsoftgraph/msgraph-sdk-python#477]
Adding a user to a group works with the following code
```
request_body = ReferenceCreate(odata_id=f"https://graph.microsoft.com/v1.0/directoryObjects/{user.id}")
await graph_client.groups.by_group_id(group_id).members.ref.post(request_body)
```

It would make sense to add a remove user feature which would probably look something like this
```
request_body = ReferenceCreate(odata_id=f"https://graph.microsoft.com/v1.0/directoryObjects/{user.id}")
await graph_client.groups.by_group_id(group_id).members.ref.delete(request_body)
```

**Comment by andrueastman** [comment]
Thanks for raising this @teemu47 

Any chance the documentation at the link below is helpful? 
https://learn.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=python

**Comment by teemuij** [comment]
> Thanks for raising this @teemu47
> 
> Any chance the documentation at the link below is helpful? https://learn.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=python

Ah, that looks like exactly what I was looking for, thanks.
