### ISSUE TITLE
Installation fails due to Windows MAX_PATH lenght

### ISSUE THREAD

**Issue by tb-tech** [microsoftgraph/msgraph-sdk-python#48]
obviously this library ends up with a very long path. in case you cannot change the MAX_PATH in windows registry or group policy, you will not be able to install the package.

Lib\\site-packages\\msgraph\\generated\\groups\\item\\drives\\item\\items\\item\\get_activities_by_interval_with_start_date_time_with_end_date_time_with_interval\\get_activities_by_interval_with_start_date_time_with_end_date_time_with_interval_request_builder.py

edit: sorry, was in the wrong repo. can anyone move it to pyton issue list? https://github.com/microsoftgraph/msgraph-sdk-python/issues

**Comment by samwelkanda** [comment]
Hi @tb-tech 

Thanks for your interest in trying out our SDK. 

As you mentioned, this is an expected issue with the library, owing the generated file names depending on the depth of paths in the Microsoft Graph API. We are exploring ways to trim the file names, but do not have a definite fix for now. This means you'll have to modify the `MAX_PATH` to allow long file names if you want to use the SDK.

We'll provide an update once we have a working solution to the problem.
Thanks.
