### ISSUE TITLE
[Feature request] Allow retrieving pages of Sharepoint site (beta API)

### ISSUE THREAD

**Issue by dabla** [microsoftgraph/msgraph-sdk-python#492]
Hello, we're now migrating to the msgraph-sdk-python library.  Until now we used our own python based MS Graph Client.

I already succeeded retrieving sharepoint sites using the msgraph-sdk-python library, but I've looked through the source code and I saw that pages associated to a sharepoint site is not availabe in the msgraph-sdk-python library.

With our custom implementation we could retrieve pages associated to a sharepoint site like this with the api:

        site = client.sites("accinfrabel.sharepoint.com").relative_path("sites/news")
        pages = site.pages()

I now how the endpoint should be invoked, I'm also willing to contribute but from what I understand the api is generated here.  So how could we add this feature?

Bellow the code we used to get the pages from a sharepoint site:

`self._get(f"/sites/{self.site_id}/pages", api_version="beta")`

**Comment by dabla** [comment]
I've implemented the feature myself and it works.  I have also added integration tests but that would mean that we need a test tenant_id/client_id/client_secret so that we can test the client.  I've used on my side a Microsoft 365 developer account for that.  Of course I cannot use my credentials here, so question is, how do we proceed here?  I would be nice to have some integration tests which get validated automatically in Github QA actions.

I've added following method in the site_item_request_builder module:

        def page(self, page_id: str) -> SitePageRequestBuilder:
                """
                Provides operations to manage the collection of site page entities.
                param site_id: The unique identifier of site
                Returns: SitePageRequestBuilder
                """
                from ..page.site_page_request_builder import SitePageRequestBuilder

                url_tpl_params = get_path_parameters(self.path_parameters)
                url_tpl_params["page%2Did"] = page_id
                request_adapter = copy.copy(self.request_adapter)  # clone original request adapter
                request_adapter.base_url = "https://graph.microsoft.com/beta" # change the base_url to beta
                return SitePageRequestBuilder(request_adapter, url_tpl_params)

This is the contructor of the SitePageRequestBuilder:

    class SitePageRequestBuilder(BaseRequestBuilder):
        """
        Provides operations to manage the collection of site entities.
        """
        def __init__(self,request_adapter: RequestAdapter, path_parameters: Optional[Union[Dict[str, Any], str]] = None) -> None:
            """
            Instantiates a new SiteItemRequestBuilder and sets the default values.
            param path_parameters: The raw url or the Url template parameters for the request.
            param request_adapter: The request adapter to use to execute the requests.
            Returns: None
            """
            super().__init__(request_adapter, "{+baseurl}/sites/{site%2Did}/pages/{page%2Did}", path_parameters)

**Comment by dabla** [comment]
The changes I made can be viewed in our fork: https://github.com/microsoftgraph/msgraph-sdk-python/compare/main...infrabel:msgraph-sdk-python:feature/site-with-pages-from-beta-api

**Comment by dabla** [comment]
I've also refactored BaseCollectionPaginationCountResponse so it also already contains the value field and has all method fully implemented so we can avoid copy pasting everything across all different implementations for each collection type.  To do so I made it generic:

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, TypeVar, Generic

from kiota_abstractions.serialization import AdditionalDataHolder, Parsable, ParseNode, SerializationWriter
from kiota_abstractions.store import BackedModel, BackingStore, BackingStoreFactorySingleton

from generated.models.entity import Entity

T = TypeVar('T', bound=Entity)


    @dataclass
    class BaseCollectionPaginationCountResponse(AdditionalDataHolder, BackedModel, Parsable, Generic[T]):
        # Stores the generic type so it can be used in the get_field_deserializers method
        entity: T = field(default=Entity)
        # Stores model information.
        backing_store: BackingStore =     field(default_factory=BackingStoreFactorySingleton(backing_store_factory=None).backing_store_factory.create_backing_store, repr=False)

        # Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
        additional_data: Dict[str, Any] = field(default_factory=dict)
        # The OdataCount property
        odata_count: Optional[int] = None
        # The OdataNextLink property
        odata_next_link: Optional[str] = None
        value: Optional[List[T]] = None
    
        @classmethod
        def create_from_discriminator_value(cls, parse_node: Optional[ParseNode] = None) ->     BaseCollectionPaginationCountResponse:
            """
            Creates a new instance of the appropriate class based on discriminator value
            param parse_node: The parse node to use to read the discriminator value and create the object
            Returns: BaseCollectionPaginationCountResponse
            """
            if not parse_node:
                raise TypeError("parse_node cannot be null.")
            return cls()
    
        def get_field_deserializers(self,) -> Dict[str, Callable[[ParseNode], None]]:
            """
            The deserialization information for the current model
            Returns: Dict[str, Callable[[ParseNode], None]]
            """
            fields: Dict[str, Callable[[Any], None]] = {
                "@odata.count": lambda n : setattr(self, 'odata_count', n.get_int_value()),
                "@odata.nextLink": lambda n : setattr(self, 'odata_next_link', n.get_str_value()),
                "value": lambda n: setattr(self, 'value', n.get_collection_of_object_values(self.entity)),
            }
            return fields
    
        def serialize(self,writer: SerializationWriter) -> None:
            """
            Serializes information the current object
            param writer: Serialization writer to use to serialize this model
            Returns: None
            """
            if not writer:
                raise TypeError("writer cannot be null.")
            writer.write_int_value("@odata.count", self.odata_count)
            writer.write_str_value("@odata.nextLink", self.odata_next_link)
            writer.write_collection_of_object_values("value", self.value)
            writer.write_additional_data_value(self.additional_data)

Now you just have to write this little to define a typed collection:

    @dataclass
    class UserCollectionResponse(BaseCollectionPaginationCountResponse[User]):
        def __init__(self):
            super().__init__(entity=User)

**Comment by dabla** [comment]
Continued refactoring on the BaseCollectionPaginationCountResponse, now pagination is handled for you using an async iterable implementation.

    from __future__ import annotations

    from dataclasses import dataclass, field
    from typing import Any, Callable, Dict, List, Optional, TypeVar, Generic

    from kiota_abstractions.method import Method
    from kiota_abstractions.request_adapter import RequestAdapter
    from kiota_abstractions.request_information import RequestInformation
    from kiota_abstractions.serialization import AdditionalDataHolder, Parsable, ParseNode, SerializationWriter, \
    ParsableFactory
    from kiota_abstractions.store import BackedModel, BackingStore, BackingStoreFactorySingleton

    from generated.models.entity import Entity
    from generated.models.o_data_errors.o_data_error import ODataError

    T = TypeVar('T', bound=Entity)


    @dataclass
    class BaseCollectionPaginationResponse(AdditionalDataHolder, BackedModel, Parsable, Generic[T]):
        # Stores the request adapter used for paging when an odata_next_link is available
        request_adapter: RequestAdapter = field(default=None, repr=False)
        # Stores the generic type so it can be used in the get_field_deserializers method
        entity: T = field(default=Entity)
        # Stores model information.
        backing_store: BackingStore =    field(default_factory=BackingStoreFactorySingleton(backing_store_factory=None).backing_store_factory.create_backing_store, repr=False)

        # The OdataNextLink property
        odata_next_link: Optional[str] = None
        value: Optional[List[T]] = None

        @classmethod
        def create_from_discriminator_value(cls, parse_node: Optional[ParseNode] = None) ->    BaseCollectionPaginationResponse:
            """
            Creates a new instance of the appropriate class based on discriminator value
            param parse_node: The parse node to use to read the discriminator value and create the object
            Returns: BaseCollectionPaginationCountResponse
            """
            if not parse_node:
                raise TypeError("parse_node cannot be null.")
            return cls()
    
        def get_field_deserializers(self,) -> Dict[str, Callable[[ParseNode], None]]:
            """
            The deserialization information for the current model
            Returns: Dict[str, Callable[[ParseNode], None]]
            """
            fields: Dict[str, Callable[[Any], None]] = {
                "@odata.nextLink": lambda n : setattr(self, 'odata_next_link', n.get_str_value()),
                "value": lambda n: setattr(self, 'value', n.get_collection_of_object_values(self.entity)),
            }
            return fields
    
        def serialize(self,writer: SerializationWriter) -> None:
            """
            Serializes information the current object
            param writer: Serialization writer to use to serialize this model
            Returns: None
            """
            if not writer:
                raise TypeError("writer cannot be null.")
            writer.write_str_value("@odata.nextLink", self.odata_next_link)
            writer.write_collection_of_object_values("value", self.value)
            writer.write_additional_data_value(self.additional_data)

        def request_information(self, method: Method = Method.GET) -> RequestInformation:
            request_info = RequestInformation()
            request_info.url = self.odata_next_link
            request_info.http_method = method
            request_info.headers.try_add("Accept", "application/json;q=1")
            return request_info

        async def __anext__(self):
            if not self.value:
                raise StopAsyncIteration

            try:
                return self.value
            finally:
                if self.odata_next_link:
                    error_mapping: Dict[str, ParsableFactory] = {
                        "4XX": ODataError,
                        "5XX": ODataError,
                    }
                    result = await BaseCollectionPaginationResponse.request_adapter.send_async(
                        request_info=self.request_information(),
                        parsable_factory=type(self),
                        error_map=error_mapping
                    )
                    self.value = result.value
                    self.additional_data = result.additional_data
                    self.odata_next_link = result.odata_next_link
                else:
                    self.value = None

        def __aiter__(self):
            return self

**Comment by baywet** [comment]
Hi @dabla 
I'm only seeing this now, sorry about that (Python is not my primary assignment)
Have you tried [using the beta SDK](https://github.com/microsoftgraph/msgraph-beta-sdk-python) to access this beta API?

**Comment by paulschmeida** [comment]
Beta SDK seems to be on the exact same version as this one and doesn't contain methods to retrieve a sharepoint site by relative path, even though it's possible in the REST API. This means we have to resort to using search and then verifying the results to get the site id and proceeding from that. 
It would be much, much better if we could access resources by their relative paths, not just for sites but for other resources that support it.

**Comment by baywet** [comment]
@paulschmeida can you point to the documentation page of the API you're referring to please?

If you're talking about the pages API, this should be [already supported in beta](https://github.com/microsoftgraph/msgraph-beta-sdk-python/tree/main/msgraph_beta/generated/sites/item/pages)

a call similar to this one (with the beta library) should retrieve the pages

```python
client.sites("accinfrabel.sharepoint.com:/sites/news").pages.get()
```

**Comment by dabla** [comment]
@baywet thank you for the above example, indeed the beta SDK has the pages available, I didn't find it the first time.  Also good to see we can retrieve the pages through relative path, I will try that and keep you posted.

**Comment by dabla** [comment]
> @paulschmeida can you point to the documentation page of the API you're referring to please?
> 
> If you're talking about the pages API, this should be [already supported in beta](https://github.com/microsoftgraph/msgraph-beta-sdk-python/tree/main/msgraph_beta/generated/sites/item/pages)
> 
> a call similar to this one (with the beta library) should retrieve the pages
> 
> ```python
> client.sites("accinfrabel.sharepoint.com:/sites/news").pages.get()
> ```

The example above doesn't work, but this one does:

    site = client.sites.by_site_id('accinfrabel.sharepoint.com:/sites/news').get()

At least I can find a site from its relative url, but still not able to get the pages though from there.  I have to do it in 2 steps.
First the above one to get the site_id from its relative path, and then once we have the site_id we can do following call:

    pages = self.client.sites.by_site_id(site.id).pages.get()

I've tried doing it in one call but it doesn't work:

    pages = client.sites.by_site_id('accinfrabel.sharepoint.com:/sites/news').pages.get()

I will update the documentation, also regarding the proxy configuration cause that's also a bit tricky, and once documentation is updated I will do a pull request.

**Comment by baywet** [comment]
Thanks for the additional context. The fact the call isn't supported in a single call is due to the service implementation, and not the client SDK here. You could [post on the dedicated Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/tags/274/microsoft-graph-files-api/) to get attention from the service team on that issue.

**Comment by paulschmeida** [comment]
@baywet so I was mostly after the option to get a sharepoint site by it's path or relative path and ideally get the drive. I didn't know you get use .by_site_id() with an identifier like this - `site = client.sites.by_site_id('accinfrabel.sharepoint.com:/sites/news').get()`. This works for retrieving the site, but if I modify it to get the drive - `site = client.sites.by_site_id('accinfrabel.sharepoint.com:/sites/news').drive.get()`, it fails. If I call the same method but you the actual id for the same site, it works and retrieves the drive.

I have also commented on another bug report about the getting the relative paths - #279 
I was trying to chain methods like this to get the site:
```
await (
    client.sites.by_site_id("uhsnhs.sharepoint.com")
    .get_by_path_with_path("/sites/ResearchDataSciencesBRCProjectUnit")
    .get()
)
```
