### ISSUE TITLE
msgraph-sdk pendulum dependency doesn't build on Python 3.12

### ISSUE THREAD

**Issue by miketheitguy** [microsoftgraph/msgraph-sdk-python#499]
Please see https://github.com/microsoftgraph/msgraph-sdk-python/issues/467. I'm unsure why this issue was closed, but to add more clarity from my end.

`      Traceback (most recent call last):
        File "C:\Users\mike\AppData\Local\Temp\pip-install-c0prgg71\pendulum_c7e379bfe6e94ee199f93ca3d734efad\build.py", line 5, in <module>
          from distutils.command.build_ext import build_ext
      ModuleNotFoundError: No module named 'distutils'
      Traceback (most recent call last):`

Python 3.12 no longer includes distutils: https://docs.python.org/3.10/library/distutils.html

**Comment by miketheitguy** [comment]
Discussion in Pendulum is here https://github.com/sdispater/pendulum/issues/696

Appears 3.0.0b1 resolves the issue.

**Comment by andrueastman** [comment]
@miketheitguy Any chance you can confirm this is fixed in the latest version of the SDK?
