### ISSUE TITLE
Getting "kiota_http._exceptions.RedirectError: Too many redirects. []" Error

### ISSUE THREAD

**Issue by Luki2003** [microsoftgraph/msgraph-sdk-python#504]
I am trying to download all pptx files from a OneDrive folder as pdf files. To do this, all pptx files are first saved with file name and id in a dictionary. Then the contents are downloaded via a for loop. This works up to the 5th element. From the 6th element I get the error: "kiota_http._exceptions.RedirectError: Too many redirects. []"

Here is my code:
```Python
for file_name, file_id in files.items():
      loop.run_until_complete(convert_and_download_file_content(client, drive_id, file_id, file_name))
```
```Python
async def convert_and_download_file_content(_graph_client: GraphServiceClient, _drive_id: str, _file_id: str, _filename: str) -> None:
    content: bytes | None = await _graph_client.drives.by_drive_id('drive-id').items.by_drive_item_id('driveItem-id').content.with_url(f'https://graph.microsoft.com/v1.0/drives/{_drive_id}/items/{_file_id}/content?format=pdf').get()
    if content is None:
        raise ValueError("Content is None!")

    with open(f"./pdf-files/{_filename}", "wb") as file:
        file.write(content)

    print(f"Downloaded {_filename}!")
```

**Comment by snorrea** [comment]
I am facing this exact issue, and the lack of a workaround is a major blocker for my current project. Have you had any luck circumventing it? This has also been reported in the underlying `kiota-http-python` module [here](https://github.com/microsoft/kiota-http-python/issues/246), and there seems to be a PR in progress to address it [here](https://github.com/microsoft/kiota-http-python/pull/258). Once the fix is merged, though, I reckon the `kiota-http-python` version used by `msgraph` must also be bumped. I don't know how long that'll take...

**Comment by Luki2003** [comment]
I have found a workaround for the problem. You can generate an access token and then use the Requests module for this.

```Python
def authenticate(_client_id: str, _tenant_id: str, _scopes: list[str]) -> tuple[GraphServiceClient, str]:
    credential: DeviceCodeCredential = DeviceCodeCredential(client_id=_client_id, tenant_id=_tenant_id)
    token: AccessToken = credential.get_token("User.Read", "Files.Read")
    graph_client: GraphServiceClient = GraphServiceClient(credentials=credential, scopes=_scopes)
    return graph_client, token.token
```
```Python
headers = {
        "Authorization": "Bearer " + access_token,
        "Content-Type": "application/json",
    }

url: str = f'https://graph.microsoft.com/v1.0/drives/{drive_id}/items/{file_id}/content?format=pdf'

response: Response = requests.get(url, headers=headers)
```

**Comment by tpcgold** [comment]
this is a big issue with the sdk. (one of many) 
one solution: the old msgraph-core versions don't seem to have this issue

**Comment by samwelkanda** [comment]
Resolved in https://github.com/microsoft/kiota-http-python/pull/258

Please update to the latest `microsoft-kiota-http` package
