### ISSUE TITLE
GA Plans for Python SDK

### ISSUE THREAD

**Issue by jreinhardtproarch** [microsoftgraph/msgraph-sdk-python#512]
I am considering possible production scenarios for the Graph Python SDK. It's been out in public preview for a year. Is there any public acknowledgement of when it will go to general availability? I haven't been able to find anything so I'm posting an issue here for feedback. Thank you.

**Comment by baywet** [comment]
Hi @jreinhardtproarch 
Thanks for reaching out.
This SDK [has been in GA since Nov 1st](https://devblogs.microsoft.com/microsoft365dev/introducing-the-microsoft-graph-python-sdk/) and is ready for production use.
Closing.
