### ISSUE TITLE
adding filters with ApplicationsRequestBuilderGetQueryParameters() doesn't work as expected

### ISSUE THREAD

**Issue by luojunh** [microsoftgraph/msgraph-sdk-python#524]
Hi team,

when using  ApplicationsRequestBuilderGetQueryParameters() to add filters for the query, can get the data, but the filters didn't work, additional unexpected data return as well.

code:

credential = ClientSecretCredential(
tenant_id=tenant_id,
client_id=client_id,
client_secret=client_secret
)
graph_client = GraphServiceClient(credentials=credential, scopes=scope)
//========== Filter and get SP ==========
query_params = graph_client.applications.ApplicationsRequestBuilderGetQueryParameters(
filter = 'startswith(displayName, 'ca-in')',
select = ['id','appId','displayName','keyCredentials','passwordCredentials']
)
request_configuration = graph_client.applications.ApplicationsRequestBuilderGetRequestConfiguration(
query_parameters=query_params
)

result = await graph_client.applications.get(request_configuration = request_configuration)
print(result)

https://learn.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=python#code-try-31

response

{

  "backing_store": {

    "_InMemoryBackingStore__subscriptions": {},

    "_InMemoryBackingStore__store": {

      "additional_data": [

        false,

        {

          "@odata.context": "[https://graph.microsoft.com/v1.0/$metadata#applications(id,appId,displayName,requiredResourceAccess)/$entity"](https://graph.microsoft.com/v1.0/$metadata#applications(id,appId,displayName,requiredResourceAccess)/$entity%22)

        }

      ],

      "id": [

        false,

        "47c508fa-288b-44d2-928d-a37d7cac9bdc"

      ],

      "odata_type": [

        false,

        "#microsoft.graph.application"

      ],

      "deleted_date_time": [

        false,

        null

      ],

      "add_ins": [

        false,

        null

      ],

      "api": [

        false,

        null

      ],

      "app_id": [

        false,

        "df73862b-d836-4a03-a3a8-8d105fef5aa9"

      ],

      "app_management_policies": [

        false,

        null

      ],

      "app_roles": [

        false,

        null

      ],

      "application_template_id": [

        false,

        null

      ],

      "certification": [

        false,

        null

      ],

      "created_date_time": [

        false,

        null

      ],

**Comment by andrueastman** [comment]
@luojunh Any chance you can confirm if this is still an issue on the latest version of the SDK?
