### ISSUE TITLE
How to implement ResponseHandler

### ISSUE THREAD

**Issue by champlin2** [microsoftgraph/msgraph-sdk-python#54]
I have an application that has to issue multiple requests to verify some items are located on OneDrive under certain folders for multiple items which causes a 429 (too many requests) response.  According to the documentation (https://devblogs.microsoft.com/microsoft365dev/introducing-the-microsoft-graph-python-sdk-now-available-for-public-preview/#built-in-retry-handler) there is a built-in retry handler that will read the Retry-After header from the response and handle the waiting.  I guess this would be passed to the get() call but I can't find anywhere that describes how to do this.  Any chance you can post an example of how to do that?

**Comment by champlin2** [comment]
Seems like the default handler was being called it just didn't wait long enough inbetween retries or retry enough times so I had to create a CustomGraphRequestAdapter to pass down the number of retries and wait that I wanted to use.

**Comment by WardenHub** [comment]
Thanks for this, helped my solve my own 429 issue. (basically added a time.sleep() command to it.
