### ISSUE TITLE
problem running sample code - and feedback

### ISSUE THREAD

**Issue by pauljstuart** [microsoftgraph/msgraph-sdk-python#549]
hello.  I'm trying to get the msgraph-sdk to work.  I have been working with the http interface for a while, so I understand well how the API is supposed to work.  I downloaded the msgraph-sdk cause I thought it would make development significantly easier, but so far that hasn't been the case.  I have some questions and feedback, but first the problem.

I setup this small code block based on your example code.  All I'm trying to do is to read the members of a AD group - that's it.

### my code 
```
import sys
import logging
import requests
import json
import asyncio

#from azure.identity.aio import ClientSecretCredential
from azure.identity import ClientSecretCredential
from msgraph import GraphServiceClient

SP_CLIENT_ID='XXXXX'
SP_TENANT_ID='YYYYY'
SP_SECRET='ZZZZZZZZZZZZ'  
ms_authority = 'https://login.microsoftonline.com'
token_scope='https://graph.microsoft.com/.default'
base_url =  'https://graph.microsoft.com'  

credential = ClientSecretCredential(SP_TENANT_ID,
                                    SP_CLIENT_ID,
                                    SP_SECRET)


scopes = ['https://graph.microsoft.com/.default']

client = GraphServiceClient(credentials=credential, scopes=scopes)

group_id = '735b750a-835b-4234-83e7-57c3b8be88cc'
    

async def get_group_members(): 
    members = await client.groups.by_group_id(group_id).members.get()
    if members and members.value:
        for member in members.value:
            user = await client.users.by_user_id(member.id).get()
            if user:
                print(user.display_name, user.mail)
asyncio.run(get_group_members())
```

When I run this block - inside Databricks - I get the following error :

RuntimeError: asyncio.run() cannot be called from a running event loop

Any ideas what might cause that?

### Feedback 

Can you please explain to me why all of the sample code for the msgraph-sdk uses the asyncio libraries?

Is there no way to run the sdk in a simple way without asyncio?  I've spent quite some time trying to prise the function calls from asyncio without success.   

I understand that asyncio gives a degree of resilience, but what if I don't want that?  i spent ages looking in  your repo and on the internet but I don't see suggestions on how to use it without asyncio.  And as noted, for me it doesn't work, at least in Databricks.

**Comment by jh0274** [comment]
hey! 

Databricks uses an event loop itself (also utilising asyncio i think).  So you need to install 'nest_asyncio' ...

then:
  import next_asyncio
  import asyncio
  nest_asyncio.apply()

instead of just:
  import asyncio

wherever you want to use it.

**Comment by fey101** [comment]
Hi @pauljstuart. If Databricks uses an event loop itself and you call `asyncio.run`, you try to create another event loop within an already existing event loop started in Databricks. Hence the error. Try using an `await` call instead of the `asyncio.run` or use `nest_asyncio` and let us know if the problem still persists.

```
...
async def get_group_members(): 
    members = await client.groups.by_group_id(group_id).members.get()
    if members and members.value:
       ...
await (get_group_members())
```

Also note that at the moment, there's no way to run the graph sdks without asyncio.

**Comment by pauljstuart** [comment]
Great, thank you!
