### ISSUE TITLE
__path__ attribute not found on 'msgraph.generated.models.security'

### ISSUE THREAD

**Issue by Wwwolfgang** [microsoftgraph/msgraph-sdk-python#55]
I'm trying to use this sdk in a Django/Wagtail project. 
Version: I installed the current version wich is 1.0.0a4 I believe.

It gets imported fast but if I import
`from msgraph import GraphRequestAdapter, GraphServiceClient`

I always get this error:
`__path__ attribute not found on 'msgraph.generated.models.security' while trying to find 'msgraph.generated.models.security.cases_root'`

I tried using an older version like 1.0.0a3 but than the import is very slow. Loading a project takes multiple minutes.
Any idea what is happening?

**Comment by Wwwolfgang** [comment]
I saw on pypi that there is a new version from this library, version 1.0.0a7 to be specific. So I tried it in my project, but the problem and error message still remains.

**Comment by samwelkanda** [comment]
Hi @Wwwolfgang 

Thanks for trying out our library. I was able to repro the above issue on Django and it has now been fixed. Kindly install the latest version of our SDK to get the latest changes.

Feel free to re-open this issue if the problem persists.

Thanks!
