### ISSUE TITLE
Parse negative offsets

### ISSUE THREAD

**Issue by draew6** [microsoftgraph/msgraph-sdk-python#552]
I am not able to use MSGraph Bookings API properly because of this error on many responses:
`
 Error: Unable to parse string [-PT15M]
`

This one is "List Services"
https://learn.microsoft.com/en-gb/graph/api/bookingbusiness-list-services?view=graph-rest-1.0&tabs=http
which is business.services.get() in python sdk
for this default notification:
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/73714196/b822bd2d-da7a-4705-8a7a-502f472d8323)

Another one is response when creating appointment. There is probably more of them.

**Comment by andrueastman** [comment]
Thanks for raising this @draew6 

Any chance you can confirm if this is still an issue for you in the latest version of the SDK?

**Comment by jaclar** [comment]
I can confirm that this bug is still available in the current version 1.5.2

```
pendulum.parsing.exceptions.ParserError: Unable to parse string [-PT15M]
```

**Comment by jeffswanvalla** [comment]
Still an issue in 1.5.3, e.g. listServices fails to parse response with same error

**Comment by shemogumbe** [comment]
Hello @draew6 we have recently made some changes in https://github.com/microsoft/kiota-serialization-json-python.

Could you kindly confirm if this is still an issue?

**Comment by draew6** [comment]
> Hello @draew6 we have recently made some changes in https://github.com/microsoft/kiota-serialization-json-python.
> 
> Could you kindly confirm if this is still an issue?

Hello, I can't. I am no longer working on that project/job, sorry.

**Comment by shemogumbe** [comment]
Resolved
