### ISSUE TITLE
How do we iterate next set of 100 rows

### ISSUE THREAD

**Issue by sujaywork** [microsoftgraph/msgraph-sdk-python#555]
Using the Python APIs it only fetches 100 rows max, however the odata_next_link has a URL what's the best way to fetch the next set of rows and keep track of the offset? It doesn't make sense to use the Python SDK for the initial 100 rows then switch to HTTPS calls for the next 100. Is there something in the SDK itself?

**Comment by sujaywork** [comment]
This issue seems to be open from last year https://github.com/microsoftgraph/msgraph-sdk-python/issues/105

**Comment by jussihi** [comment]
Hey @sujaywork , You can always use the `with_url` 

For example with user's calendar events, first create a normal initial request:
```python
result: Optional[EventCollectionResponse] = await graph_client.users.by_user_id(mailbox).calendar.calendar_view.get(request_configuration = request_configuration)
```

Then subsequent queries with `odata.nextlink` in `with_url`:
```python
while result is not None and result.odata_next_link is not None:
  result: Optional[EventCollectionResponse] = await graph_client.users.by_user_id(mailbox).calendar.calendar_view.with_url(result.odata_next_link).get(request_configuration = request_configuration)
```

**Comment by sujaywork** [comment]
> Hey @sujaywork , You can always use the `with_url`
> 
> For example with user's calendar events, first create a normal initial request:
> 
> ```python
> result: Optional[EventCollectionResponse] = await graph_client.users.by_user_id(mailbox).calendar.calendar_view.get(request_configuration = request_configuration)
> ```
> 
> Then subsequent queries with `odata.nextlink` in `with_url`:
> 
> ```python
> while result is not None and result.odata_next_link is not None:
>   result: Optional[EventCollectionResponse] = await graph_client.users.by_user_id(mailbox).calendar.calendar_view.with_url(result.odata_next_link).get(request_configuration = request_configuration)
> ```

Thanks @jussihi your solution is beautiful, wish this was documented better in the docs :) I was able to get this to work with your suggestion. 

        # get group members
        members = await client.groups.by_group_id(id).members.get()
        if members:
            print(f"########## Members:")
            for i in range(len(members.value)):
                print(f"display_name: {members.value[i].display_name}, mail: {members.value[i].mail}, id: {members.value[i].id}")

        # iterate over result batches > 100 rows
        while members is not None and members.odata_next_link is not None:
            members = await client.groups.by_group_id(id).members.with_url(members.odata_next_link).get()
            if members:
                print(f"########## Members:")
                for i in range(len(members.value)):
                    print(f"display_name: {members.value[i].display_name}, mail: {members.value[i].mail}, id: {members.value[i].id}")

**Comment by jussihi** [comment]
Glad to help!

**Comment by kannan-seenivasan** [comment]
Hi @jussihi / @sujaywork,


Sorry for the stupid question, 

Do we require, the below double check, whether `members is not None and members.odata_next_link is not None`?
```
while members is not None and members.odata_next_link is not None:
```
From my understanding validating `members.odata_next_link` this is more than enough. 
```
while members.odata_next_link is not None:
```
Please correct me, if my understanding is wrong.

**Comment by jussihi** [comment]
> Hi @jussihi / @sujaywork,
> 
> Sorry for the stupid question,
> 
> Do we require, the below double check, whether `members is not None and members.odata_next_link is not None`?
> 
> ```
> while members is not None and members.odata_next_link is not None:
> ```
> 
> From my understanding validating `members.odata_next_link` this is more than enough.
> 
> ```
> while members.odata_next_link is not None:
> ```
> 
> Please correct me, if my understanding is wrong.

@kannan-seenivasan  I'm not sure, I've just double-checked it since the return value of any `.get()` command that returns any "CollectionResponse" in this library returns an `Optional[<something>CollectionResponse]` coroutine, which implies that even the return value of `get()` (here `members`) could also be `None`.

**Comment by kannan-seenivasan** [comment]
Hi @jussihi , 
Thanks for quick reply. 
True, Even if `members` are None, then `members.odata_next_link` would also be _None_ right?
