### ISSUE TITLE
Query subsites

### ISSUE THREAD

**Issue by berntrune** [microsoftgraph/msgraph-sdk-python#588]
Add subsites to query.

I get an error running:
client.sites.by_site_id(site_id).sites.by_site_id(web_id).lists.by_list_id(list_id).items.get()

Exception: 'SitesRequestBuilder' object has no attribute 'by_site_id'

Is this supported today?

**Comment by berntrune** [comment]
Hi,
If subsites are not supported today, can you give me a ballpark estimate when you think that it will be supported?
I'm a bit stuck.

Thanks!
Rune

**Comment by andrueastman** [comment]
Thanks for raising this @berntrune 

Any chance you can confirm if the code at the link below works out for you in the latest version of SDK? https://learn.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=python#request
