### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'headers'

### ISSUE THREAD

**Issue by alexjordi** [microsoftgraph/msgraph-sdk-python#593]
Here is a copy of my error log:
  File "C:\Users\XXXX\Documents\GitHub\fitd\app\webservices\endpoints\inboxMonitoring.py", line 160, in inboxMonitor
    emails = await inbox_MS_client.users.by_user_id(user_id).messages.get(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\Documents\GitHub\fitd\.venv\Lib\site-packages\msgraph\generated\users\item\messages\messages_request_builder.py", line 54, in get
    request_info = self.to_get_request_information(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\Documents\GitHub\fitd\.venv\Lib\site-packages\msgraph\generated\users\item\messages\messages_request_builder.py", line 102, in to_get_request_information
    request_info.headers.add_all(request_configuration.headers)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'headers'

-----------------------

The value of inbox_MS_client is set by using this code:
def connect_to_MS_Graph(client_id, tenant_id, secret):
    # Create a credential object. Used to authenticate requests
    credential = ClientSecretCredential(
        tenant_id=tenant_id, client_id=client_id, client_secret=secret
    )
    scopes = ["https://graph.microsoft.com/.default"]
    # Create an API client with the credentials and scopes.
    client = GraphServiceClient(credentials=credential, scopes=scopes)
    return client
    
So why am I getting this error?

**Comment by shemogumbe** [comment]
Hello @alexjordi is your request  information a dictionary or a request information object. We have[ request information](https://github.com/microsoft/kiota-abstractions-python/blob/main/kiota_abstractions/request_information.py) and [request headers collection](https://github.com/microsoft/kiota-abstractions-python/blob/main/kiota_abstractions/headers_collection.py) classes for creating the respective objects.

Do you mind sharing a snippet of the code you are running
