### ISSUE TITLE
Is there a method to retrieve SharePoint Groups and its members using msgraph-sdk-python?

### ISSUE THREAD

**Issue by mingchun-zhao** [microsoftgraph/msgraph-sdk-python#60]
Hi,
Is there a method to retrieve SharePoint Groups and its members using msgraph-sdk-python?

**Comment by samwelkanda** [comment]
Hi @mingchun-zhao. 

Thank you for your interest in trying out our SDK. Here's a sample snippet to get the members of an [M365 group](https://learn.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0) using our SDK: 

```py
async def get_group_members():
    try:
        members = await client.groups_by_id('GROUP_ID').members.get()
        for member in members.value:
            user = await client.users_by_id(member.id).get()
            print(user.display_name, user.id)
    except Exception as e:
        print(e.error.message)
asyncio.run(get_group_members())
```

If instead you are referring specifically to permission groups within a Sharepoint site, then unfortunately that functionality is currently not available using the Microsoft Graph API.

**Comment by mingchun-zhao** [comment]
Hi @samwelkanda,
Thanks for your reply, got it.
