### ISSUE TITLE
Is there a method to fire Delta Query for SharePoint Documents using msgraph-sdk-python?

### ISSUE THREAD

**Issue by mingchun-zhao** [microsoftgraph/msgraph-sdk-python#61]
Hi,
Is there a method to fire Delta Query for SharePoint Documents using msgraph-sdk-python?

**Comment by samwelkanda** [comment]
Hi @mingchun-zhao 

Currently, there is no endpoint to fire a delta query on individual Sharepoint documents/files within Microsoft Graph. Delta queries are supported on drives, so an option is to issue a delta query on the drive containing the document, and it will give you the changes in the drive items over time. Here's a sample snippet:

```py
# GET DELTA OF A SHAREPOINT SITE ROOT DRIVE

async def get_root_delta():
    try:
        items = await client.sites_by_id('SITE_ID').drives_by_id('DRIVE_ID').root.delta.get()
        for item in items.value:
            print(item.id, item.name)
    except Exception as e:
        print(e)
asyncio.run(get_root_delta())
```

**Comment by mingchun-zhao** [comment]
Hi @samwelkanda,
Thanks for your reply, got it.
