### ISSUE TITLE
Error when trying to get site by URL

### ISSUE THREAD

**Issue by EverSoJoe** [microsoftgraph/msgraph-sdk-python#638]
Hi.
When trying to get site by URL I get the following error: `ValueError: Unable to parse claims from response`
Am I doing something wrong or is there an issue with the SDK?

Here is the full traceback
```
  File "/root/agco_dir/office365_test/sharepoint_delta_test.py", line 19, in <module>
    asyncio.run(client.sites.with_url(SP_SITE_URL).get())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/agco_dir/python_venv/lib/python3.11/site-packages/msgraph/generated/sites/sites_request_builder.py", line 69, in get
    return await self.request_adapter.send_async(request_info, SiteCollectionResponse, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/agco_dir/python_venv/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 178, in send_async
    response = await self.get_http_response_message(request_info, parent_span)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/agco_dir/python_venv/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 543, in get_http_response_message
    return await self.retry_cae_response_if_required(resp, request_info, claims)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/agco_dir/python_venv/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py", line 560, in retry_cae_response_if_required
    raise ValueError("Unable to parse claims from response")
ValueError: Unable to parse claims from response
```

**Comment by shemogumbe** [comment]
Hello @EverSoJoe  do you mind sharing a snippet of the code you are running for this?

**Comment by EverSoJoe** [comment]
Hi. I already moved to requests to handle the API calls. But as far as I recall I tried following approaches:
```python
site = asyncio.run(client.sites.with_url('https://<host>.sharepoint.com/sites/<site_name>").get())
drives = asyncio.run(client.sites.with_url('https://<host>.sharepoint.com/sites/<site_name>").drives.get())
```

**Comment by p6907265** [comment]
same

**Comment by GuidoZam** [comment]
Same issue here

**Comment by petrhollayms** [comment]
Hi @EverSoJoe ,

Thank you for raising this. Could you please share your SDK version, more info on the way you create the client and authenticate against Graph API and the log file?
Is the error specific to this endpoint or does it fail also for others, e.g. client.users.get() etc?

**Comment by shemogumbe** [comment]
Seen this error before on a number of instances, it has something to do with token acquisition and mostly fixed by updating client initialization.
This had to do with US  client initialization for US government clouds, also experienced it when initializing clients without giving all required parameters.
You can counter check client set up here https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/docs/applications_samples.md, https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/docs/authentication_samples.md,

**Comment by shemogumbe** [comment]
On this, the Site URL  is NOT supported by Graph, would be advisable to use ID
