### ISSUE TITLE
Wrong import path for MovePostRequestBody

### ISSUE THREAD

**Issue by NADOOITChristophBa** [microsoftgraph/msgraph-sdk-python#650]
Hello.

I created this pull request for the Microsoft graph documentation because I found that the path for importing MovePostRequestBody was wrong or at least did not work on my machine.

https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9274

Wrong:

from msgraph.generated.models.move_post_request_body import MovePostRequestBody

Right:

from msgraph.generated.users.item.messages.item.move.move_post_request_body import MovePostRequestBody

I was told that the snipped is generated from this somehow and I should file an issue.

**Comment by shemogumbe** [comment]
This  has been implemented here https://github.com/microsoftgraph/msgraph-sdk-python/issues/674
The PR has been merged https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/2019 and this should be aplied in the docs this week, kindly check back and confirm if the fix is in
