### ISSUE TITLE
SharePoint Custom Fields (Single line of text) - Gets cast to Python Pendulam DateTime

### ISSUE THREAD

**Issue by nikhilmakan02** [microsoftgraph/msgraph-sdk-python#653]
Hi Everyone, doing a simple call to a SharePoint Document library to return the custom metadata fields related to a file. What's interesting is I can set the column type to 'Single line of text' in SharePoint but if I put certain numbers into the column it returns as a datetime object.

If I put text in the field on SharePoint it returns correctly as text or even if I put enough numbers it returns as text as well.

In the example below the Doc_ID column in SharePoint contains the numbers 1212.
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/48241954/9f65d7a6-1540-4273-aa27-47621c8e54e8)
![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/48241954/38cf81a0-5a8d-4e58-8d65-0038f94bfc9e)

```
result = await (
        client.drives.by_drive_id(drive_id)
        .items.by_drive_item_id(drive_item_id)
        .list_item.get()
    )

print(result.fields.additional_data["Doc_x0020_ID"])
print(type(result.fields.additional_data["Doc_x0020_ID"]))

```

Output:
```
1212-01-01 00:00:00+00:00
<class 'pendulum.datetime.DateTime'>
```

This seems like unexpected behavior?

**Comment by georgethomasii** [comment]
I am seeing a similar issues when querying entraid attributes. Any value that has a 4-digit numerical value is being returned as a datetime object instead of a string. If I get the raw http response the value is returned as a string correctly. It would be great if this was looked into and resolved as I prefer not to have to get the native HTTPX response.

**Comment by shemogumbe** [comment]
Hello, and thanks  for continued use of the SDK and for raising this.
As we look into our serialization to give a consistent behaviour, would you cast the result to a string/datetime object for now: 

- [ ] Pendulum to string
```python
# Cast Pendulum DateTime to string
pendulum_datetime_string = pendulum_datetime.to_iso8601_string()
print("Pendulum DateTime as string (ISO 8601 format):", pendulum_datetime_string)
```
- [ ] string to pendulum 
```python
# Parse the string to Pendulum DateTime object
pendulum_datetime = pendulum.parse(pendulum_datetime_if_string)
```

**Comment by nikhilmakan02** [comment]
@shemogumbe I am not really sure how that is helpful? Are you suggesting I cast this to a string then truncate the string to get the 4 digit value. That sounds like a messy solution to be honest.

I have actually just implemented @georgethomasii suggestion to just get the raw response and get the metadata more reliably there.

**Comment by 56badkarma** [comment]
Anyone still dealing with this issue: 
[microsoft/kiota-python/pull/664](https://github.com/microsoft/kiota-python/pull/664) 
merged and released last week. Latest version has the real fix.
