### ISSUE TITLE
messages.by_message_id() does not replace forward slashes ("/") with dashes ("-")

### ISSUE THREAD

**Issue by derpadoo** [microsoftgraph/msgraph-sdk-python#658]
**Is your feature request related to a problem? Please describe.**

`users.by_user_id(user_id).messages.by_message_id(graph_message_id)` (https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/msgraph/generated/users/item/messages/messages_request_builder.py#L33) does not work when the `graph_message_id` has a `/` in it.  This seems to be a known issue without official documentation from Microsoft.

```python
import asyncio
from azure.identity.aio import ClientSecretCredential
from msgraph import GraphServiceClient

credentials = ClientSecretCredential(
    "tenant_id",
    "client_id",
    "client_secret",
)
scopes = ["https://graph.microsoft.com/.default"]
client = GraphServiceClient(credentials=credentials, scopes=scopes)

user_id = "12345678"

# Graph Message Id with a "/"
item_id = "ABCD....1234/k9CUAAA="

message = await client.users.by_user_id(user_id).messages.by_message_id(item_id).content.get()
print(message)
```

<img width="1261" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-python/assets/27816854/ddc8a4f3-0f0e-45b5-9aca-8b3477dc1fe0">

**Describe the solution you'd like**

Any instances of `/` in the Graph Message ID must be replaced with `-`

**Describe alternatives you've considered**

Encode the entire URL.

**Additional context**

  * https://github.com/microsoftgraph/microsoft-graph-docs/issues/10167
  * https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/7596#issuecomment-1680701646
  * https://blog.mastykarz.nl/office-365-unified-api-mail/
  * https://stackoverflow.com/questions/66686843/issue-with-microsoft-graph-api-with-forward-slashes-in-me-events-id
  * https://stackoverflow.com/questions/62154437/microsoft-graph-hostedcontents-id-contains-a-slash

**Comment by shemogumbe** [comment]
Hello @derpadoo  thanks for using the SDK and for raising this.

While acknowledging the issue, microsoft graph IDs rarely contain special characters e.g /, ?, #, they could be in other fields in which we would require to escape them accordingly.

The ID, you are passing to the query, did you get it from MS graph or another application, if from another application, why not just replace / with - before passing using message_id.

if from msgraph, how could we reproduce this,  for testing purposes.

Note: We use a custome generator to write models and request builders such as https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/msgraph/generated/users/item/messages/messages_request_builder.py - making a change on the generator to allow this could affect many other entitis whose ID does not contain '/'.
