### ISSUE TITLE
azure.core import error?

### ISSUE THREAD

**Issue by cltj** [microsoftgraph/msgraph-sdk-python#662]
**Is your feature request related to a problem? Please describe.**
How about making it not break on the first line? Why would i even get an import error for azure.core?

```
Exception has occurred: ModuleNotFoundError
No module named 'azure.core'
```

I have azure.core installed in my virtual environment as shown below

```
poetry show
azure-core                              1.30.1      Microsoft Azure Core Library for Python
```

**Describe the solution you'd like**
I expect the examples to work like provided, and not go 13 rounds on it for simple things to work. It should be either be as easy as the examples if it is to have any vaule for me or my company. 

**Describe alternatives you've considered**
The level of confusion with all the different sdks and the versions is createing a lot of overhead. I might as well just go back to api calls.  
Bah. Its very frustrating.

**Comment by shemogumbe** [comment]
Hello, thanks for using our SDK and for raising this.
Sorry for the frustrations you have faced.
To help you further, do you mind sharing the snippet you are using, and the documentation link that doesn't work as expected

**Comment by shemogumbe** [comment]
Closing for lack of further information and inabilityto reproduce
