### ISSUE TITLE
Wrong options given for devicecodecredential

### ISSUE THREAD

**Issue by bvduijn** [microsoftgraph/msgraph-sdk-python#663]
https://github.com/microsoftgraph/msgraph-sdk-python/blob/31d632610b5969439dfe406cb34301a816250735/README.md?plain=1#L66

According to the options specified for [devicecodecredential ](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.devicecodecredential?view=azure-python) the **tenantID** is a keyword only parameter.
The line should be:

```
credentials = DeviceCodeCredential(client_id, 
                                   tenant_id=tenant_id )
```

**Comment by shemogumbe** [comment]
Thanks for raising this, for delegated flow, you can use both keywoord and positional arguments, should they positional, the order to be client_id, tenanant id, for keyword arguments which is a good preferance, put them whenere.
Did you find a bug using tenant_id as a positional argument?
