### ISSUE TITLE
Sending Attachment with mail does not include the contentBytes in request

### ISSUE THREAD

**Issue by Christiaan-Mathu** [microsoftgraph/msgraph-sdk-python#667]
**Is your feature request related to a problem? Please describe.**
I am trying send a mail with some attachments, but when I do I get the following response back from the API:

```
APIError
        Code: 400
        message: None
        error: MainError(additional_data={}, code='ErrorRequiredPropertyMissing', details=None, inner_error=None, message='Required property is missing.', target=None)
```

After quite a bit of debugging I tracked down that the request does not include the `contentBytes` property so the request would look like this:

```
    ...
    "attachments": [
        {
          "@odata.type": "#microsoft.graph.fileAttachment",
          "name": "someFile.svg"
           # Missing contentBytes here
        }
    ],
    ...
``` 

**Describe the solution you'd like**
To be honest I don't know why this is happening and would just like to clarify if this is a bug or user error🙏 

**Describe alternatives you've considered**
I tested sending mail with attachments on Postman and it worked there so just trying to get it to work in python.

**Comment by danalex7212** [comment]
I'm facing the same issue . Unable to send file attachments with the same API error .

**Comment by shemogumbe** [comment]
Hello, thanks for using the SDK and for raisning this, do you mind sharing the snippet of code you are using, a link to the docs/snippet your are depending on?

**Comment by Christiaan-Mathu** [comment]
Hi @shemogumbe,

This issue was caused by user error and can be closed.

For future reference, if anyone encounters a similar problem, it was due to passing the base64 files as type `str` instead of type `bytes`.

The resolution was to decode the base64 strings to bytes, as shown in the example below:

```python
FileAttachment(
    name=file.name,
    content_bytes=base64.b64decode(file.content_bytes),
    odata_type="#microsoft.graph.fileAttachment",
)
```

So file.content_bytes here is type `str` and the decode function returns type `bytes` and after this it worked.

Hope it helps :)
