### ISSUE TITLE
Unable to add Token Signing Certificate to Service Principal

### ISSUE THREAD

**Issue by rubenk** [microsoftgraph/msgraph-sdk-python#675]
Hi,

I'm trying to setup an Enterprise App for SAML authentication. Therefore I need to add a Token Signing Certificate to the Service Principle.

I tried the following:
```
await self._graph_service_client.service_principals.by_service_principal_id(service_principal.id).add_token_signing_certificate.post(
    body={
        'display_name':'saml app'
    }
}
```
but this gives me `Exception: AttributeError: 'dict' object has no attribute 'serialize'`

I'm guessing I need some kind of model instead of a dict for the body, but can't find one for TokenSigningCertificate.

Can you please tell me the right way to do this?

**Comment by shemogumbe** [comment]
Hello, thanks for continued use of the SDK, have you tried this https://learn.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&tabs=python

**Comment by rubenk** [comment]
Thanks for that, it works.
