### ISSUE TITLE
Can't find MessagesRequestBuilderGetRequestConfiguration used across examples

### ISSUE THREAD

**Issue by WilliamWood01** [microsoftgraph/msgraph-sdk-python#681]
Hello, I have been looking at the following examples for adding query parameters and they make use of a property called 'MessagesRequestBuilderGetRequestConfiguration', yet I can't find this property anywhere. I have tried to make an acceptable request configuration myself but I am struggling.

Apologies if this an improper issue or I have made a mistake, this is the first time I have tried to raise an issue

Example I was using:
https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/docs/general_samples.md

![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/117728607/77826d98-54ef-4dd8-a3a9-12b933038e4c)

File where I think the property should be:

https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/msgraph/generated/users/item/messages/messages_request_builder.py

I would like a way to create a valid request_configuration as in the examples, if one exists please let me know and apologies for wasting anyone's time

EDIT:
I think it may be related to this open issue https://github.com/microsoftgraph/msgraph-sdk-python/issues/680, will try the new sample 

EDIT 2;
Got this working with the new sample - 
from kiota_abstractions.base_request_configuration import RequestConfiguration

query_params= MessageRequestBuilder.MessageRequestBuilderGetQueryParams(top=1000)
request_config= RequestConfiguration(query_parameters=query_params)

SomeProcess.get(request_configuration=request_config)

**Comment by shemogumbe** [comment]
Thanks for  your continued use of the SDK and  for raising this:
We have work ongoing to get this resolved asap https://github.com/microsoft/kiota/issues/4535

In the meantime:

- [ ]  You can downgrade to our V1.2.0
- [ ]  If using V1.3.0, you can tweak the code to be:

```diff

+from kiota_abstractions.base_request_configuration import RequestConfiguration
from msgraph import GraphServiceClient
from msgraph.generated.users.item.messages.messages_request_builder import MessagesRequestBuilder
graph_client = GraphServiceClient(credentials, scopes)
query_params = GroupsRequestBuilder.GroupsRequestBuilderGetQueryParameters(
		filter = "startswith(displayName, 'a')",
		count = True,
		top = 1,
		orderby = ["displayName"],
)
-request_configuration = MessagesRequestBuilder.MessagesRequestBuilderGetRequestConfiguration(
+request_configuration = RequestConfiguration(
query_parameters = query_params,
)
request_configuration.headers.add("ConsistencyLevel", "eventual")
result = await graph_client.groups.get(request_configuration = request_configuration)
```

As we solve for this, we believe this patch will be compatible with the solution once done, thus you might not necessarily need to change your code then.

**Comment by WilliamWood01** [comment]
Hello!

Thanks for the response and the solution, as per the edit I did find this and managed to get it working, I feel this can be closed

**Comment by shemogumbe** [comment]
This has been resolved for backward compatibility in https://github.com/microsoft/kiota/pull/4578, closing as both the workaround and the backward compatibility fix is in
