### ISSUE TITLE
Unable to find property 'MovePostRequestBody' which is used in example documentation

### ISSUE THREAD

**Issue by WilliamWood01** [microsoftgraph/msgraph-sdk-python#686]
As per title I am unable to find the MovePostRequestBody class required to make requests to move an email to another folder, looking for alternate solutions.

I have found msgraph.generated.models.move_post_request_body does not exist yet it is used in the example:

![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/117728607/b46a4df3-9f57-4351-9314-9f7a229bfcc7)

https://learn.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=python

**Describe the solution you'd like**
Is there a new way to achieve this? If so the documentation should reflect this, although I am aware the contributors to this repo may not be responsible for that.

EDIT:

Apologies I think I have been a bit trigger-happy with this issue, the same problem has been referenced here - https://github.com/microsoftgraph/msgraph-sdk-python/issues/650 , and the corrected import works:

from msgraph.generated.users.item.messages.item.move.move_post_request_body import MovePostRequestBody

**Comment by shemogumbe** [comment]
Hello, this was fixed two weeks ago and the fix is not in the docs https://learn.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=python
