### ISSUE TITLE
Has APIError handling changed recently?

### ISSUE THREAD

**Issue by yoxalld** [microsoftgraph/msgraph-sdk-python#691]
I've been working on a project for a while and I recently came back to a part of the project where users are created in this fashion:

```python
try:
    result = await client.users.post(user)
    return result
except APIError as e:
    if e.error.details[0].code == 'ObjectConflict':
        # Check for duplicates, enumerate email address, try again
```

This was working fine before and I was able to identify if the user already existed and try to create a new user/email address by adding a number to the email address.

For some reason now when this gets called and the user already exists I get a generic 400 error response indicating the payload was malformed.
```
APIError(message='The server returned an unexpected status code and no error class is registered for this code 400',
         response_status_code=400,
         response_headers=Headers({'cache-control': 'no-cache', 'content-type': 'application/json', 'content-encoding': 'gzip', 'vary': 'Accept-Encoding', 'strict-transport-security': 'max-age=31536000', 'request-id': 'xxxxxxxxxxxx', 'client-request-id': 'xxxxxxxxxxxxx', 'x-ms-ags-diagnostic': '{"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"006","RoleInstance":"xxxxxxxxx"}}', 'x-ms-resource-unit': '1', 'date': 'Thu, 25 Apr 2024 15:23:19 GMT'}))
```
I only get this error when trying to create a user that already exists. This indicates to me that the payload is formed just fine. Is there some other way of digging into the response so that I am able check for the ObjectConflict again?

EDIT
I'm including the installed package list from the virtual environment with versions for reference in case those details help identify the issue.
```
Package                                 Version     
--------------------------------------- -----------
aiohttp                                 3.9.3
aiosignal                               1.3.1
anyio                                   4.2.0
attrs                                   23.2.0
azure-core                              1.30.0
azure-identity                          1.15.0
certifi                                 2024.2.2
cffi                                    1.16.0
charset-normalizer                      3.3.2
cryptography                            42.0.2
Deprecated                              1.2.14
dnspython                               2.5.0
email-validator                         2.1.0.post1
et-xmlfile                              1.1.0
frozenlist                              1.4.1
h11                                     0.14.0
h2                                      4.1.0
hpack                                   4.0.0
httpcore                                1.0.2
httpx                                   0.26.0
hyperframe                              6.0.1
idna                                    3.6
importlib-metadata                      6.11.0
iniconfig                               2.0.0
microsoft-kiota-abstractions            1.3.2
microsoft-kiota-authentication-azure    1.0.0
microsoft-kiota-http                    1.2.1
microsoft-kiota-serialization-form      0.1.0
microsoft-kiota-serialization-json      1.0.1
microsoft-kiota-serialization-multipart 0.1.0
microsoft-kiota-serialization-text      1.0.0
msal                                    1.26.0
msal-extensions                         1.1.0
msgraph-core                            1.0.0
msgraph-sdk                             1.2.0
multidict                               6.0.5
numpy                                   1.26.4
openpyxl                                3.1.2
opentelemetry-api                       1.22.0
opentelemetry-sdk                       1.22.0
opentelemetry-semantic-conventions      0.43b0
packaging                               23.2
pandas                                  2.2.0
pendulum                                3.0.0
pip                                     24.0
pluggy                                  1.4.0
portalocker                             2.8.2
pyarrow                                 15.0.0
pycparser                               2.21
PyJWT                                   2.8.0
pytest                                  8.1.1
python-dateutil                         2.8.2
python-dotenv                           1.0.1
pytz                                    2024.1
PyYAML                                  6.0.1
requests                                2.31.0
setuptools                              69.0.2
six                                     1.16.0
sniffio                                 1.3.0
std-uritemplate                         0.0.50
time-machine                            2.13.0
typing_extensions                       4.9.0
tzdata                                  2023.4
urllib3                                 2.2.0
wrapt                                   1.16.0
yarl                                    1.9.4
zipp                                    3.17.0
```

**Comment by shemogumbe** [comment]
Using APIError, I assume you are using the abstraction class here https://github.com/microsoft/kiota-abstractions-python/blob/main/kiota_abstractions/api_error.py, if so, the MainError object would not even be subscriptible unless toy serialize into into a native type, 
Note that you can inherit the API error and customize it to your needs with the base elements returned.
The messages from the API are not static and thus the need to use error messages that are as generic as possible, and if you want some special error handling, implement the abstraction differently.

**Comment by yoxalld** [comment]
Yes, I have been using the class from kiota_abstractions for the APIError class. It was working before and I was able to get more details within the APIError object before that are no longer present. The __str__ method within that class looks for an 'error' attribute that seems to no longer be passed along in the response. That's why I asked if the responses from the Graph API have changed because it seems like the data that was present isn't anymore.

**Comment by shemogumbe** [comment]
Yes, stringifying the MainError will give any of the fields in this snippet if they do not exist, thing is, we do not have control on what exact message the API returns and that is why we try to be as generic as possible in our handling of the error:
` ``python
def __str__(self) -> str:
        error = getattr(self, "error", None)
        if error:
            return f"""
        APIError
        Code: {self.response_status_code}
        message: {self.message}
        error: {error}
        """
        return f"""
        APIError
        Code: {self.response_status_code}
        message: {self.message}
        """
```
