### ISSUE TITLE
Invitation does not support setting user attributes and SDK does not support PATCH for updating user

### ISSUE THREAD

**Issue by lorandvarga** [microsoftgraph/msgraph-sdk-python#721]
Hi,

Trying to invite users automatically into my entra tenant.

Using:
`request_body = Invitation(invite_redirect_url=invite_redirect_url, invited_user_display_name=display_name, invited_user_email_address=mail, invited_user_type="Guest", send_invitation_message=True)`
`result = await graph_client.invitations.post(request_body)`
to invite the external user which seems to work.

Need to set other attributes about the user such as first name, last name, department etc.

From the docs and my testing I see that `invited_user` is readonly so can't leverage that. 
From what I see `UsersRequestBuilder` implements only GET and POST so can't leverage that.

Is there another way to do it or Is this a limitation of the SDK?

Thank you for your help.

**Comment by fey101** [comment]
Hi @lorandvarga. Thanks for raising this. The question asked is MS Graph API related and therefore the MS Graph SDK team is not in a position to give all the relevant details and comprehensively. Could you please post your question to the API team here https://developer.microsoft.com/en-us/graph/support. Thanks

**Comment by lorandvarga** [comment]
hi @fey101 ,
thanks for your answer. I've actually received some support on a different channel and it seems this is implemented via 
`
user_update = User(
            given_name=given_name,
            surname=surname
        )
`
`await graph_client.users.by_user_id(user_id).patch(user_update)`
I'll close the issue since I got what I needed.
