### ISSUE TITLE
devices.by_device_id() does not work with device IDs, only with object IDs

### ISSUE THREAD

**Issue by dotconfig404** [microsoftgraph/msgraph-sdk-python#730]
### Describe the bug

Hi, I noticed that the method by_device_id() is probably out of date, as I suspect the API call for that was changed? 

In the documentation 
https://learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-1.0
it shows the correct http calls to get devices by their IDs, i.e. 
```
GET /devices/{id}
GET /devices(deviceId='{deviceId}')
```
Here we see that by calling `GET /devices/{id}` we can get a device by it's (object) ID and by calling 
`GET /devices(deviceId='{deviceId}')` we can get a device by its device ID.
But the SDK method does not have this nuance, it can only uses the underlying API call for /devices/{id}, not /devices/{deviceId='{deviceId}'). 

Here some relevant code from the Python version of DeviceItemRequestBuilder:
```python
class DeviceItemRequestBuilder(BaseRequestBuilder):
    """
    Provides operations to manage the collection of device entities.
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, Dict[str, Any]]) -> None:
        """
        Instantiates a new DeviceItemRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/devices/{device%2Did}{?%24expand,%24select}", path_parameters)
```
and the DeviceRequestBuilder:
```python
    def by_device_id(self,device_id: str) -> DeviceItemRequestBuilder:
        """
        Provides operations to manage the collection of device entities.
        param device_id: The unique identifier of device
        Returns: DeviceItemRequestBuilder
        """
        if not device_id:
            raise TypeError("device_id cannot be null.")
        from .item.device_item_request_builder import DeviceItemRequestBuilder

        url_tpl_params = get_path_parameters(self.path_parameters)
        url_tpl_params["device%2Did"] = device_id
        return DeviceItemRequestBuilder(self.request_adapter, url_tpl_params)
```
### Expected behavior

Should return device object when using the device ID in devices.by_device_id(device_id='deviceId')

### How to reproduce

E           msgraph.generated.models.o_data_errors.o_data_error.ODataError: 
E                   APIError
E                   Code: 404
E                   message: None
E                   error: MainError(additional_data={}, code='Request_ResourceNotFound', details=None, inner_error=InnerError(additional_data={}, client_request_id='78fd7570-ab44-44c2-a995-c672fc2d4ca2', date=DateTime(2024, 5, 29, 10, 20, 1, tzinfo=Timezone('UTC')), odata_type=None, request_id='8e2dc2a3-e80f-41b4-a654-c6376650ff03'), message="Resource '4c299165-6e8f-4b45-a5ba-c5d250a707ff' does not exist or one of its queried reference-property objects are not present.", target=None)

.venv/lib/python3.10/site-packages/kiota_http/httpx_request_adapter.py:503: ODataError

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by SilasKenneth** [comment]
Hi @dotconfig404, thanks for trying out the SDK.

Have you tried doing this instead?
```python
client.devices_with_device_id(device_id='device-id')
```

I believe that provides the functionality you are looking for.
If this resolves your issue, kindly consider closing the issue.

**Comment by dotconfig404** [comment]
Thanks for showing me this alternative method, this works. I cannot find it in the documentation, can you point it out to me? 

I am not sure if this issue should be closed, as the other SDK method seems to be bugged anyways. i.e. it should work with `client.devices.by_device_id(device_id='deviceId')` as well, but it doesn't.

**Comment by SilasKenneth** [comment]
Hi @dotconfig404, 
I am glad that works for you.
First, the two URLs generate different fluent paths which is expected since they are not identical.
Could you please provide some context on why you think the other method is bugged?

**Comment by dotconfig404** [comment]
https://learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-1.0&tabs=http#http-request

As you can see the documentation says you can address devices using either their id or deviceId. 
```
GET /devices/{id}
GET /devices(deviceId='{deviceId}')
```

Then further down there are SDK examples. However, the given example for addressing a device using the SDK does not work using the deviceId, it only works using the id, even when explicitly passing device_id='device_id', as in the http request example above.

**Comment by SilasKenneth** [comment]
The Snippets in examples are generated using the URL on the HTTP tab. If you want to get examples for alternative URLs, you can try Graph explorer by pasting the URL there and clicking on the Snippets tab at the bottom to get snippets for the current URL.
Example from above
https://developer.microsoft.com/en-us/graph/graph-explorer?request=devices(deviceId%3D'device_id')&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

**Comment by dotconfig404** [comment]
I understand now. Although I think it is confusing, it is not a bug and I will close the issue. 

Thanks for showing me the graph explorer, this is indeed very useful for generating snippets. Actually, it seems essential.
