### ISSUE TITLE
missing CopilotInteraction key for enum AuditLogRecordType

### ISSUE THREAD

**Issue by xstex** [microsoftgraph/msgraph-sdk-python#767]
### Describe the bug

When parsing purview Audit Logs, i get this error:

> Invalid key: CopilotInteraction for enum <enum 'AuditLogRecordType'>.

This record type is documented here: https://learn.microsoft.com/en-us/office/office-365-management-api/copilot-schema

### Expected behavior

CopilotInteraction type should be added to enum

### How to reproduce

_AuditLogRecordType.CopilotInteraction_ should not give error

### SDK Version

1.4.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @xstex 

Any chance you can confirm if this is still an issue with the latest sdk version 1.5.2?
