### ISSUE TITLE
Allow getting Sharepoint list item attachements

### ISSUE THREAD

**Issue by chrismit3s** [microsoftgraph/msgraph-sdk-python#786]
### Is your feature request related to a problem? Please describe the problem.

I am trying to get the attachements of a Sharepoint list item, but that functionality is not supported since [2019!](https://stackoverflow.com/a/57515352).

### Describe the solution you'd like.

Please expose the functionality in msgraph. It is already implemented in the Sharepoint Online REST API.

**Comment by fey101** [comment]
Hello @chrismit3s , according to documentation [here](https://github.com/microsoftgraph/msgraph-sdk-python/tree/main/msgraph/generated/teams/item/channels/item/messages/item/hosted_contents/item/value), it should be possible to expand fields. Could you try testing this on [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and if not possible, recreate your issue in the Graph API support page here https://developer.microsoft.com/en-us/graph/support

**Comment by chrismit3s** [comment]
I don't quite understand, the class you linked it for teams messages attachments, not Sharepoint list attachments. How can I use that to access Sharepoint list attachments?
