### ISSUE TITLE
Directly insert an rfc822 message into the user's inbox, similar to IMAP APPEND. 

### ISSUE THREAD

**Issue by antonyjosepha** [microsoftgraph/msgraph-sdk-python#791]
Hi all,

Using the msgraph API to directly insert an rfc822 message into the user's inbox, equivalent to IMAP APPEND.  Can someone help me?

Thanks,
Antony

**Comment by andrueastman** [comment]
Thanks for raising this @antonyjosepha 

At the moment, the API supports creating messages in json and Mime format as described at https://learn.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http

Any chance you'd be willing to submit a request at the link below to give feedback to the API owners to look into adding support for this?

https://aka.ms/graphFeedback
