### ISSUE TITLE
Delete a Teams channel using msgraph-sdk-python

### ISSUE THREAD

**Issue by mprnci** [microsoftgraph/msgraph-sdk-python#80]
Hello,

I have been trying to find a way to delete a Teams channel using msgraph-sdk-python but I do not seem to find it. Is there a method for this matter?

Thank you

**Comment by samwelkanda** [comment]
Hi @mprnci 

Thank you for trying out our SDK. That should be:

```py
# DELETE A TEAMS CHANNEL

async def delete_channel():
    try:
        await client.teams_by_id('TEAM_ID').channels_by_id('CHANNEL_ID').delete()
    except Exception as e:
        print(e.error.message)
asyncio.run(delete_channel())
```

Note that the SDK closely mirrors the syntax of the corresponding HTTP call to the API:  
`DELETE /teams/{team-id}/channels/{channel-id}`

 You can use that as reference for future SDK calls.

**Comment by mprnci** [comment]
Hello @samwelkanda,

First of all, thank you for the quick answer!

I have indeed tried doing this but following error appears:
`await client.teams_by_id(team_id).channels_by_id(channel_id).delete()
AttributeError: 'ChannelItemRequestBuilder' object has no attribute 'delete'`

**Comment by samwelkanda** [comment]
@mprnci 

Indeed the call is failing due to a naming conflict with another request builder. Similar to https://github.com/microsoftgraph/msgraph-sdk-python/issues/46

We are fast tracking the fix and will update the SDK soon.

**Comment by mprnci** [comment]
@samwelkanda thank you!
Do you have an estimated day for the fix?
