### ISSUE TITLE
Problem with API responses with string 'none'

### ISSUE THREAD

**Issue by tynsh** [microsoftgraph/msgraph-sdk-python#81]
Hi,

it seems there is a problem with api responses with the string "none". Here is an example, but I think this might happen more often.

### Problem
When fetching sign-ins, an exception from kiota_serialization_json is raised.

Minimal example for reproduction:

```#!/usr/bin/env python3

import asyncio

from azure.identity import DefaultAzureCredential
from msgraph import GraphRequestAdapter
from msgraph import GraphServiceClient
from kiota_authentication_azure.azure_identity_authentication_provider import AzureIdentityAuthenticationProvider

from msgraph.generated.audit_logs.sign_ins.sign_ins_request_builder import SignInsRequestBuilder


# Acquire a credential object
credential = DefaultAzureCredential()
auth_provider = AzureIdentityAuthenticationProvider(credential)
adapter = GraphRequestAdapter(auth_provider)
client = GraphServiceClient(adapter)

async def get_failed_sign_ins():
  query_params = SignInsRequestBuilder.SignInsRequestBuilderGetQueryParameters(
    top=10, filter='createdDateTime gt 2023-01-30 and status/errorCode ne 0'
  )
  request_config = SignInsRequestBuilder.SignInsRequestBuilderGetRequestConfiguration(
    query_parameters=query_params
  )

  failed_sign_ins = await (client.audit_logs.sign_ins.get(request_configuration=request_config))

asyncio.run(get_failed_sign_ins())
```

The exception raised is ```Invalid key: None for enum <enum 'RiskState'>.``` . This seems to happen, because the API Response contains the string 'none' for this field, which is turned into 'None' by preprocessing in kiota_serialization_json. The following is a the corresponding line in the dataclass. It seems to expect 'None_'.

https://github.com/microsoftgraph/msgraph-sdk-python/blob/deb4a99b6093adc35b0760d029176612c43b9d28/msgraph/generated/models/risk_level.py#L8

Best

Tobias

**Comment by samwelkanda** [comment]
Hi @tynsh 

Thank you for trying out the SDK and reporting the issue! I was able to replicate the bug and we are working on a fix.

**Comment by sogoogos** [comment]
Encountered the same issue.

**Comment by samwelkanda** [comment]
This has been fixed in the serialization library. Kindly update to the latest version [0.2.2](https://pypi.org/project/microsoft-kiota-serialization-json/)

**Comment by sogoogos** [comment]
@samwelkanda Thank you for fixing it!
