### ISSUE TITLE
msgraph.generated.models.o_data_errors.o_data_error.ODataError when self.user_client.me.todo.lists.get()

### ISSUE THREAD

**Issue by mr-pounds** [microsoftgraph/msgraph-sdk-python#87]
I am getting error _msgraph.generated.models.o_data_errors.o_data_error.ODataError_.

config.cfg
```
[azure]
clientId = ***
tenantId = ***
graphUserScopes = Tasks.Read Directory.Read.All User.ReadBasic.All User.Read
clientSecret = ***
```

graphy.py 
```
class Graph:
    settings: SectionProxy
    device_code_credential: DeviceCodeCredential
    adapter: GraphRequestAdapter
    user_client: GraphServiceClient

    def __init__(self, config: SectionProxy):
        self.settings = config
        client_id = self.settings["clientId"]
        tenant_id = self.settings["tenantId"]
        graph_scopes = self.settings["graphUserScopes"].split(" ")

        self.device_code_credential = DeviceCodeCredential(
            client_id, tenant_id=tenant_id
        )
        auth_provider = AzureIdentityAuthenticationProvider(
            self.device_code_credential, scopes=graph_scopes
        )
        self.adapter = GraphRequestAdapter(auth_provider)
        self.user_client = GraphServiceClient(self.adapter)

    async def get_user_token(self):
        graph_scopes = self.settings["graphUserScopes"]
        access_token = self.device_code_credential.get_token(graph_scopes)
        return access_token.token

    async def get(self):
        user = await self.user_client.me.todo.lists.get()
        print(user)
```

main.py
```
import asyncio
import configparser
from graph import Graph

async def main():
    print("Python Graph Tutorial\n")

    # Load settings
    config = configparser.ConfigParser()
    config.read(["config.cfg", "config.dev.cfg"])
    azure_settings = config["azure"]

    graph: Graph = Graph(azure_settings)
    await graph.get()

asyncio.run(main())
```

**Comment by samwelkanda** [comment]
Hi @mr-pounds. Thanks for trying out our library.

This is an error respose from the API. Wrap your functions in `try` `catch` statements to access the error details like so

```py
async def get_user_lists():
    try:
        user = await self.user_client.me.todo.lists.get()
        print(user.user_principal_name, user.display_name, user.id)
    except Exception as e:
        print(f'Error: {e.error.message}')

asyncio.run(get_user_lists())
```

**Comment by mr-pounds** [comment]
I try it, get nothing about error.

![image](https://user-images.githubusercontent.com/30515791/218231241-5f763be0-0aa8-4465-8127-02394bb73cf0.png)

**Comment by baffoon242** [comment]
I have just gone through the same error message when calling 

`users.get()`

In my case the error was caused by an invalid Accept header being sent from the client, eg

> GET /v1.0/users HTTP/1.1
> Host: graph.microsoft.com
> Accept-Encoding: gzip, deflate
> User-Agent: python-httpx/0.23.3
> **Accept: a, p, p, l, i, c, a, t, i, o, n, /, j, s, o, n**

seems to be occurring in kiota_abstractions/request_information.py

>     @property
>     def request_headers(self) -> Optional[Dict]:
>         final = {}
>         for key, value in self.headers.items():
>             final[key] = ', '.join(value)
>         return final


For testing I am ignoring the Accept header and it works correctly now

> GET /v1.0/users HTTP/1.1
> Host: graph.microsoft.com
> Accept-Encoding: gzip, deflate
> User-Agent: python-httpx/0.23.3
> Accept: application/json

**Comment by mr-pounds** [comment]
您好，我已经收到您的邮件。

**Comment by iargue** [comment]
https://github.com/microsoftgraph/msgraph-sdk-python/issues/134

This is caused because the current version being pushed by PIP is 1.0.0a9 and is setting the header as a string. The latest version on github is 1.0.0.a11 and is setting the header as a list.

This will give you the latest version directly from git.
`pip install --upgrade 'msgraph-sdk @ git+https://github.com/microsoftgraph/msgraph-sdk-python.git'`
