### ISSUE TITLE
Invalid scopes (using the example code from README)

### ISSUE THREAD

**Issue by fschlz** [microsoftgraph/msgraph-sdk-python#889]
### Describe the bug

I'm trying to follow the examples in the README, but my scope definitions seem to be wrong, I'm just getting this error:

```
Microsoft Entra ID error '(invalid_scope) AADSTS1002012: The provided value for scope User.Read is not valid.
```

### Expected behavior

code in the README should execute successfully

### How to reproduce

```python
credentials = ClientSecretCredential(
    os.getenv("AZURE_TENANT_ID"),
    os.getenv("AZURE_CLIENT_ID"),
    os.getenv("AZURE_CLIENT_SECRET"),
)

scopes = ["User.Read"]
client = GraphServiceClient(credentials=credentials, scopes=scopes)

await client.users.by_user_id('userPrincipalName').get()
```

### SDK Version

1.5.3

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @fschlz 

Apologies, the scope for that snippet is incorrect. Authored https://github.com/microsoftgraph/msgraph-sdk-python/pull/890 to resolve this. 

As you the sample is using the `ClientSecretCredential` the application is using app only access so the scope should be the default scope of `'https://graph.microsoft.com/.default'` and then configured on the app portal. 

https://learn.microsoft.com/en-us/graph/permissions-overview?tabs=http#application-permissions
