### ISSUE TITLE
None attributes of Drive object

### ISSUE THREAD

**Issue by LuchiLucs** [microsoftgraph/msgraph-sdk-python#892]
### Describe the bug

I tried exploring the APIs of Files/Drive by calling:
`await self.client.users.by_user_id(user_id).drives.by_drive_id(drive_id).get()`
But the returned object has all the attributes init by `None`, such as `root`, `items`.

Is this normal? I believe I should see these attributes if in the OneDrive dashboard I see some folders/files using the personal space of the user_id I provide and the drive_id of the OneDrive Drive object.

Here the same question with more context:
https://stackoverflow.com/questions/78964383/how-can-i-use-msgraph-python-sdk-to-properly-list-or-get-files-from-onedrive

My goal is to be able to query the endpoint:
https://mycompany-my.sharepoint.com/my?id=%2Fpersonal%2my_user_id%2FDocuments%2FDocuments
In order to see/list the available files/folders.

### Expected behavior

I expect to be able to see items or root attributes not equal to None, in order to chain query like this:
`self.client.users.by_user_id(user_id).drives.by_drive_id(drive_id).root.children.get()`

### How to reproduce

```
drive = await drive_dao.client.users.by_user_id(drive_dao.user_id).drives.by_drive_id(drive_dao.drive_id).get()
drive.root
drive.items
```

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by shemogumbe** [comment]
Hello @LuchiLucs 
Thanks for raising this and for using the SDK:
This is potentially related to https://github.com/microsoftgraph/msgraph-metadata/issues/596 in which case most of the data is dumped in additional data.

In the meantime you can just follow the nesting to the appropriate item, worksheet table. 
e.g - 
```
self.client.users.by_user_id(user_id).drives.by_drive_id(drive_id).root.children.get()

```
will map to 
```python
drive_items = await user_client.drives.by_drive_id(
            'drive-id'
        ).items.get()
``
then with the items you can nest further to
```
ws_table_data = await user_client.drives.by_drive_id(
            ''
        ).items.by_drive_item_id(
            ''
        ).get()
```
https://github.com/microsoftgraph/msgraph-sdk-python/tree/main/msgraph/generated/drives/item/items/item  and follow the nesting till you get the object you want

**Comment by SuryaThiru** [comment]
Hi, I'm running into similar issues where drive attributes are None. As a result, the code below errors:

```python
await client.sites.by_site_id(SITE_ID).drives.by_drive_id(DRIVE_ID).root.children.get()
```

```
AttributeError: 'DriveItemRequestBuilder' object has no attribute 'root'
```

The equivalent http request works:

```
https://graph.microsoft.com/v1.0/sites/{{site_id}}/drives/{{drive_id}}/root/children
```
