### ISSUE TITLE
How to get immutable identifiers for any outlook based request?

### ISSUE THREAD

**Issue by adhadseKavida** [microsoftgraph/msgraph-sdk-python#903]
Specifically, I'm looking at this documentation: https://learn.microsoft.com/en-us/graph/outlook-immutable-id. 

For anyone coming to the issue:

Outlook items (messages, events, contacts, tasks) have an interesting behavior that you've probably either never noticed or has caused you significant frustration: their IDs change. It doesn't happen often, only if the item is moved, but it can cause real problems for apps that store IDs offline for later use. Immutable identifiers (IDs) enable your application to obtain an ID that doesn't change for the lifetime of the item.

An item's immutable ID won't change so long as the item stays in the same mailbox. That means that immutable ID will NOT change if the item is moved to a different folder in the mailbox. However, the immutable ID changes if:

- The user moves the item to an archive mailbox.
- The user exports the item (to a PST, as an MSG file, etc.) and re-imports it into their mailbox.

---
How is that supposed to work with msgraph-sdk-python? @shemogumbe

**Comment by shemogumbe** [comment]
Hello @adhadseKavida tha ks for using the SDK and for raising this.

Graph has a way to give you immutable IDs, just set your requests with `Prefer: IdType="ImmutableId"` header,

Follow https://learn.microsoft.com/en-us/graph/outlook-immutable-id#immutable-id-with-sending-mail
