### ISSUE TITLE
Set and unset reaction on chatMessage or use raw URL

### ISSUE THREAD

**Issue by nakasix** [microsoftgraph/msgraph-sdk-python#920]
### Is your feature request related to a problem? Please describe the problem.

Hello,

I would like to set an unset reaction on chatMessage, but I don't think the SDK supports it.

- **Set**: https://learn.microsoft.com/en-us/graph/api/chatmessage-setreaction?view=graph-rest-1.0
- **Unset**: https://learn.microsoft.com/en-us/graph/api/chatmessage-unsetreaction?view=graph-rest-1.0

Is it possible to add it?

### Describe the solution you'd like.

For example:

- **Set**: await graph_client.users.by_user_id('user-id').chats.by_chat_id('chat-id').messages.by_chat_message_id('chatMessage-id').set_reaction.post('reaction-type')
- **Unset**: await graph_client.users.by_user_id('user-id').chats.by_chat_id('chat-id').messages.by_chat_message_id('chatMessage-id').unset_reaction.ost('reaction-type')

### Additional context?

In the meantime is it possible to make a post with a raw URL and data with SDK ? A possible example :)
I tried that, but it didn't work :(
```
str_url = "https://graph.microsoft.com/1.0/chats/{}/messages/{}/unsetReaction".format(str_chat_id, str_message_id)
await self.obj_client.chats.with_url(str_url).post(body={"reactionType": str_reaction})
```

Or is it possible to retrieve the access_token from SDK to use the requests module?

**Comment by shemogumbe** [comment]
Hello @nakasix thanks for using the SDK and for raising this.

While this is currently not supported due to metadata constraints, there are multiple ways you can do this via Raw URL calls through the SDK or using the python requests library:
*Using python requests*
Once you have the access token, you can always do requests using requests library or urllib.
```python
credentials = ClientSecretCredential(tenant_id=tenant_id,
                                     client_id=client_id,
                                     client_secret=client_secret)
# Scope for Microsoft Graph API (default scope)
scopes = ["https://graph.microsoft.com/.default"]

# Create the GraphClient using the token from the credential
client = GraphServiceClient(credentials=credentials, scopes=scopes)

token = credentials.get_token(*scopes).token

# use the url you are interested in here
url = "https://graph.microsoft.com/v1.0/users"
headers = {
    "Authorization": f"Bearer {test_token}",
}

response = requests.get(url, headers=headers)
```

**Comment by nakasix** [comment]
Hello @shemogumbe ,

Thanks, that's exactly what I wanted :)
