### ISSUE TITLE
List items for `choice` column type returns DateTime instead int

### ISSUE THREAD

**Issue by mkkubins** [microsoftgraph/msgraph-sdk-python#937]
### Describe the bug

Hi, 

I am trying to get items for my SPO list as:
```
expand = "fields"
filter_ = f"fields/Modified gt '{last_modified}'"
query_params = ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters(
                    expand=expand,
                    top=self.TOP_ITEMS,
                    filter=filter_,
            )
request_configuration = RequestConfiguration(query_parameters=query_params)
items = await client.sites.by_site_id(
                    self.site_id
                ).lists.by_list_id(
                    list_id
                ).items.get(request_configuration=request_configuration)
````

I have SPO choice column defined as:

![image](https://github.com/user-attachments/assets/c74dbe64-a91f-4ea7-b309-239c11291d75)

Items returned are:
```
{'@odata.etag': '"0d9665c9-94e7-418b-bc92-3e5936c57d6d,30"',
 'Title': 'Test 2',
 'Choicecolumntest': DateTime(1000, 1, 1, 0, 0, 0, tzinfo=Timezone('UTC')),
}
```
It looks like there is a bug as it returns the `DateTime` instead `int`.

### Expected behavior

When extracting the choice and multi-choice columns data types should be reflected correctly. 

### How to reproduce

Create list with choice column type and get items from list.

![image](https://github.com/user-attachments/assets/c74dbe64-a91f-4ea7-b309-239c11291d75)

```
expand = "fields"
filter_ = f"fields/Modified gt '{last_modified}'"
query_params = ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters(
                    expand=expand,
                    top=self.TOP_ITEMS,
                    filter=filter_,
            )
request_configuration = RequestConfiguration(query_parameters=query_params)
items = await client.sites.by_site_id(
                    self.site_id
                ).lists.by_list_id(
                    list_id
                ).items.get(request_configuration=request_configuration)
````

### SDK Version

1.4.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

20.04.6 LTS (Focal Fossa)

**Comment by shemogumbe** [comment]
Hello @mkkubins thanks for using the SDK and for raising this.

This is likely an issue with JSON serialization.

What is your version the json srialization library are you using, is it the latest.

This could be related to https://github.com/microsoft/kiota-serialization-json-python/pull/358

Please confirm if you have this even with latest version of the serialization library?

**Comment by mkkubins** [comment]
After upgrading to the latest version issue is fixed. Thanks for help!
